### ISSUE TITLE
Static files with path="/"

### ISSUE THREAD

**Issue by proz89** [starlite-api/starlite#100]
Hi Guys,

I have a question about serving static files with `path="/"`.
I have found that the problem is here, in line 54.
https://github.com/starlite-api/starlite/blob/e9372128d490667402db2893e47f5cfda0917bab/starlite/asgi.py#L52-L55

Consider this static file configuration:
```python
[StaticFilesConfig(
    directories=[Path(pkg_resources.resource_filename(__name__, 'view_dist'))],
    path='/',
    html_mode=True
)]
```
and following `view_dist` subdirectories:
```
+--- view_dist
    +--- index.html
    +--- diagnostic
        +--- index.html
```

Requests and its reponses:
```bash
URL=http://192.168.200.100:8000

1. wget -O- $URL/                          --> 200 OK
2. wget -O- $URL/index.html                --> 200 OK
3. wget -O- $URL/diagnostic                --> 307 Temporary Redirect to new location (bad): http://192.168.200.100:8000diagnostic/
4. wget -O- $URL/diagnostic/               --> 307 like above
5. wget -O- $URL/diagnostic/index.html     --> 404 Not Found
```

The problems in points 3 and 4 come from the fact that line 54 in `asgi.py` file removed every occurrences of `/` from `scope['path']` and then the same `scope` is used in the `starlette/staticfiles.py` file to build the URL for redirecting purpose, but unfortunately `scope['path']` is lack of forward slashes.
https://github.com/encode/starlette/blob/d7cbe2a4887ad6b15fe7523ed62e28a426b7697d/starlette/staticfiles.py#L135-L139

After guarding line 54 (removing every `static_path='/'` from `scope['path']`) with extra `if` it works as expected.
```python
if static_path != '/':
    scope["path"] = scope["path"].replace(static_path, "") 
```

```bash
1. wget -O- $URL/                          --> 200 OK
2. wget -O- $URL/index.html                --> 200 OK
3. wget -O- $URL/diagnostic                --> 307 Temporary Redirect to new location (ok): http://192.168.200.100:8000/diagnostic/ --> 200 OK
4. wget -O- $URL/diagnostic/               --> 200 OK
5. wget -O- $URL/diagnostic/index.html     --> 200 OK
```

I have just started my journey with `starlite` so I do not know if and where are the side effects of commented out this line in `asgi.py`. Do you have any suggestions on what I should do to make all the previously mentioned requests work?

**Comment by Goldziher** [comment]
Thanks for the detailed issue and analysis!

I would suggest you clone the starlite repo and make your adjustment while running the tests. This will give you an indication of the impact of this change vis-a-vis other components. If your adjustment work, add another test to ensure that your use case is working correctly, and submit a PR.

**Comment by Goldziher** [comment]
ok @proz89 - I looked into this issue. Your solution will work well. Would you like to add a PR with the fix and a test to ensure its working? I can do this of course, but you already did most of the work :)

**Comment by Goldziher** [comment]
v1.3.2 released with this fix. thanks for your issue!
