### ISSUE TITLE
Bug: openapi render for multiple tags isn't consistent

### ISSUE THREAD

**Issue by ste-pool** [starlite-api/starlite#1004]
**Describe the bug**
When the openapi renders tags from both a controller and a route it is not deterministic. This may not be a bug? But it surprised me so thought I'd raise it.

I'm unsure if I'm doing something crazy but for a project, we check in the generated json openapi schema so we can browse the API live in gitlab. I've recently added a tag to both a controller and a route in it. But because the order of the tags isn't consistent they are going to keep flip flopping as we have a pre-commit that generates the json to make sure it's up to date. I hope that ramble makes sense...

**To Reproduce**
```python
from typing import Dict                                           
                                                                  
from starlite import Starlite, Controller, get                    
                                                                  
class TestController(Controller):                                 
    tags = ["a"]                                                  
                                                                  
    @get("/", tags=["b"])                                         
    def hello_world(self) -> Dict[str, str]:                      
        """Handler function that returns a greeting dictionary."""
        return {"hello": "world"}                                 
                                                                  
                                                                  
app = Starlite(route_handlers=[TestController])                   
print(app.openapi_schema.paths["/"].get.tags)                     
```
If you run that multiple times, you will see you get either:
```python
['a', 'b']
```
or
```python
['b', 'a']
```

**Additional context**
I believe the problem is [here](https://github.com/starlite-api/starlite/blob/835749112e8364c1516f45973c924774aca22ca9/starlite/openapi/path_item.py#L59) as it forces construction of a new set. Sorting them before returning would be viable as there shouldn't be _too many_ tags and it's a one time thing I believe?

But as I said, it may not be a problem you care about as I could be doing something silly.

**Comment by ste-pool** [comment]
Let me know if this is an okay approach and I'll try and make a PR with a test (But because it isn't determinstic the test can't be 100%?)

**Comment by Goldziher** [comment]
So the issue is the order of tags? I'd assume we probably use a set somewhere, which will jumble the order.

**Comment by ste-pool** [comment]
Yup 🙂 

> I believe the problem is [here](https://github.com/starlite-api/starlite/blob/835749112e8364c1516f45973c924774aca22ca9/starlite/openapi/path_item.py#L59) as it forces construction of a new set. Sorting them before returning would be viable as there shouldn't be too many tags and it's a one time thing I believe?

**Comment by Goldziher** [comment]
> Yup 🙂 
> 
> > I believe the problem is [here](https://github.com/starlite-api/starlite/blob/835749112e8364c1516f45973c924774aca22ca9/starlite/openapi/path_item.py#L59) as it forces construction of a new set. Sorting them before returning would be viable as there shouldn't be too many tags and it's a one time thing I believe?

Sure. Wanna add a PR?

**Comment by ste-pool** [comment]
Yeah, can do. I was just wondering if you do try to guarantee the repeatability of your schema generation from the same code - There may well be other places

**Comment by provinzkraut** [comment]
>  if you do try to guarantee the repeatability of your schema generation from the same code

Afaik we currently don't have a strong guarantee for this, but imo it makes sense as a requirement. The schema should not change if the code doesn't change.
