### ISSUE TITLE
Bug: Structlog example no longer works

### ISSUE THREAD

**Issue by ste-pool** [starlite-api/starlite#1008]
Me again. Sorry 🙈 

**Describe the bug**
Running the structlog example [here](https://starlite-api.github.io/starlite/1.48/usage/0-the-starlite-app/?h=structlog#using-structlog) results in an internal server error as of v1.45 (I think)

```
{"status_code":500,"detail":"TypeError(\"encode_json() got an unexpected keyword argument 'default'\")"}
```

The default encoder was changed [here](https://github.com/starlite-api/starlite/pull/891/files#diff-6b2294023eb60948cd9f742e4930255a72254daf74f9e3157df8d479a685b123R213)
Which doesn't accept the `default` argument given [here](https://github.com/hynek/structlog/blob/main/src/structlog/processors.py#L318)

I'm not sure if it's a structlog problem or a starlite problem.

Maybe the solution is to rename `enc_hook` to `default` then it mirrors the signature of `json.dumps`? I'm not sure, to be honest.

**To Reproduce**
Run the structlog example in the documentation:
```python
from starlite import Starlite, StructLoggingConfig, Request, get


@get("/")
def my_router_handler(request: Request) -> None:
    request.logger.info("inside a request")
    return None


logging_config = StructLoggingConfig()

app = Starlite(route_handlers=[my_router_handler], logging_config=logging_config)
```

**Additional context**

**Comment by provinzkraut** [comment]
> Maybe the solution is to rename `enc_hook` to `default` then it mirrors the signature of json.dumps

Yes, that would be the best solution. Wanna add  a PR?

**Comment by vtarchon** [comment]
This seems to be a regression at least since 2.0.0 

https://github.com/litestar-org/litestar/blob/v2.0.0/litestar/serialization/msgspec_hooks.py#L127

I'm seeing the same error when using msgspec encoder over the default `json.dumps`
