### ISSUE TITLE
Enhancement: Make `starlite run` work with servers besides uvicorn

### ISSUE THREAD

**Issue by provinzkraut** [starlite-api/starlite#1017]
**What's the feature you'd like to ask for.**
Currently using the `starlite run` command requires users to install uvicorn, which is impractical should they be using e.g. hypercorn or Daphne. I'd like for the CLI to be able to support those servers as well.

**Comment by kareemmahlees** [comment]
could you assign this to me

**Comment by provinzkraut** [comment]
After some consideration, I decided it's best to close this and not support this feature. It would require additional abstractions and make adding more options to the server harder, since it would restrict us to a subset of options available across all servers. Additionally, the benefit is low, since this is not intended to be used in production anyway, so supporting multiple servers isn't really relevant. 

@kareemmahlees Thanks for the effort you already put into this, and I'm sorry that they've been a bit wasted now.
