### ISSUE TITLE
Bug: validation error for array of enums in query parameters

### ISSUE THREAD

**Issue by Gamazic** [starlite-api/starlite#1033]
**Describe the bug**
type annotation `list[Enum]` doesn't support form style query parameters (E.g. `/resource?param=1,2,3`). Validation error occurs. 

**To Reproduce**
There are 2 handlers for enum array and string array. For string array everything works correctly. For enum array error occurs for form-style array expanding.

```python
from enum import Enum

from starlite import Starlite, get


class E(Enum):
    e1 = "e1"
    e2 = "e2"


@get("/r1-enum")
def h1_enum(params: list[E]) -> None:
    ...


@get("/r2-str")
def h2_str(params: list[str]) -> None:
    ...


app = Starlite(route_handlers=[h1_enum, h2_str])
```

Requests for tests:

```commandline
curl "localhost:8000/r1-enum?params=e1&params=e2" # OK
curl "localhost:8000/r1-enum?params=e1,e2" # VALIDATION ERROR

curl "localhost:8000/r2-str?params=e1&params=e2" # OK
curl "localhost:8000/r2-str?params=e1,e2" # OK
```

For `curl "localhost:8000/r1-enum?params=e1,e2" ` occurs the following error:
```json
{
  "status_code": 400,
  "detail": "Validation failed for GET http://127.0.0.1:8000/r1-enum?params=e1,e2",
  "extra": [
    {
      "loc": [
        "params",
        0
      ],
      "msg": "value is not a valid enumeration member; permitted: 'e1', 'e2'",
      "type": "type_error.enum",
      "ctx": {
        "enum_values": [
          "e1",
          "e2"
        ]
      }
    }
  ]
}
```

**Additional context**

Form-style array expending is default for OpenAPI request url generation.
![image](https://user-images.githubusercontent.com/33692402/210833183-b51f6f40-5702-4711-8125-5458303a698f.png)

**Comment by provinzkraut** [comment]
This has nothing to do with `Enum`s. The code for the other endpoint doesn't work as you think it does. Check the value of `params` you get in `h2_str`:

```python
from starlite import create_test_client, get


@get("/r2-str")
def h2_str(params: list[str]) -> list[str]:
    return params


with create_test_client(route_handlers=[h2_str]) as client:
    print(client.get("/r2-str?params=e1,e2").json())  # prints: ['e1,e2']
    print(client.get("/r2-str?params=e1&params=e2").json())  # prints: ['e1', 'e2']
```

This is not a valid way to pass multiple values for a query parameters in Starlite. This is parsed as one string with the value `'e1,e2'`, which of course is not a valid member of your `E` Enum.

Looks like this is an OpenAPI issue: It's generating a broken request. Does one @Goldziher @cofin one of you want to take a look at this?

**Comment by Goldziher** [comment]
one of us will.

**Comment by Gamazic** [comment]
I've found the place where Starlite generates parameters for a route. 

https://github.com/starlite-api/starlite/blob/624b0693c34b81f272b24fd385c2eb6bd77c5328/starlite/openapi/parameters.py#L113

`Parameter` model attribute `explode` is responsible for this behavior:

* If we put `explode=False` OpenAPI will generate in form `params=e1,e2`.
* If we put `expode=True` it will generate like this `params=e1&params=e2`.

And also there is a place in this function for choice other attributes for `Parameter` model depends on wheter it are `Coockie`, `Path`, `Query` params. So I think this is a good place to add and fill `expode` variable in if condition and then pass it into `Parameter` constructor.
____

Does any of `Header`, `Cookie`, `Path` parameters need "`expode`" their parameters by default?

**Comment by Goldziher** [comment]
Hi, we can add `explode` as an option to the Parameter, Cookie etc. Classes. PR is welcome!

**Comment by Gamazic** [comment]
Ok, let me clarify:

We will add additional parameter `explode` to this function?

https://github.com/starlite-api/starlite/blob/48251d886e61e68fc5ec2818af87cb7903217a0f/starlite/params.py#L13

And when user uses `Parameter`, he can select whether explode parameters in OpenAPI or no? E.g.

```python
@get("")
def handler(params: list[str] = Parameter(explode=True))
    ...
```

**Comment by Goldziher** [comment]
sure, but also to the other functions in starlite.params.

**Comment by Gamazic** [comment]
You're right, currently parser doesn't work like this. It can't parse as an array not exploded parameters (E.g. `/resource?param=1,2`). It works only like this `/resource?param=1&param=2` -> `[("param", 1), ("param", 2)]` .
So, maybe it doesn't make sense to add the `explode` argument, and we can just require OpenAPI to serialize arrays in exploded form?
