### ISSUE TITLE
[Question] Mount Piccolo Admin to Starlite app

### ISSUE THREAD

**Issue by sinisaos** [starlite-api/starlite#107]
Hello,
First I want to thanks all for this great new framework.
I would like to implement a Starlite asgi template for [Piccolo ORM](https://github.com/piccolo-orm). Piccolo ORM is an easy-to-use async orm with an integrated web admin. Piccolo ORM currently support Starlette, FastAPI, BlackSheep and Xpresso (all this frameworks support mounting asgi apps) and it would be nice if we could add Starlite support. I have already implemented a basic CRUD for Piccolo tables, but the main problem is mounting [Piccolo Admin](https://github.com/piccolo-orm/piccolo_admin) (which is already an asgi application) on the Starlite app. 

Starlite routing has a different design and you can only run the another asgi application through middleware which work,
```python
# some other import
from piccolo_admin.endpoints import create_admin
from starlite import Starlite
from home.piccolo_app import APP_CONFIG

# Piccolo Admin asgi app
admin_app = create_admin(tables=APP_CONFIG.table_classes)

class AdminMiddleware(MiddlewareProtocol):
    def __init__(self, app: ASGIApp):
        self.app = admin_app

    async def __call__(
        self, scope: Scope, receive: Receive, send: Send
    ) -> None:
        if scope["type"] == "http":
            request = Request(scope)
        await self.app(scope, receive, send)

app = Starlite(
    middleware=[AdminMiddleware],
   ...
)
```
but that didn't solve the main problem because admin app is mounted to root path and any other routes from `route_handlers` is not accesible (e.g `/tasks`). `Router` class also does not work because `route_handlers` accept standalone function or controller but not asgi app.
Is it possible to mount Piccolo Admin on the `/admin` route (other frameworks have `Mount` or `app.mount`), and the rest of the Starlite app is on the root path? 
Sorry for long comment (I hope I have explained the problem well) but any help appriciated. 
Thanks.

**Comment by Goldziher** [comment]
Hi, have you tried using the `asgi` decorator?

**Comment by sinisaos** [comment]
@Goldziher Yes, I have already tried this without success, because the asgi decorator function must return the response (if response is not ok we get 500 error `ImproperlyConfiguredException: Unable to serialize response content`) not the asgi app.

**Comment by Goldziher** [comment]
can you show me some code? how did you use it?

**Comment by sinisaos** [comment]
@Goldziher I'm not home right now. Tomorrow I will make a github repo with whole Piccolo template and post the link here.

**Comment by sinisaos** [comment]
@Goldziher Here is a [repo](https://github.com/sinisaos/starlite-piccolo). Starlite changes are in [app.py](https://github.com/sinisaos/starlite-piccolo/blob/main/app.py) and [endpoints.py](https://github.com/sinisaos/starlite-piccolo/blob/main/home/endpoints.py) and all other files are the same for all starter asgi templates. Take a look at the comments I left in the code. You can git clone repo better than fork because I will delete that repo.

**Comment by Goldziher** [comment]
Great, I'll check it in the evening.

**Comment by Goldziher** [comment]
Ok, so looking at the code, you currently have this:

```python
admin_app = create_admin(
    tables=APP_CONFIG.table_classes,
    # Required when running under HTTPS:
    # allowed_hosts=['my_site.com']
)

@asgi(path="/admin")
async def admin(scope: Scope, receive: Receive, send: Send) -> None:
    if scope["type"] == "http":
        if scope["method"] == "GET":
            response = Response({"hello": "world"}, status_code=HTTP_200_OK) ????
            await response(scope=scope, receive=receive, send=send)
        return
    response = Response(
        {"detail": "unsupported request"}, status_code=HTTP_400_BAD_REQUEST
    )
    await response(scope=scope, receive=receive, send=send)

# middleware for Piccolo Admin
class AdminMiddleware(MiddlewareProtocol):
    def __init__(self, app: ASGIApp):
        self.app = admin_app

    async def __call__(
        self, scope: Scope, receive: Receive, send: Send
    ) -> None:
        if scope["type"] == "http":
            request = Request(scope)
        await self.app(scope, receive, send)
```

But I don't understand why you'd use the response app there - response is an ASGI app that returns http responses. What you want is something like this instead: 

```python
admin_app = create_admin(
    tables=APP_CONFIG.table_classes,
    # Required when running under HTTPS:
    # allowed_hosts=['my_site.com']
)

@asgi(path="/admin")
async def admin(scope: Scope, receive: Receive, send: Send) -> None:
    await admin_app(scope=scope, receive=receive, send=send)
```

I also don't see the point for the middleware - a middleware is basically a pipeline to either evaluate a request or modify it, what you want is to basically have an ASGI app mounted on a specific path.

**Comment by sinisaos** [comment]
@Goldziher I agree with you and that’s why I asked the question here because I dont know how to make Piccolo Admin to work with Starlite.
```python
@asgi(path="/admin")
async def admin(scope: Scope, receive: Receive, send: Send) -> None:
    await admin_app(scope=scope, receive=receive, send=send)
```
This is not working (error `404 Not Found`).

**Comment by Goldziher** [comment]
I see. Is piccolo exposing an asgi app?

**Comment by sinisaos** [comment]
Here is Piccolo Admin [docs](https://piccolo-admin.readthedocs.io/en/latest/asgi/index.html) about asgi.
In Starlette or BlackSheep we can easily mount Piccolo Admin like this.
```python
app = Starlette()

app.mount(
    "/admin/",
    create_admin(
        tables=APP_CONFIG.table_classes,
        # Required when running under HTTPS:
        # allowed_hosts=['my_site.com']
    ),
)
```

**Comment by Goldziher** [comment]
so, you get a 404 because you didn't add the admin function into the route handlers:

```python
from piccolo.engine import engine_finder
from piccolo_admin.endpoints import create_admin
from starlette.types import Receive, Scope, Send

from home.endpoints import create_task, delete_task, home, tasks, update_task
from home.piccolo_app import APP_CONFIG
from starlite import (
    OpenAPIConfig,
    Starlite,
    StaticFilesConfig,
    TemplateConfig,
    asgi,
)
from starlite.template.jinja import JinjaTemplateEngine

# Piccolo Admin asgi app
admin_app = create_admin(
    tables=APP_CONFIG.table_classes,
    # Required when running under HTTPS:
    # allowed_hosts=['my_site.com']
)


# I don't know how to pass Piccolo Admin app to this route with asgi decorator
# because this function returns response and not asgi app and if response is not ok
# we get 500 error ImproperlyConfiguredException: Unable to serialize response content

@asgi(path="/admin")
async def admin(scope: Scope, receive: Receive, send: Send) -> None:
    admin_app(scope=scope, receive=receive, send=send)


async def open_database_connection_pool():
    try:
        engine = engine_finder()
        await engine.start_connection_pool()
    except Exception:
        print("Unable to connect to the database")


async def close_database_connection_pool():
    try:
        engine = engine_finder()
        await engine.close_connection_pool()
    except Exception:
        print("Unable to connect to the database")


app = Starlite(
    debug=True,
    route_handlers=[admin, home, tasks, create_task, update_task, delete_task],
    template_config=TemplateConfig(
        directory="home/templates", engine=JinjaTemplateEngine
    ),
    openapi_config=OpenAPIConfig(
        title="Starlite API",
        version="1.0.0",
    ),
    static_files_config=[
        StaticFilesConfig(directories=["static"], path="/static"),
    ],
    on_startup=[open_database_connection_pool],
    on_shutdown=[close_database_connection_pool],
)
```

**Comment by Goldziher** [comment]
I am getting an internal server error after i created the user as per the documentation served from 127.0.0.1:8000, but i am running the DB in docker etc. and have no clue if im using this correctly. I did attach a debugger to this stuff, but I am not sure I want to really delve into this code to figure out why the fast api based admin is not working 😉

**Comment by sinisaos** [comment]
I already added the admin function to `route_handlers` before and get an error.

> I am getting an internal server error after i created the user as per the documentation served from 127.0.0.1:8000, but i am running the DB in docker etc. and have no clue if im using this correctly. I did attach a debugger to this stuff, but I am not sure I want to really delve into this code to figure out why the fast api based admin is not working

No problem. There doesn't seem to be an easy way to mount Piccolo Admin, but it doesn't matter, I just wanted to give it a try. Thanks for your time and help. I will close this issue. Cheers.

**Comment by Goldziher** [comment]
Sure thing. Note- for my money this is mounted, there is an error being returned from it, but the cause of the error cannot be ascertain without debugging the code internally. The issue is no longer with the mount - its something else. @sinisaos

**Comment by sinisaos** [comment]
@Goldziher Nevermind. It was just my little experiment and trying out a new framework.
