### ISSUE TITLE
TestClient() ignores Starlite(on_startup=[...])

### ISSUE THREAD

**Issue by arthurxlee** [starlite-api/starlite#108]
For `my_app/main.py`
```python
import sys

from starlite import MediaType, Starlite, State, get


def on_startup(state: State):
    state.value = 1


@get(path="/health-check", media_type=MediaType.TEXT)
def health_check(state: State) -> str:
    try:
        print(f'{state.value=}')
        return "healthy"
    except Exception as exc:
        print(exc, file=sys.stderr)


app = Starlite(route_handlers=[health_check], on_startup=[on_startup])
```
This test will fail. `tests/test_health_check.py`
```python
from starlette.status import HTTP_200_OK
from starlite import TestClient

from my_app.main import app

client = TestClient(app=app)


def test_health_check():
    response = client.get("/health-check")
    assert response.status_code == HTTP_200_OK
    assert response.text == "healthy"
```
The error ```'State' object has no attribute 'value'``` indicates, `on_startup()` were not executed prior to the test execution.  It ran as expected when using uvicorn.

**Comment by Goldziher** [comment]
Thanks for the issue. I'll look into it in the weekend, unless you or someone else do so first.

**Comment by Goldziher** [comment]
Hi, ok I looked into it and updated the documentation. To have `on_startup` called you need to use the client as a context manager. Here is the test I added and passes:

```python
def test_test_client() -> None:
    def start_up_handler(state: State) -> None:
        state.value = 1

    @get(path="/test")
    def test_handler(state: State) -> None:
        assert state.value == 1

    app = Starlite(route_handlers=[test_handler], on_startup=[start_up_handler])

    with TestClient(app=app) as client:
        client.get("/test")
        assert app.state.value == 1
```

**Comment by arthurxlee** [comment]
Congratulations to this great project. Thank you for your help.

**Comment by arthurxlee** [comment]
A minor follow up,  the following code using pytest fixture should also look like:
`tests/test_health_check.py`
```python
from starlette.status import HTTP_200_OK
from starlite import TestClient


def test_health_check(test_client: TestClient):
    with test_client as client:
        response = client.get("/health-check")
        assert response.status_code == HTTP_200_OK
        assert response.text == "healthy"
```

**Comment by Goldziher** [comment]
> A minor follow up,  the following code using pytest fixture should also look like:
> `tests/test_health_check.py`
> ```python
> from starlette.status import HTTP_200_OK
> from starlite import TestClient
> 
> 
> def test_health_check(test_client: TestClient):
>     with test_client as client:
>         response = client.get("/health-check")
>         assert response.status_code == HTTP_200_OK
>         assert response.text == "healthy"
> ```

True. Would you like to add a PR?
