### ISSUE TITLE
Bug: Jinja support is incorrectly specified in pyproject.toml

### ISSUE THREAD

**Issue by andersbogsnes** [starlite-api/starlite#1080]
**Describe the bug**
Installing starlite with `pip install starlite[jinja]` as outlined in the documentation fails, since there's no such extra defined in pyproject.toml

https://starlite-api.github.io/starlite/latest/usage/16-templating/
https://github.com/starlite-api/starlite/blob/v1.49.0/pyproject.toml#L119

In addition, the dependency specified in `standard` is pointing to the deprecated Jinja package, as opposed to the currently supported Jinja2 package

**To Reproduce**
Try to install starlite with jinja extra

**Comment by provinzkraut** [comment]
@andersbogsnes Thanks for the report! Should be fixed by #1081!

**Comment by pomma89** [comment]
I just wanted to warn you that I think that #1081 introduced a small typo in `pyproject.toml`, as `jinja` is written as `jina` 😄 

https://github.com/starlite-api/starlite/blob/main/pyproject.toml#L127

![image](https://user-images.githubusercontent.com/4697032/213928203-c98542e1-c8c9-47b2-aea2-74da2875a50a.png)

Thanks,
Alessio

**Comment by provinzkraut** [comment]
@pomma89 Thanks, I made a patch release to fix this!
