### ISSUE TITLE
[documentation] Continous update

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#11]
The documentation is an ongoing project - we would like to ask the community to contribute. PRs including any of the following will be welcome:

1. edits and rewrites to improve the documentation in terms of grammar, syntax, structure
2. improvements to examples - better code or cleaner code, fixes, additional examples
3. additional documentation
4. improvements to the documentation website (using mkdocs metarial theme)

You are also welcome to discuss in this thread your opinion regarding required additions or improvements to the documentation.

**Comment by vincentsarago** [comment]
First, as of today the documentation is nice and covers most of the new comers need 👏 

## State and Lifecycle documentation

One thing I struggled with, coming from FastAPI world, was the lifecycle configuration. The `my_app/postgres.py` example in https://starlite-api.github.io/starlite/usage/0-the-starlite-app/?h=lifecycle nicely explains how to create startup/shutdown function but not what the `state` object is and how to use it.

Option: in FastAPI I used to store the DB connection pool directly in the application `state` (so it would be available in `request.app.state`, not sure if this is possible with Starlite.

**Comment by philvarner** [comment]
The URLs for the openapi schema are hard to find and the endpoint `/schema` is a 404. 

In 
https://starlite-api.github.io/starlite/usage/12-openapi/?h=openapi#the-openapi-controller
the urls to /schema/openapi.yaml etc aren't mentioned until the last section, when these should be mentioned at the very top. 

I tried just going to `/schema` b/c it was mentioned other places in the docs, but it gave a 404, so I thought I had the wrong place. Having a simple HTML landing page that points to the yaml, json, and redoc urls would be great.

**Comment by Goldziher** [comment]
@philvarner thanks. Do you want to edit the docs?

**Comment by philvarner** [comment]
I don't, sorry I can't contribute right now.

**Comment by Goldziher** [comment]
thats fine. @yudjinn is taking care of this
