### ISSUE TITLE
List[User] in openapi is displayed as Any

### ISSUE THREAD

**Issue by zy7y** [starlite-api/starlite#111]
# code
```python
from typing import List

from starlite import Starlite, Controller, Partial, get, post, delete, patch, put, OpenAPIConfig

from pydantic import BaseModel, UUID4


class User(BaseModel):
    first_name: str
    last_name: str
    id: UUID4


class UserController(Controller):
    path = "/users"

    @post()
    async def create_user(self, data: User) -> User:
        ...

    @get()
    async def list_users(self) -> List[User]:
        ...

    @patch(path="/{user_id:uuid}")
    async def partially_update_user(self, user_id: UUID4, data: Partial[User]) -> User:
        ...

    @put(path="/{user_id:uuid}")
    async def update_user(self, user_id: UUID4, data: User) -> User:
        ...

    @get(path="/{user_id:uuid}")
    async def get_user(self, user_id: UUID4) -> User:
        ...

    @delete(path="/{user_id:uuid}")
    async def delete_user(self, user_id: UUID4) -> User:
        ...

app = Starlite(route_handlers=[UserController])
```
# result
![image](https://user-images.githubusercontent.com/67154681/169229144-bb6c3afd-b73b-4c3d-9e89-c6d4e2c59d19.png)
And how to access the interactive openapi documentation fastAPI is used in /docs
Can you tell me what to do?

**Comment by Goldziher** [comment]
Evening and thanks for reporting the issue. I will take a look in the weekend.

As for the question regarding "interactive" openapi docs. This is Swagger UI. It doesn't support OpenAPI 3.1 and until it does it will not be included in starlite, see this issue for tracking: https://github.com/swagger-api/swagger-ui/issues/5891

**Comment by zy7y** [comment]
Thank you for your reply

**Comment by zy7y** [comment]
> Evening and thanks for reporting the issue. I will take a look in the weekend.
> 
> 晚上好，谢谢你报道这个问题。我将在周末去看看。
> 
> As for the question regarding "interactive" openapi docs. This is Swagger UI. It doesn't support OpenAPI 3.1 and until it does it will not be included in starlite, see this issue for tracking: [swagger-api/swagger-ui#5891](https://github.com/swagger-api/swagger-ui/issues/5891)
> 
> 至于“交互式”openapi 文档的问题。这是 Swagger UI。它不支持 OpenAPI 3.1，除非支持，否则它不会包含在 starlite 中，请参见此跟踪问题: swagger-api/swagger-ui # 5891

Thank you for your reply

**Comment by Goldziher** [comment]
So, I could not reproduce this. Can you perhaps create a demo repo that shows this issue?

**Comment by zy7y** [comment]
sorry, here have user model attributes
![image](https://user-images.githubusercontent.com/67154681/170901415-45cea763-aaf9-4a52-ad1e-f5b64cd3bbbc.png)
