### ISSUE TITLE
Enhancement: Support returning token in response body with JWTAuth

### ISSUE THREAD

**Issue by mje-nz** [starlite-api/starlite#1118]
**What's the feature you'd like to ask for.**
Currently `JWTAuth` returns the token in a header, and `JWTCookieAuth` also returns it in a cookie. This is fine for login endpoints that return a User instance or similar, but login endpoints that return the token are hard to implement, since the calling code never has access to the actual token.

It would be nice if we could access the token somehow during the login process. Perhaps `JWTAuth.login` could take a `response_body_factory` callable that receives the token?

**Additional context**
Stoplight Elements doesn't seem to support displaying response headers or cookies, which makes it a bit less useful for projects using `JWTAuth` currently.

**Comment by peterschutt** [comment]
@cofin do you have any bandwidth to take a look at this one?

**Comment by Goldziher** [comment]
Done, will be included in 2.0

**Comment by mje-nz** [comment]
Apologies for the delay; thanks for the feature 🚀
