### ISSUE TITLE
Enhancement: Allow configuration of an application via an `AppConfig` instance

### ISSUE THREAD

**Issue by provinzkraut** [starlite-api/starlite#1120]
We already have `AppConfig` in place, so it would be nice to be able to do something like 

```python
from starlite import Starlite, AppConfig

config = AppConfig(...)

app = Starlite.from_config(config)
```

**Comment by Goldziher** [comment]
Cool, why not

**Comment by wassafshahzad** [comment]
How would you recommend this be implemented ? 
Should the from_config just call __init__ under the hood
```
@classmethod
def from_config(cls, config):
    return cls(**config) // this wont work since config is not a dict
``` 
Something like this ?

**Comment by peterschutt** [comment]
>  Should the from_config just call init under the hood

Something like calling `Starlite(**config.dict(exclude_unset=True))` would certainly work, but then we just turn around and construct another `AppConfig` object inside `__init__` (not that performance is an issue, as it only happens once).

We could add `app_config: Optional[AppConfig] = None` to the `Starlite.__init__()` signature, and if it is provided, we use that as the initial config object that is passed to the `on_app_init` hooks, in lieu of constructing our own. If that was the case, the constructor method wouldn't be necessary as we could simply call `Starlite(config=AppConfig(...))`, but we'd have to work out precedence rules, e.g., if both `route_handlers` and `config` were given to the constructor, then should they be merged, would one take precedence over the other etc etc.

Starlite has _a lot_ of `__init__` params, maybe an evolution into 2.0 could be adding the `config` object to the signature, and then in 2.0 making config of the app _only_ via config object.

**Comment by provinzkraut** [comment]
> maybe an evolution into 2.0 could be adding the config object to the signature, and then in 2.0 making config of the app only via config object.

I'm not sure about that. Feels a bit cumbersome *having* to construct a config object and pass it immediately to `Starlite`. 

I think for now, the best approach would be to do what you described, but `@overload` `__init__`, to only allow either kwargs or a config object, and then just discard all kwargs if a config object is passed.

**Comment by peterschutt** [comment]
> I think for now, the best approach would be to do what you described, but @overload __init__, to only allow either kwargs or a config object, and then just discard all kwargs if a config object is passed.

SGTM. We'd need to make `route_handlers` optional for that, but I can't see why that should be a problem, and also put default values on the `AppConfig` object

**Comment by wassafshahzad** [comment]
Can we initialize AppConfig from .env's ?

**Comment by provinzkraut** [comment]
No. It's mostly Python objects, so adding `.env`-file support doesn't make a lot of sense.

**Comment by peterschutt** [comment]
There's not a lot of settings there that would lend to being directly set by environment.

I go pretty heavy on the config-via-environment approach in [starlite-saqlalchemy](https://github.com/topsport-com-au/starlite-saqlalchemy/blob/main/src/starlite_saqlalchemy/settings.py), but mostly that is using environment to configure things like cache config, openapi config, sqlalchemy plugin etc, which are then passed to the app via `AppConfig` as a `on_app_init` hook.

**Comment by wassafshahzad** [comment]
@provinzkraut @peterschutt  Thank you for informing, One more question generally we could set defaults in dunder init for AppConfig or create a settings.py like how django does it (Although I think that would over complicate things for this issue)

**Comment by provinzkraut** [comment]
>  One more question generally we could set defaults in dunder init for AppConfig

If you take a look at `AppConfig`, you'll see that it's a Pydantic model. So the correct way to set defaults would be on the class attributes themselves. 

I don't think `settings.py` fits the Starlite way of doing things, and I don't see any benefit of this. Even for Django this makes things more complicated. It's opaque "automagic", which almost never is a good idea.

**Comment by wassafshahzad** [comment]
ok thanks for the help

**Comment by provinzkraut** [comment]
> The one that stands out to me most is the lifecycle hooks., having a `LifecycleHookConfig` makes sense as a grouping IMO, and would significantly reduce the number of parameters to the application.

Well it would certainly make sense, and it'd be 8 parameters we could remove. On the other hand

```python
app = Starlite(..., on_startup=on_startup)
```
is way more convenient than

```python
app = Starlite(..., lifecycle_hooks_config=LifecycleHooksConfig(on_startup=on_startup))
```

**Comment by JacobCoffee** [comment]
@wassafshahzad were you working on this?

**Comment by Goldziher** [comment]
@JacobCoffee - you can work on this

**Comment by wassafshahzad** [comment]
> @wassafshahzad were you working on this?
> 

Yes will have a pr up by tomorrow
