### ISSUE TITLE
DTO Factory changing not nullable fields to Optional

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#113]
SQLAlchemy 1.4.36, Starlite 1.3.3, pydantic 1.9.1

```python
from pydantic import create_model
from sqlalchemy import Column, String
from sqlalchemy.orm import declarative_base
from starlite.dto import DTOFactory
from starlite.plugins.sql_alchemy import SQLAlchemyPlugin

Base = declarative_base()


class MyModel(Base):
    __tablename__ = "whatever"
    id = Column(String, nullable=False, primary_key=True)


FromPlugin = SQLAlchemyPlugin().to_pydantic_model_class(MyModel)
print(repr(FromPlugin.__fields__["id"]))
# ModelField(name='id', type=str, required=True)

FromDTO = DTOFactory(plugins=[SQLAlchemyPlugin()])("FromDTO", MyModel)
print(repr(FromDTO.__fields__["id"]))
# ModelField(name="id", type=Optional[str], required=False, default=None)

print(FromPlugin.__fields__["id"].field_info.default)
# Ellipsis
print(FromPlugin.__fields__["id"].default)
# None

print(create_model("Test", id=(str, None)).__fields__)
# {'id': ModelField(name='id', type=Optional[str], required=False, default=None)}

```

https://github.com/starlite-api/starlite/blob/b95519c6c325074d9209f36119d749532d506ae1/starlite/dto.py#L140-L145

The model field hits the first line of the if statement, `if model_field.field_info.default is not Undefined:`, and as you can see in the above script, for the `FromPlugin` model that is `Ellipsis`, so it enters the block and returns `(field_type, None)`, where `None` is `model_field.default`. The 2nd element of the tuple being `None` makes `create_model()` make the type Optional.

**Comment by Goldziher** [comment]
Looks like a bug. Wanna make a PR?

**Comment by peterschutt** [comment]
I'll have a crack, but I'm not super familiar with pydantic internals.

Is there anything special about using the `...` in place of `Undefined`? 

`DTOFactory` changes any `FieldInfo.default` from `PydanticUndefined` to `...`. Am I right that this means the `...` symbolizes that there is no default, so not-optional, which internally pydantic represents with `PydanticUndefined`?

In the same context the method doesn't treat `...` the same as `PydanticUndefined`: 

```python
if model_field.field_info.default is not Undefined: 
```

So, if `PydanticUndefined` and `...` are interchangeable for inferring the presence of a field default, then that line should probably be:

```python
if model_field.field_info.default is not in (..., Undefined): 
```
That way, plugins or users can create fields with `(str, ...)` or `(str, Undefined)` and it is treated the same way.

However, the method still changes a field that is originally defined as `(str, Undefined)` to `(str, ...)`. 

If the field isn't in `exclude` or `field_mappings`, does it really need to be reconstructed at all? We could just pass the existing `FieldInfo` object straight through to `create_model()` and save a bit of complexity.

That is supported by `create_model()` ([ref](https://github.com/samuelcolvin/pydantic/blob/8846ec4685e749b93907081450f592060eeb99b1/pydantic/main.py#L943-L946)):

> for complex use-cases, in the format `<name>=<FieldInfo>`

Although that docstring seems incorrect (see: https://github.com/samuelcolvin/pydantic/issues/4041), i needed `<name=(<field type>, <FieldInfo>)`.

Making the above changes exposed a bug with `dto.get_field_types()`. All tests passed except this one:

```
________________________________________________________ test_conversion_from_model_instance[VanillaDataClassPerson-exclude1-field_mapping1-plugins1] ________________________________________________________

model = <class 'tests.VanillaDataClassPerson'>, exclude = ['id'], field_mapping = {'complex': 'ultra'}, plugins = []

    @pytest.mark.parametrize(  # type: ignore[misc]
        "model, exclude, field_mapping, plugins",
        [
            [Person, ["id"], {"complex": "ultra"}, []],
            [VanillaDataClassPerson, ["id"], {"complex": "ultra"}, []],
            [Pet, ["age"], {"species": "kind"}, [SQLAlchemyPlugin()]],
        ],
    )
    def test_conversion_from_model_instance(model: Any, exclude: list, field_mapping: dict, plugins: list) -> None:
        DTO = DTOFactory(plugins=plugins)("MyDTO", model, exclude=exclude, field_mapping=field_mapping)
    
        if issubclass(model, (Person, VanillaDataClassPerson)):
            model_instance = model(
                first_name="moishe",
                last_name="zuchmir",
                id=1,
                optional="some-value",
                complex={"key": [{"key": "value"}]},
                pets=None,
            )
        else:
            model_instance = cast(Type[Pet], model)(  # type: ignore
                id=1,
                species=Species.MONKEY,
                name="Mike",
                age=3,
                owner_id=1,
            )
>       dto_instance = DTO.from_model_instance(model_instance=model_instance)

tests/test_dto_factory.py:181: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
starlite/dto.py:51: in from_model_instance
    return cls(**values)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   pydantic.error_wrappers.ValidationError: 1 validation error for MyDTO
E   pets
E     none is not an allowed value (type=type_error.none.not_allowed)

pydantic/main.py:331: ValidationError
```

I exposed that error in the test `test_get_field_type_optional()`:

```python
def test_get_field_type_optional() -> None:
    optional_field = Person.__fields__["optional"]
    pets_field = Person.__fields__["pets"]
    assert get_field_type(optional_field) == Optional[str]
    assert get_field_type(pets_field) == Optional[List[PydanticPet]]
```

So the patch includes a fix for that, but please have a look and tell me what to do, as I've only applied the patch to fix the direct errors that I found. I don't know if that fix needs to apply to the other branches of that function.

Please checkout the patch here and let me know if you want anything to change before i PR: https://github.com/peterschutt/starlite/commit/bacc31340d3d0e1762dcbf83ace150bffd0d5168

**Comment by peterschutt** [comment]
Lmk, if you want me to break up the patch into separate issues.

**Comment by Goldziher** [comment]
So in pydantic `...` usually means that the field is required. The pydantic `Undefined` class is meant to signify that no value is given, even not None - because None is a specific value in type checks.

**Comment by peterschutt** [comment]
I'll break the issues out.
