### ISSUE TITLE
DTOFactory.__call__() unnecessarily modifies FieldInfo

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#115]
The field is neither excluded, nor mapped so the least surprising thing would be that the field stays the same. This can be achieved as `create_model()` accepts `FieldInfo` for attributes.

```python console
>>> class Example(BaseModel):
...     not_optional: str
... 
>>> ExampleDTO = DTOFactory(plugins=[])("ExampleDTO", Example, exclude=[], field_mapping={}, field_definitions={})
>>> Example.__fields__["not_optional"].field_info.default
PydanticUndefined
>>> ExampleDTO.__fields__["not_optional"].field_info.default
Ellipsis
```

`create_model` doc:

>        :param field_definitions: fields of the model (or extra fields if a base is supplied)
>         in the format `<name>=(<type>, <default default>)` or `<name>=<default value>, e.g.
>         `foobar=(str, ...)` or `foobar=123`, or, for complex use-cases, in the format
>         `<name>=<FieldInfo>`, e.g. `foo=Field(default_factory=datetime.utcnow, alias='bar')`

But also see: https://github.com/samuelcolvin/pydantic/issues/4041 as turns out it still needs to be passed as `(<type>, <FieldInfo>)` tuple.

**Comment by peterschutt** [comment]
TBH, the more I think about this one, the less it bothers me. Unless you had someone with a specific issue it probably isn't worth the churn.

It might be a slight improvement in efficiency by passing the field info straight through, but I'm sure most of the time `DTOFactory` will be called in module scope anyway, so who cares. So then, if the only issue is that `model_info.default` flips from `Undefined` to `...`, I'll leave you to decide how much you care about that, but it wouldn't bother me at all if you close this off and #116 .

**Comment by Goldziher** [comment]
please rebase ur PR and we can proceed.
