### ISSUE TITLE
Mypy false positive: Name "asgi" already defined (by an import)

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#1162]
```
starlite/config/static_files.py:5: error: Name "asgi" already defined (by an import)  [no-redef]
starlite/config/static_files.py:100: error: Returning Any from function declared to return "ASGIRouteHandler"  [no-any-return]
starlite/config/static_files.py:100: error: Module not callable  [operator]
```
I'm getting these errors from `pre-commit run mypy --all-files`.

`static_files.py` imports `asgi` with `from starlite.handlers import asgi`, if I change that to `from starlite.handlers.asgi import asgi` the issue goes away.

Obviously smth to do with the fact that the name of the decorator is the same as the name of the module, but looking at `starlite.handlers.__init__`, the imports seem defined properly.

```python-console
>>> from starlite.handlers import asgi
>>> asgi
<class 'starlite.handlers.asgi.ASGIRouteHandler'>
```

I think this is the relevant issue: https://github.com/python/mypy/issues/7203

**Comment by provinzkraut** [comment]
So, I think this is more of a "questionable design choice" on our end as it's a bug. `starlite.handlers.asgi` **is** ambiguous because `starlite/handlers/asgi.py` as a file exists, but so does `starlite.handlers.asgi`, as a class.

Proper resolution IMO would be to rename `starlite/handlers/asgi.py` > `starlite/handlers/asgi_handlers.py` (and maybe the others for consistency as well?)

**Comment by peterschutt** [comment]
Yep, its ambiguous as it is. I can't see why changing the module name should be that big a deal as most would be importing from the package namespace.

> and maybe the others for consistency as well?

I think we'll have to for `websocket` too, as that should be the same issue (we mustn't expose it anywhere in the tests). While we have the chance to break stuff for 2.0 we may as well.

**Comment by Goldziher** [comment]
Sure
