### ISSUE TITLE
Bug: Issue with reload

### ISSUE THREAD

**Issue by Alc-Alc** [starlite-api/starlite#1191]
**Describe the bug**
When I start my app using starlite run -r I get the following error

INFO:     Will watch for changes in these directories: ['/Users/alc/starlite-apps/starlite_test']
ERROR:    [Errno 48] Address already in use

If I stop that and run it without -r it works, so I guess my port is not blocked

**To Reproduce**
Save this as `app.py`

```python
from starlite import get, Starlite

@get('/')
def route() -> str:
    return 'Hello'

app = Starlite([route])
```

**Additional context**
@provinzkraut in discord help suggested a workaround using ` uvicorn <app file>:<application object> --reload` and also linked https://github.com/encode/uvicorn/issues/1045

**Comment by Goldziher** [comment]
ok, assigning this to @provinzkraut for now - he will check it once he feels bette (covid got him).
