### ISSUE TITLE
Bug: Can not serve static file in `/` path

### ISSUE THREAD

**Issue by LazyGeniusMan** [starlite-api/starlite#1201]
**Describe the bug**
If `StaticFilesConfig` path is `/`, instead of serving the static file in root path, it gave `starlite.exceptions.http_exceptions.ImproperlyConfiguredException: 500: Path parameters are not allowed under a static or mount route.` error from `starlite.asgi.routing_trie.validate.validate_node`

**To Reproduce**
1. Install Starlite and Uvicorn
2. Setup a `StaticFilesConfig` with `/` as a path like:
```
from starlite import Starlite, StaticFilesConfig

PATH = "Some Path"

app = Starlite(
    route_handlers=[],
    static_files_config=[
        StaticFilesConfig(directories=[PATH], path="/", html_mode=True),
    ],
)
```
2. Run `uvicorn main:app`

**Additional context**
As comparison, `starlette` can do this just fine with this code:
```
from starlette.applications import Starlette
from starlette.routing import Mount
from starlette.staticfiles import StaticFiles

PATH = "Some Path"

routes = [
    Mount('/', app=StaticFiles(directory=PATH, html=True)),
]

app = Starlette(routes=routes)
```

**Comment by JacobCoffee** [comment]
This was part of a discussion in the #chat channel on the Starlite Discord

https://discord.com/channels/919193495116337154/919193495690936353/1075524323378483361

**Comment by Goldziher** [comment]
Ok, issue was not apparent in our tests - at all, because the bug was not in the routing but rather in validation - and it was failing on the documentation. Its now fixed. It should be cherry picked into the LTS version too after we merge it.
