### ISSUE TITLE
Documentation: Template link showing as API Reference

### ISSUE THREAD

**Issue by travisjungroth** [starlite-api/starlite#1202]
<img width="882" alt="Screenshot 2023-02-15 at 3 18 26 PM" src="https://user-images.githubusercontent.com/11671107/219214392-c3ae88fb-ee6a-413a-a45c-7ca9c52aeb8f.png">

I believe this circled `API Reference` is supposed to say Template and be a link. 

Page: https://starliteproject.dev/lib/usage/responses.html#template-responses
Code:
https://github.com/starlite-api/starlite/blame/1fdb997f35acfc5981719bbdb21df8334faa166f/docs/lib/usage/responses.rst#L642

Maybe part of a bigger thing that `API Reference` doesn't seem to be correct in a few places. There's something similar under [The Redirect Class](https://starliteproject.dev/lib/usage/responses.html#the-redirect-class).

**Comment by Jarmos-san** [comment]
Thanks for reporting it! I'm working on restructuring the entire "Usage Guidelines" section of the documentations so I'll look into it some time in the near future. And yes, the API reference links are broken at certain places, so if you come across any more such inconsistencies, let us know?

**Comment by provinzkraut** [comment]
Hm. This is odd. Sphinx isn't complaining about a missing reference for this, I'm not sure why. I'll investigate. @travisjungroth thanks for reporting!

**Comment by travisjungroth** [comment]
Happy to let you know anything else I run across and thanks for looking!

**Comment by provinzkraut** [comment]
Resolved by #1291
