### ISSUE TITLE
Enhancement: Improve startup time

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#1214]
According to @provinzkraut:

```text
Tthe time it takes to import starlite is exorbitant compared to other libraries.
starlette: 0.064s
fastapi: 0.4s
flask: 0.2s
sanic: 0.2s
django: 0.07
sqlalchemy: 0.19s
pandas: 0.3s
starlite: 1s 
```

The goal of this issue is to ensure our startup time is at least as fast as the fastapi, with the aim of being significantly faster.

**Comment by provinzkraut** [comment]
To add some context: This is a very naive measurement done by running `time python -m "import <library>"`, which is not necessarily representative of starting up an entire application, but indicative of the issue at play.
