### ISSUE TITLE
Bug: `JWTAuth.login` raises `SerializationException` despite `type_encoders` settings

### ISSUE THREAD

**Issue by LonelyVikingMichael** [starlite-api/starlite#1219]
**Describe the bug**
`JWTAuth.login` instantiates and returns a `starlite.Response` object that does not respect custom defined `type_encoders`. This will raise an exception if the response body custom types such as `asyncpg.pgproto.pgproto.UUID` etc.

**To Reproduce**
N/A

**Additional context**
This wasn't a problem in older releases before `type_encoders` were introduced, as we'd override the Response class directly to customise serialization.

**Comment by Goldziher** [comment]
can you give me an MCVE? or a failing test? would be very helpful to have it.

**Comment by LonelyVikingMichael** [comment]
My mistake, project was using an older Starlite version.
