### ISSUE TITLE
Documentation: Maybe the description concerning the file containing the instance of Starlite and the CLI not consistent

### ISSUE THREAD

**Issue by konsilanto** [starlite-api/starlite#1221]
[Application object](https://starliteproject.dev/lib/usage/the-starlite-app.html#application-object) mentions that the instance of `Starlite` is typically placed inside a file called `main.py`. The `CLI` [Autodiscovery](https://starliteproject.dev/lib/usage/cli.html#autodiscovery) is only searching for `app.py`, `application.py`, `asgi.py`, and `app/__init__.py`. Maybe `CLI` or the documentation could be changed to be more clearer/consistent.

**Comment by provinzkraut** [comment]
I think we just need to reword the section about the application object. Placing that in a `main.py` file is not really a convention we promote anywhere else, and as such is not honored by the CLI as well. 

Nevertheless, I intended to extend the autodiscovery's "best match" functionality in such a way that it would pick up an app in a file of any name within the current working directory, should it not find an app in one of the canonical paths.

I'll open an issue to track this.

**Comment by konsilanto** [comment]
Ok, thanks! Then we could close this particular issue.
