### ISSUE TITLE
Piccolo Admin test app 

### ISSUE THREAD

**Issue by sinisaos** [starlite-api/starlite#1235]
Hi,
I don't know if it matters, but the Piccolo Admin app in [test_apps](https://github.com/starlite-api/starlite/tree/main/test_apps/piccolo_admin_app) doesn't work as it should because the Piccolo ORM doesn't support automatic database migrations for Sqlite and we have to manually create the tables to fix it. If you think it would be good to fix the Piccolo Admin test app I can make a PR.

**Comment by Goldziher** [comment]
@sinisaos hi and sure, why not? If you want to maintain it - that would be nice.

**Comment by sinisaos** [comment]
@Goldziher Thanks for quick response. During the day I will do a PR.
