### ISSUE TITLE
Refactor: Reduce reliance on `pydantic.BaseModel`

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#1239]
Internally we use pydantic models for the following types:

- `config.allowed_hosts.AllowedHostsConfig`
- `config.app.AppConfig`
- `config.cache.CacheConfig`
- `config.compression.CompressionConfig`
- `config.cors.CORSConfig`
- `config.csrf.CSRFConfig`
- `config.openapi.OpenAPIConfig`
- `config.static_files.StaticFilesConfig`
- `contrib.jwt.jwt_auth.OAuth2Login`
- `contrib.jwt.jwt_auth.Token`
- `contrib.opentelemetry.config.OpenTelemetryConfig`
- `middleware.logging.LoggingMiddlewareConfig`
- `middleware.rate_limit.RateLimitConfig`
- `middleware.session.base.BaseBackendConfig`
- `openapi.datastructures.ResponseSpec`
- `plugins.sql_alchemy.config.SQLAlchemySessionConfig`
- `plugins.sql_alchemy.config.SQLAlchemyEngineConfig`
- `plugins.sql_alchemy.config.SQLAlchemyConfig`
- `utils.exception.ExceptionResponseContent`

Any of these that do not explicitly rely on pydantic functionality for some reason should probably be migrated to dataclasses.

**Comment by Goldziher** [comment]
Addressed in #1242
