### ISSUE TITLE
Documentation: Ambiguity concerning operationId

### ISSUE THREAD

**Issue by konsilanto** [starlite-api/starlite#1240]
I think there is an ambiguity concerning `operationId` in [Semantic handler decorators](https://starliteproject.dev/lib/usage/route-handlers.html#semantic-handler-decorators):

>  each operation should be distinguished by a unique operationId

In this context the reader assumes that the kwarg is named `operationId` but, actually, it is called `operation_id`. Therefore, I suggest to make it clear that the OpenApi `operationId` has to be specified with the kwarg `operation_id`.

**Comment by Goldziher** [comment]
sure, you're welcome to add a fix.
