### ISSUE TITLE
Bug: Optional query params

### ISSUE THREAD

**Issue by WardPearce** [starlite-api/starlite#1249]
**Describe the bug**
Defining optional string query parameters has unexpected behavior.

**To Reproduce**
Define a query param like the following.
```py
@get(
    "/{paste_id:str}",
    middleware=[RateLimitConfig(rate_limit=("minute", 60)).middleware],
)
async def get_paste(paste_id: str, access_code: Optional[str] = None) -> PasteModel:
    return await Paste(paste_id).get(access_code=access_code)
```

Then the API schema looks like this
https://api.paaster.io/schema#operation/ControllerPasteGetPaste

![image](https://user-images.githubusercontent.com/27844174/221800633-2ba423fe-7c3a-45fd-a857-b582eba37a3f.png)

**Comment by peterschutt** [comment]
Looks like this is fixed somewhat on `main` branch. This exact error doesn't occur, but I can create another issue with `__future__.annotations` and `IF_TYPECHECKING`.. but I won't get side-tracked here.

Will just need to work out where the fix came from and we can do a patch for 1.51.

**Comment by peterschutt** [comment]
This is on main:

![image](https://user-images.githubusercontent.com/20659309/221807082-b6fa881d-218a-4abc-bbf0-c84ba813cd61.png)

**Comment by peterschutt** [comment]
Patch is now in https://github.com/starlite-api/starlite/tree/v1.51 - would you like to test before I make a release?

**Comment by WardPearce** [comment]
Hey, currently not near my PC but will be able to test latet today.

**Comment by peterschutt** [comment]
sweet, no rush.

**Comment by WardPearce** [comment]
![image](https://user-images.githubusercontent.com/27844174/222129488-ee56d3f1-c9a2-4246-9238-a7666bc4e6ef.png)

Yup can confirm is working as expect now, thank you!

**Comment by peterschutt** [comment]
Thanks @WardPearce - rolling out `v1.51.6` as we speak!
