### ISSUE TITLE
Bug: `SessionCookieConfig` import DeprecationWarning - suggested import path does not exist

### ISSUE THREAD

**Issue by LonelyVikingMichael** [starlite-api/starlite#1284]
**Describe the bug**
In Starlite >= 1.47, the statement `from starlite.middleware.session.cookie_backend import CookieBackendConfig` raises a DeprecationWarning:
```
DeprecationWarning: Import of deprecated import 'SessionCookieConfig from starlite.middleware.session'.
Deprecated in starlite 1.47.0. This import will be removed in the next major version.
Use "'from startlite.middleware.sessions.cookie_backend import CookieBackendConfig'" instead
```
The suggested import path does not exist and contains a typo.

**Comment by JacobCoffee** [comment]
Quick searches against the codebase show this also has that typo
https://github.com/starlite-api/starlite/blob/abc0ff41ac917afd8d8af718949de2ea935ca44c/starlite/app.py#L466

**Comment by peterschutt** [comment]
> Quick searches against the codebase show this also has that `startlite` typo
> 
> https://github.com/starlite-api/starlite/blob/abc0ff41ac917afd8d8af718949de2ea935ca44c/starlite/app.py#L466

This one looks like it only exists on the 2.x branch - there was another one in 1.x though - an easy typo to make!
