### ISSUE TITLE
Enhancement: Add a way to override default OpenAPI response descriptions

### ISSUE THREAD

**Issue by Nadock** [starlite-api/starlite#1292]
**What's the feature you'd like to ask for.**
Currently there is no way to replace the default OpenAPI description for HTTP 400 errors. For example, you currently can't do this:

```python
@starlite.post(
    "/path",
    responses={
        400: starlite.ResponseSpec(
            model=MyErrorModel, description="A more detailed error description"
        )
    },
)
async def login() -> starlite.Response:
    ...
```

If you do, you will get this error on startup:

```console
starlite.exceptions.http_exceptions.ImproperlyConfiguredException: 500: Additional response for status code 400 already exists in success or error responses
```

This makes it impossible to add more detailed error descriptions or properly document response shapes if you want your endpoint to return a different error shape.

**Additional context**
Removing this bit of code would allow the default HTTP 400 description to be replaced:
https://github.com/seladb/starlite/blob/51ae7eebda3e6834a6520471bfdb9cad2ab790c5/starlite/openapi/responses.py#L217-L220

**Comment by Goldziher** [comment]
Have you tried using the raises key?

**Comment by Nadock** [comment]
The raises key doesn't let you specify a model, just an exception type, so you can't specify any OpenAPI details.

**Comment by Nadock** [comment]
> Ok, i understand the issue.
> 
> Would you like to submit a PR?

Yeah can do, I'll get one up tonight.
