### ISSUE TITLE
Enhancement: `provide` decorator 

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#1305]
The idea is to add a new decorator `provide`. This decorator should decorate a route handler, and define a dependency. 

```python
def my_func(request: Request) -> str:
   ...

@provide("dep", my_func)
@get("/")
def handler(dep: str) -> str:
   ...
```

This should be equivalent to this:

```python
def my_func(request: Request) -> str:
   ...

@get("/", dependencies={"dep": Provide(my_func)})
def handler(dep: str) -> str:
   ...
```

Also- the decorator must ensure the proper order. This means the decorator MUST be applied after the route handler decorator (above it) or it will raise an exception. We could do stuff to go around this of course, but I'm not sure we should.

**Comment by provinzkraut** [comment]
Would be a nice addition. Shall we add that to the 2.0 track?

> We could do stuff to go around this of course, but I'm not sure we should.

Working around that is going to be messy with typing and IMO it makes more sense semantically to enforce the "correct" order so I'm on the side of "let's not do that".

**Comment by Goldziher** [comment]
> Shall we add that to the 2.0 track?

yhea lets do this

**Comment by wassafshahzad** [comment]
Is this available to pick up ?

**Comment by JacobCoffee** [comment]
@wassafshahzad yes I believe so, I can assign to you

**Comment by wassafshahzad** [comment]
> @wassafshahzad yes I believe so, I can assign to you

Thank you

**Comment by wassafshahzad** [comment]
@JacobCoffee @Goldziher, I have created the decorator however while running my local test I get the error "Improperly Configured". I do know why I get this, Since router.Register was passed an instance other then RouterHandler. However after RnD I could not figure out how to make the decorator work without changing the original check. Could you guide me a bit.

**Comment by Goldziher** [comment]
> @JacobCoffee @Goldziher, I have created the decorator however while running my local test I get the error "Improperly Configured". I do know why I get this, Since router.Register was passed an instance other then RouterHandler. However after RnD I could not figure out how to make the decorator work without changing the original check. Could you guide me a bit.

Without seeing code we can't help you

**Comment by provinzkraut** [comment]
Something like this was suggested on discord, and I think it would be a nice addition to have:


```python
class SomeController(Controller):
  @provide("foo")
  async def foo_dependency() -> str:
    ...

  @get("/")
  def handler(foo: str) -> str:
    ...
```

which would be equivalent to

```python
class SomeController(Controller):
  async def foo_dependency() -> str:
    ...

  @get("/", dependencies={"foo": Provide(foo_dependency)})
  def handler(foo: str) -> str:
    ...
```

just less noisy.

**Comment by wassafshahzad** [comment]
> @wassafshahzad - is there a PR incoming? if it wont be incoming in the very near future (2 days), let me know. 

Yes it is 
I will push changes tomorrow I think for you to take a look

Sorry I can only work on weekends

**Comment by wassafshahzad** [comment]
@Goldziher @JacobCoffee I have created a PR for you to take a look at with the code which is causing the above mentioned issues.

**Comment by provinzkraut** [comment]
Thinking about this some more, why don't we just allow

```python
def my_func(request: Request) -> str:
   ...

@get("/", dependencies={"dep": my_func})
def handler(dep: str) -> str:
   ...
```
?

That's just as explicit and doesn't require any additional logic. There's no need to wrap the callable in a `Provide` **before** it gets passed to the dependency map.

**Comment by peterschutt** [comment]
> That's just as explicit and doesn't require any additional logic. There's no need to wrap the callable in a Provide before it gets passed to the dependency map.

Great idea!

**Comment by Goldziher** [comment]
Provide offers also the option to cache the value etc., this is where a decorator can be helpful - provide accepts a few kwargs.

**Comment by provinzkraut** [comment]
Maybe I wasn't clear enough about this: I'm not suggesting removing the ability to pass in `Provide`. I'm merely suggesting that we also allow passing in callables directly.

**Comment by Goldziher** [comment]
thats fine, but we are writing here regarding a provide decorator. We can certainly support not wrapping in provide to give default behaviour, but lets split that into a different issue @provinzkraut

**Comment by wassafshahzad** [comment]
The issue I face with this code is the following `starlite.exceptions.http_exceptions.ImproperlyConfiguredException: 500: Unsupported value passed to **Router.register**. If you passed in a function or method, make sure to decorate it first with one of the routing decorators`
I could update the checks for improperly configured but I beleive there could be a better solution

**Comment by provinzkraut** [comment]
> thats fine, but we are writing here regarding a provide decorator. We can certainly support not wrapping in provide to give default behaviour, but lets split that into a different issue

As I said, I think that if we add the functionality I proposed, there's no need for this new `provide` decorator.

**Comment by wassafshahzad** [comment]
So, should I continue  ?

**Comment by Goldziher** [comment]
> > thats fine, but we are writing here regarding a provide decorator. We can certainly support not wrapping in provide to give default behaviour, but lets split that into a different issue
> 
> As I said, I think that if we add the functionality I proposed, there's no need for this new `provide` decorator.

Provide accepts `cache` as kwarg. 

The suggestion for the decorator was to make it cleaner to define DI. I'm not sure your suggestion replaces the idea of a decorator. 

@starlite-api/maintainers please chime in.

**Comment by provinzkraut** [comment]
> Provide accepts cache as kwarg.
>
> The suggestion for the decorator was to make it cleaner to define DI. I'm not sure your suggestion replaces the idea of a decorator.

I'm thinking more about the default case, which is to not use any of the additional parameters at all. The default case should be intuitive and the easiest to implement, and in any case there should be *one* clear way of doing things. If we add essentially two ways of achieving the same thing, with no difference but semantics, IMO this only makes things more complicated.

Adding to this, the `provide` decorator breaks with our other API paradigms, whereas my proposal would actually make dependencies more coherent with them. Think about `Parameter` and `Dependency`. They work on the principle that by default you can just say `x: thing`, and if you want to add additional info you do `x: thing = Parameter(...)` or `x: thing = Dependency(...)`.

**Comment by Goldziher** [comment]
Fair enough @provinzkraut , let's close this. 

@wassafshahzad thanks for your efforts

**Comment by wassafshahzad** [comment]
> Fair enough @provinzkraut , let's close this. 
> 
> @wassafshahzad thanks for your efforts 

No problem?
