### ISSUE TITLE
Enhancement: Return Tasks instead of coroutines from EventEmitter

### ISSUE THREAD

**Issue by chris-telemetry** [starlite-api/starlite#1307]
Currently `app.emit` returns a coroutine which must be awaited. This limits its usefulness for a websocket since a socket will effectively only be able to handle and respond to one message at a time. You can subclass the BaseEventEmitterBackend that returns Tasks like so:

```python

class CustomEventEmitter(BaseEventEmitterBackend):
    async def emit(self, event_id: str, *args: Any, **kwargs: Any) -> asyncio.Task | Tuple[asyncio.Task, ...]:
        """Emit an event to all attached listeners.

        :param event_id: The ID of the event to emit, e.g 'my_event'.
        :param args: args to pass to the listener(s).
        :param kwargs: kwargs to pass to the listener(s)
        :return: None
        """
        if listeners := self.listeners.get(event_id):
            if len(listeners) > 1:
                    return (asyncio.create_task(listener(*args, **kwargs)) for listener in listeners)
            else:
                return asyncio.create_task(listeners[0](*args, **kwargs))
        else:
            raise ImproperlyConfiguredException(f"no event listeners are registered for the event ID: {event_id}")

```

But this comes with its own problems since `app.emit` returns None and thus, the Tasks are liable to be garbage collected, cannot be cancelled, and cannot be awaited.

**Comment by Goldziher** [comment]
We could offer your emitter as an alternative builtin, which can be used by users. 

We also need to add documentation for this, which we haven't done Yet.

**Comment by chris-telemetry** [comment]
> We could offer your emitter as an alternative builtin, which can be used by users.

This would be great and I would be happy if you did that! But I don't want to get lost here -- the critical thing for this feature to have any value is to refactor `emit` in `app.py` and have it return the result of the emitter rather than `None`. Right now my Tasking solution wouldn't work since my Tasks would be liable to be garbage collected:

```python
async def emit(self, event_id: str, *args: Any, **kwargs: Any) -> None:
        """Emit an event to all attached listeners.

        :param event_id: The ID of the event to emit, e.g 'my_event'.
        :param args: args to pass to the listener(s).
        :param kwargs: kwargs to pass to the listener(s)
        :return: None
        """
        await self.event_emitter.emit(event_id, *args, **kwargs) # this needs to return something.
```

**Comment by chris-telemetry** [comment]
@provinzkraut 

>afaict you'd need to hold a reference to the tasks created on an object

Yeah so our typical pattern for socket-based handling is that we dispatch the events then keep the task reference which is then removed when the task itself fires it's "done" callback.

**Comment by provinzkraut** [comment]
> then keep the task reference

Where do you keep it though?
