### ISSUE TITLE
Dark docs theme is challenging to read

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#131]
.. at least for me.

![image](https://user-images.githubusercontent.com/20659309/172288722-4cee6933-d28b-4f13-b748-c69f23599bce.png)

The dark text on dark background is the issue.

It looks like this changed recently?

**Comment by Goldziher** [comment]
Perhaps due to the recent updates to mkdocs. Let's ask @dkress59 to assist with improving the docs.

**Comment by peterschutt** [comment]
Thanks @dkress59!

**Comment by peterschutt** [comment]
Whatever the cause, it was introduced in 1.3.9 with mkdocs-material bumped from 8.2.16 to 8.3..

Maybe we should pin to 8.2 for now?

**Comment by Goldziher** [comment]
Go for it

**Comment by dkress59** [comment]
sorry guys I'm in the middle of moving 📋 🚚 📦 📦

**Comment by Goldziher** [comment]
So, I reverted the pin - it didn't resole anything. We have an actual bug here I think, and we need an update to the CSS etc.

**Comment by peterschutt** [comment]
Hmm, ok. Definitely resolved it locally with `mkdocs build` but I don't know enough about mkdocs and the custom css to know if there was a difference between my local environment and the production one.

**Comment by Goldziher** [comment]
Well, maybe Im wrong. I repinned it and am deploying. Lemme know if its resolved -- i am myself color blind and cannot be trusted :)

**Comment by peterschutt** [comment]
Version pinned in `.github/workflows/docs.yml` as well as in `pyproject.toml`.

**Comment by dkress59** [comment]
> @dkress59 any update on this? We currently have to pin the mkdocs versions.

For me it's working now – I'll open a PR, please verify on your end @Goldziher

**Comment by Goldziher** [comment]
Fixed! thanks @dkress59
