### ISSUE TITLE
Bug: Returning a `starlite.Response` object in a route handler bypasses the after_request hook

### ISSUE THREAD

**Issue by iamrinshibuya** [starlite-api/starlite#1315]
**Describe the bug**
In the code that follows, `route_1` and `route_2` are very similar routes that respond with an `str`, the only difference being, `route_1` returns it directly as an `str` whereas `route_2` returns it as a `starlite.Response` object with the `str` in it. The `after_request` hook passed to `Starlite.after_request` is not being used for `route_2` the one that returns  `starlite.Response`

**To Reproduce**
```python
from starlite import Starlite, Response, get

def after_request(response: Response) -> Response:
    print("after request")
    response.headers["Custom-Header-Name"] = "Custom Header Value"
    return response

@get("/route_1")
def route_1() -> str:
    return "route_1"

@get("/route_2")
def route_2() -> Response:
    return Response("route_2", status_code=201)  # example 201 status in a GET Request 

app = Starlite([route_1, route_2], after_request=after_request)
```

**Additional context**
- A GET request to `/route_1` returns me the expected response body (`200 OK`), the output of `print` is seen in the log and I can see a custom header `"custom-header-name"` in my response

- A GET request to `/route_2` returns me the expected response body (`201 Created`), the output of `print` is NOT seen in the log and I can NOT see a custom header `"custom-header-name"` in my response

**Comment by peterschutt** [comment]
Confirmed. Thanks for opening @iamrinshibuya!

**Comment by Goldziher** [comment]
Will fix
