### ISSUE TITLE
Documentation: Add API documentation using Doctstring Annotations. 

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#132]
I really miss having API docs generally available.. this isn't just a starlite issue, but in general I notice that developer docs are more tailored to the beginner by being mostly prose and metaphor.

I actually agree with that though, ease of uptake is important, but that doesn't mean api docs can't be buried somewhere via some tiny obscure link at the bottom of the page somewhere.

https://github.com/mkdocstrings/mkdocstrings looks like it might be a good plugin to use.

**Comment by Goldziher** [comment]
Go ahead, I just got exhausted from writing docs 😀

**Comment by peterschutt** [comment]
Haha, I can totally understand that, and I hope my comment didn't come across as diminishing in any way to the work you've done!

@Goldziher do you have a preference for docstring style? I prefer the numpy style myself.

@dkress59 I'm only asking your opinion here as I see you were tagged into the other docs issue, so assume you are across the mkdocs setup? I've only used readthedocs and sphinx in the past. Do you have any opinion on this, or happy to let me run with it?

**Comment by Goldziher** [comment]
Not really, as long as the comment style is consistent I'm good.

**Comment by peterschutt** [comment]
Great, thanks.

**Comment by dkress59** [comment]
I'm not exactly sure what you question is but I'll try to answer 😄 
I've only ever used mkdocs and docsify, so I have no opinion of  sphinx or readthedocs.
I'm mostly responsible for the appearance of the starlite docs and I've always wanted to go over it once more to improve readability/ease-of-use: making paragraphs easier to skim by making keywords bold, introducing more paragraphs, splitting long pages into shorter sub-pages, plus maybe some re-arranging.
If you're asking to contribute to the docs – please go ahead! @Goldziher and me would both be happy to review your PR.

**Comment by peterschutt** [comment]
Thanks for your reply @dkress59.

This issue is specifically about adding api reference docs. I linked a tool that I would probably try to use if I was to undertake the task, and I was trying to see if you had some opinion as @Goldziher linked you into the other docs issue that I raised.

Sorry if I was unclear.

**Comment by dkress59** [comment]
yeah that mcdocstrings plugin looks awesome!

**Comment by peterschutt** [comment]
Yeah, out of all the plugins listed for autogen api docs in the mkdocs wiki, it seems to be the most supported/active.

There's another issue I'm working on that will have a bit of a docs component to it. I'll hopefully find my way alright but if I need any assistance would you mind if I ping you?

**Comment by dkress59** [comment]
wouldn't mind at all!

**Comment by Goldziher** [comment]
@peterschutt - can you do a write down of what required? lets see if other people would like to chip in on this one.

**Comment by 185504a9** [comment]
+1 for mkdocsstrings. i'm using it on a few projects and it works well, especially when following google's docstring style. pairing it with with something like [interrogate](https://interrogate.readthedocs.io/en/latest/index.html) can also be a plus

**Comment by peterschutt** [comment]
Yep I remember the logo!

**Comment by peterschutt** [comment]
> especially when following google's docstring style

OK I've been looking for a reason to prefer a docstring style - so if there's benefit to preferring google style for this do you mind if we make that a requirement for new contribs going forward @Goldziher?

**Comment by Goldziher** [comment]
> > especially when following google's docstring style
> 
> OK I've been looking for a reason to prefer a docstring style - so if there's benefit to preferring google style for this do you mind if we make that a requirement for new contribs going forward @Goldziher?

Not at all

**Comment by peterschutt** [comment]
The note doesn't render in the screenshot however it says:

> WIP: Building these API docs is an ongoing, community driven task and contributions are welcome. If you feel an interface is missing, feel free to comment in [this issue](https://github.com/starlite-api/starlite/issues/132).

I figure that it will be better to have the api docs included in `main`, yet incomplete, so that we don't have to constantly rebase and resolve conflicts as we would if we chose to keep all this isolated. Hence the note.

**Comment by peterschutt** [comment]
TODO:
- [ ] settle on the configuration
- [ ] set some baselines for doc string style in `CONTRIBUTING.md`, e.g., references to other public api members should be cross-referenced, e.g., ```[`Object 1`][full.path.object1]```
- [ ] detail all classes/functions that should be included in the public api docs
- [ ] detail members of each class that should be included in the public api for each class identified above
- [ ] break the work up and get stuck in

**Comment by 185504a9** [comment]
for full transparency and seeing that this is going pretty fast, i feel like i should mention that the the reason i said that it works best with google's style is bcuz i simply couldn't get it to work with other styles at the time, which was ~4 months ago; i don't know if that was my incompetence or a bug that is resolved now

about the layout choice, i think having multiple files, one for each class/namespace/file/whatever works best

**Comment by peterschutt** [comment]
I see that google style is the default for the framework, so that's good enough for me. If we run into any issues we can try some others.

> about the layout choice, i think having multiple files, one for each class/namespace/file/whatever works best

Agree.
