### ISSUE TITLE
Bug: Validation bug when using an aliased parameter as a dependency

### ISSUE THREAD

**Issue by abdulhaq-e** [starlite-api/starlite#1336]
**Describe the bug**

Using a query parameter (and maybe others) with an alias as a dependency requires both aliases to be provided

**To Reproduce**
Please see the commit I've made [here](https://github.com/abdulhaq-e/starlite/commit/6ccfba2fee901a1c6a729a3db77ea43c84130300), this will make the test fail

**Comment by Goldziher** [comment]
Hi, can you add a PR with a failing test case or paste a code snippet here we can make a test of?

**Comment by Goldziher** [comment]
There is no issue here, I think. You made a mistake:

```python
def test_query_param_dependency_with_alias() -> None:
    def qp_dependency(page_size: int = Parameter(query="pageSize", gt=0, le=100)) -> int:
        return page_size

    @get("/", media_type=MediaType.TEXT)
    def handler(page_size_dep: int) -> int:
       return page_size_dep

    with create_test_client(handler, dependencies={"page_size_dep": Provide(qp_dependency)}) as client:
        response = client.get("/?pageSize=1")
        assert response.status_code == HTTP_200_OK, response.text
        assert response.text == '1'
```

**Comment by Goldziher** [comment]
note the abov
