### ISSUE TITLE
Bug: SQLAlchemy 1 plugin mutates app state destructively

### ISSUE THREAD

**Issue by provinzkraut** [starlite-api/starlite#1368]
### Description

When using the SQLAlchemy 1 plugin, repeatedly running through the application lifecycle (as done when testing an application not provided by a factory function), causes a `KeyError` on the second pass.

This is caused be the plugin's `on_shutdown` handler deleting the `engine_app_state_key` from the application's state on application shutdown, but only *adding* it on application init.

This can be solved by setting up the application state within `on_startup`.

### MCVE

```python
from starlite.contrib.sqlalchemy_1.config import SQLAlchemyConfig
from starlite.contrib.sqlalchemy_1.plugin import SQLAlchemyPlugin
from starlite import Starlite
from starlite.testing import TestClient

app = Starlite(
    plugins=[
        SQLAlchemyPlugin(
            config=SQLAlchemyConfig(
                connection_string="sqlite+pysqlite:///:memory:",
                use_async_engine=False,
            )
        )
    ]
)


with TestClient(app) as client:
    pass


with TestClient(app) as client:
    pass
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Starlite Version

This affects both 1.51 and the main branch.

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by peterschutt** [comment]
Can confirm.

We have this patch in `starlite-pg-redis-docker`:

```py
@pytest.fixture(scope="session", autouse=True)
def _patch_sqlalchemy_plugin() -> "abc.Iterator":
    monkeypatch = pytest.MonkeyPatch()
    monkeypatch.setattr(
        sqlalchemy_plugin.SQLAlchemyConfig,  # type:ignore[attr-defined]
        "on_shutdown",
        MagicMock(),
    )
    yield
    monkeypatch.undo()
```
Adding an `on_startup` handler feels like the correct way to handle. Good idea!
