### ISSUE TITLE
Bug: msgspec version needs updating

### ISSUE THREAD

**Issue by ste-pool** [starlite-api/starlite#1369]
### Description

Starlite currently needs msgspec >= 0.11.0 from here https://github.com/starlite-api/starlite/blob/8a49aff754d5b409397183eb395cac5a44193d72/pyproject.toml#L52.

Starlite uses msgspec.inspect:
https://github.com/starlite-api/starlite/blob/41089a2d5dff696a25c78a58322d3a8a08ebcac3/starlite/constants.py#L3

msgspec.inspect wasn't introduced in msgspec until 0.12.0:
https://github.com/jcrist/msgspec/releases/tag/0.12.0

### Steps to reproduce

```bash
1. In a new environment, pip install starlite msgspec==0.11.0
2. Try to import starlite
```

### Starlite Version

1.51.7

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by jcrist** [comment]
AFAIK starlite isn't actually making use of `msgspec.inspect.UNSET` in any way (I think this was a holdover from older msgspec integration work that was never completed). In the near future `msgspec.inspect.UNSET` will be going away; a better fix (if valid) may be just to delete this bit of code from starlite.

**Comment by ste-pool** [comment]
```UNDEFINED_SENTINELS = {Undefined, Signature.empty, UNSET, Empty, Ellipsis}```
It's used there? Happy to remove UNSET from there, drop the import and keep the version but I don't know the implications of that

**Comment by Goldziher** [comment]
you can remove this, yes, and there is no problem with increasing the version as well. Just use "*" to let poetry determine this.

**Comment by ste-pool** [comment]
Okay, updated. Thanks 😄
