### ISSUE TITLE
Bug: Openapi schema generation crashes for models with `Annotated` type attribute

### ISSUE THREAD

**Issue by NomAnor** [starlite-api/starlite#1372]
### Summary

I have a pydantic model that uses a list of [discriminated unions](https://docs.pydantic.dev/usage/types/#nested-discriminated-unions). Because of the list I need to annotate the union with the discriminator. But then the schema generation throws an error that it can't map the type.

### Basic Example

```python
class Base(BaseModel):
    pass

class A(Base):
    type: Literal["a"] = "a"

class B(Base):
    type: Literal["b"] = "b"

MyUnion = Annotated[Union[A, B], Field(discriminator="type")]

class Test(BaseModel):
  entries: List[MyUnion] = []
```
If you now use ``Test`` as a parameter in a handler function and open for example the swagger documentation you get an error like

> 500: Parameter '' with type 'typing.Annotated[typing.Union[A, B], FieldInfo(default=PydanticUndefined, discriminator='type', extra={})]' could not be mapped to an Open API type. This can occur if a user-defined generic type is resolved as a parameter. If '' should not be documented as a parameter, annotate it using the `Dependency` function, e.g., `: ... = Dependency(...)`.

**Comment by peterschutt** [comment]
Hey, I tried to reproduce, can you look at this and tell me what to change to get it to fail please?

```py
"""Minimal Starlite application."""
from __future__ import annotations

from typing import Annotated, Any, List, Literal, Union

from pydantic import BaseModel, Field
from starlite import Starlite, get


class Base(BaseModel):
    """A base model."""


class Foo(Base):
    """A Foo model."""

    type: Literal["foo"] = "foo"


class Bar(Base):
    """A Bar model."""

    type: Literal["bar"] = "bar"


AnnotatedUnion = Annotated[Union[Foo, Bar], Field(discriminator="type")]


class Test(BaseModel):
    """A Test model."""

    entries: List[AnnotatedUnion] = []


@get("/")
def hello_world(test: Test) -> dict[str, Any]:
    """Route Handler that outputs hello world."""
    return {"hello": "world"}


app = Starlite(route_handlers=[hello_world])
```

On starlite 1.51, python 3.11, I get:

![image](https://user-images.githubusercontent.com/20659309/228086908-2c5186af-387d-4191-9aa5-39adc1d98550.png)

from `/schema/swagger`

**Comment by NomAnor** [comment]
When I comment out ``from __future__ import annotations``, I get the error.

I'm running ``Python 3.10.9`` on top of the ``main`` (commit 23b84b67dd20d2836caf8e3b54797b2d15f42e7e) branch.

I seems that import is still needed in 3.10. Is starlite intentionally using the new behaviour? 
Grepping through the code it is used alot, but I can't find any mention of it in the documentation.

The future import is very easy to miss. Is it possible to fix this when the user code does not do the import?

**Comment by peterschutt** [comment]
Oh - you're on main, OK that changes things. There were some pretty big changes to openapi internals for v2 which are in main and not in 1.51.

I have reproduced, thanks for the extra info.

> The future import is very easy to miss. Is it possible to fix this when the user code does not do the import?

It should work either way - I just use it without thinking.

**Comment by peterschutt** [comment]
@NomAnor - PR up for this, which boiled down to "data" models with an annotated attribute value not having that annotated type unwrapped before the schema was being generated for the attribute.

The reason that the issue occurred without `__future__.annotations` and not with, is because when `__future__.annotations` were invoked, we pass that annotation through to `typing_extensions.get_type_hints()` which was unwrapping those for us. That inconsistency is not ideal, so will address that in another PR.

@hadware - v1 signature parsing with forward-referenced annotations is flaky at best - but if as you say it was working before this is worthy of its own tracking issue. While the outcome might seem similar to the OP, there is a difference as OPs issue originated out of us recursing into the data model to produce a schema for its attributes. Also, OPs issue is specifically on `main` branch while yours is on the `v1.51` branch.

**Comment by hadware** [comment]
Alright, i'm back: on starlite 2.0.0alpha2, I tried running 
```
starlite schema typescript
```
And i got the `starlite.exceptions.http_exceptions.ImproperlyConfiguredException: 500: Parameter '' with type ... could not be mapped to an Open API type. ....` error again (even though the starlite app can run perfectly fine). I'm mentioning it to make sure that your fix also works with the CLI.

**Comment by Goldziher** [comment]
Can you give a minimum reproduction?

**Comment by hadware** [comment]
Ok, I found out that it was because i had forgotten to put `from __future__ import annotations` in some file.

However, I still have some issues:

Let's take this example:

```python
"""Minimal Starlite application."""
from typing import Annotated, Literal

import uvicorn
from pydantic import BaseModel, Field
from starlite import Starlite, get


class Base(BaseModel):
    """A base model."""


class Foo(Base):
    """A Foo model."""

    type: Literal["foo"] = "foo"
    a: int


class Bar(Base):
    """A Bar model."""

    type: Literal["bar"] = "bar"
    b: float


AnnotatedUnion = Annotated[Foo | Bar, Field(discriminator="type")]


@get("/")
def hello_world(test: AnnotatedUnion, var: int) -> str:
    """Route Handler that outputs hello world."""
    return "hello"


app = Starlite(route_handlers=[hello_world])

if __name__ == '__main__':
    uvicorn.run("fake_app:app", reload=True)
```

Running `starlite --app fake_app:app schema typescript` will produce the following error:

```
ValueError: cannot specify `Annotated` and value `Field`s together for 'test'
```

However, if I add the infamous `from __future__ import annotations` at the beginning of the file, running the same command will output:

```
TypeError: received an unexpected openapi type: None
```

Something that I noticed: when I run `fake_app.py` and reach for the swagger/redoc webpage, all the Schema (here, `Foo` and `Bar`) have the right fields, but their types are all `any` instead of the right type.

**Comment by peterschutt** [comment]
Thanks for providing more info @hadware 

> Ok, I found out that it was because i had forgotten to put from __future__ import annotations in some file.

Which file? You should not need to include this directive for anything to work properly.

> TypeError: received an unexpected openapi type: None

I'm working on this right now, as I came across it while trying to reproduce your error from [here](https://github.com/starlite-api/starlite/issues/1372#issuecomment-1488973157). I believe this is an issue with the openapi generator not using the return annotation that we have resolved from forward references, and instead using the return annotation from `inspect(handler).signature.return_annotation` which is a string if `__future__.annotations` is invoked. My in-browser testing is working, but unfortunately it broke a lot of tests.

> ValueError: cannot specify `Annotated` and value `Field`s together for 'test'

This, I have no idea. It only happens with the typescript generator, i.e., nothing runtime?

> Something that I noticed: when I run fake_app.py and reach for the swagger/redoc webpage, all the schemas (here, Foo and Bar) have the right fields, but their types are all any instead of the right type.

I'd say this is a different issue but won't be sure until all this other stuff is resolved. Feel free to open a separate issue to track it.

**Comment by peterschutt** [comment]
Tracking the issue with the return annotation here: https://github.com/starlite-api/starlite/issues/1409

**Comment by hadware** [comment]
> Thanks for providing more info @hadware
> 
> > Ok, I found out that it was because i had forgotten to put from **future** import annotations in some file.
> 
> Which file? You should not need to include this directive for anything to work properly.
> 

Well, i'd need to test that out, but for it to work i needed to put it in some of the files that contain `Controller` classes. Note that:
- if i don't use `from __future__ import annotations` at all, I get the `ValueError: cannot specify Annotated and value Fields together for 'test'` error *at app startup time*
- if i fail to use it on _some_ files, I get the `starlite.exceptions.http_exceptions.ImproperlyConfiguredException: 500: Parameter '' with type 'typing.Annotated[...]' could not be mapped to an Open API type. ....` when accessing any of the /schema/ pages.


> 
> > ValueError: cannot specify `Annotated` and value `Field`s together for 'test'
> 
> This, I have no idea. It only happens with the typescript generator, i.e., nothing runtime?
> 

As per previous answer, I get also get it at app startup time, without using the typescript schema command. I wish I could pinpoint the error to something more precise, but my app's code is already quite lengthy, and the error isn't super helpful. I'll try building a minimal example by investigating with the dbg.

Also, noted regarding the error in the documentations. I'll make another issue for this.

**Comment by peterschutt** [comment]
No worries, if you can get an MCVE going for any of these things, please open a new issue report.
