### ISSUE TITLE
Docs: 1.x Changelog gives 404 not found

### ISSUE THREAD

**Issue by zoni** [starlite-api/starlite#1383]
### Summary

In the navigation menu at the top of the page on https://docs.starliteproject.dev/latest/ and https://docs.starliteproject.dev/1/, there's a section _"Release notes"_ with a link to [1.x Changelog](https://docs.starliteproject.dev/1/release-notes-changelog.html). 

This link errors with a 404 page not found error from GitHub pages.

Notably, the docs for the upcoming 2.x at https://docs.starliteproject.dev/2/ do have a valid link to this changelog, which also works for the latest/v1 docs set: https://docs.starliteproject.dev/1/release-notes/changelog.html

**Comment by provinzkraut** [comment]
Thanks for the report! It should be fixed now.
