### ISSUE TITLE
Docs: Startup and Shutdown mermaid chart not rendering

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#1390]
### Summary

![image](https://user-images.githubusercontent.com/20659309/227752905-dc1dedef-9570-4bba-9f8d-dc20cf4f1256.png)

**Comment by peterschutt** [comment]
This issue exists on the deployed latest version, not on deployed dev or 2, and doesn't reproduce locally on 1.51 branch..

**Comment by provinzkraut** [comment]
Hm.

> The resource from “https://unpkg.com/mermaid@10.0.2/dist/mermaid.min.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff)

**Comment by provinzkraut** [comment]
For some reason, the 1/latest uses `mermaid@10.0.2`, while 2/dev use `mermaid@9.4.0`

**Comment by peterschutt** [comment]
Oh ok, wonder if the syntax changed or smth b/w 9 & 10?

**Comment by peterschutt** [comment]
Oh ha, that'll do it - thanks - I intended to have a closer look at this but got sidetracked.

**Comment by provinzkraut** [comment]
I pushed a fix to the v1.51 branch and the new pages deployment should build as we speak.
