### ISSUE TITLE
`Provide` and `@classmethod`

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#142]
`Provide(Something.new)` where `new()` is an `@classmethod` doesn't work.

repro:

```python-console
asyncio REPL 3.10.2 (main, Jan 26 2022, 20:19:57) [GCC 10.2.1 20210110] on linux
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> from app.domain.providers.entities.service import Service
>>> Service.new
<bound method Service.new of <class 'app.domain.providers.entities.service.Service'>>
>>> await Service.new()
3
>>> from starlite import Provide
>>> await Provide(Service.new).dependency()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
TypeError: Service.new() takes 1 positional argument but 2 were given
```

Stems from here:
https://github.com/starlite-api/starlite/blob/4c411b4e260c1db0d1e8f9beba3e888e7f1e7a89/starlite/provide.py#L22-L24

I think the current pattern is to prevent the callable becoming an instance method of the `Provide` instance, which perhaps would be better done with `self.dependency = staticmethod(dependency)`... but I haven't tested it or anything yet.

**Comment by Goldziher** [comment]
Well, the issue is that if self is used inside the method, making it static will break the code. This is why this is in place. But there is a test for it - 

```python
def test_provide_method() -> None:
    class MyClass:
        def my_method(self) -> None:
            assert self.__class__ is MyClass

    provider = Provide(dependency=MyClass().my_method)
    assert isinstance(provider.dependency, partial)
    assert isinstance(provider.dependency.args[0], MyClass)
```

The issue above seems to be you are using a static method, which is still being forwarded `self`. So the bug here is that static methods are not handled correctly by provide. Am I correct?

**Comment by peterschutt** [comment]
> The issue above seems to be you are using a static method, which is still being forwarded self. So the bug here is that static methods are not handled correctly by provide. Am I correct?

In my case, `Service.new` is a `@classmethod`.

At least in 3.10, assigning an instance method to another class instance doesn't seem to overwrite `self`:

```python-console
>>> class C1:
...   def method_1(self):
...     return self.__class__
... 
>>> c1 = C1()
>>> c1.method_1()
<class '__main__.C1'>
>>> class C2:
...   def __init__(self, fn):
...     self.fn = fn
... 
>>> c2 = C2(c1.method_1)
>>> c2
<__main__.C2 object at 0x7fe05e95a260>
>>> c2.fn
<bound method C1.method_1 of <__main__.C1 object at 0x7fe05eb1bd30>>
>>> c2.fn()
<class '__main__.C1'>
```
`staticmethod` doesn't seem to change the behavior so is probably unnecessary and a red herring:

```python-console
>>> class C3:
...   def __init__(self, fn):
...     self.fn = staticmethod(fn)
... 
>>> C3(c1.method_1).fn()
<class '__main__.C1'>
```

I think I'll do up a test for each type of callable that could conceivably be passed to `Provide` and go from there. Anything you'd add to these?
- sync and async `@classmethod`
- sync and async instance methods
- sync and async regular functions
- sync and async `partial` objects
- sync and async objects with `__call__()` defined.

**Comment by Goldziher** [comment]
I'd add static methods.

**Comment by peterschutt** [comment]
I've got https://github.com/starlite-api/starlite/tree/issue-142-provide with a refactor of the `test_provider.py` module and a fix.

So far, the fix is just removing the lines where we maybe convert the callable to a `partial`.

@Goldziher if you can remember some specifics of a case that required that logic I'll add a test for it and solve it, but for now I've got all of those callable types listed above, including statics going through `Provide` and returning correct values. Please check the tests and be happy that I'm not missing anything.

**Comment by Goldziher** [comment]
Reviewed
