### ISSUE TITLE
pydantic-factories testing examples

### ISSUE THREAD

**Issue by vrslev** [starlite-api/starlite#143]
Testing page in docs has a tip that `pydantic-factories` package is bundled with Starlite. The problem is that there’s no example why it is useful. As I can see Starlite uses the package mostly for generating OpenAPI examples. I think we should either don’t mention `pydantic-factories` on testing page or add an example how to use it.

**Comment by Goldziher** [comment]
Well, I am all for adding some examples 😉 .

Wanna give it a go?

**Comment by vrslev** [comment]
Sure!
