### ISSUE TITLE
middleware help

### ISSUE THREAD

**Issue by mybigman** [starlite-api/starlite#153]
How do I achieve the same result as per below using starlites `MiddlewareProtocol` ?

The documentation doesn't provide enough information how to go about it, well for me atleast :/

```python
class CustomHeaderMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        start_time = time.time()
        response = await call_next(request)
        process_time = time.time() - start_time
        response.headers["X-Process-Time"] = str(process_time)

        return response
```

```python
class CustomHeaderMiddleware2(MiddlewareProtocol):
    def __init__(self, app: ASGIApp):
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] == "http":
            request = Request(scope)
        await self.app(scope, receive, send)
```

**Comment by mybigman** [comment]
I have come up with this, not sure if its the right way to go about it.

Is one method preferred over the other, if so why?

```python
class CustomHeaderMiddleware2(MiddlewareProtocol):
    def __init__(self, app: ASGIApp):
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] == "http":
            start_time = time.time()

            async def send_wrapper(message: Message) -> None:
                if message["type"] == "http.response.start":
                    process_time = time.time() - start_time
                    headers = MutableHeaders(scope=message)
                    headers.append("X-Process-Time-2", str(process_time))
                await send(message)

        await self.app(scope, receive, send_wrapper)
```

**Comment by peterschutt** [comment]
> Is one method preferred over the other, if so why?

What is the other method you are referring to?

If that works for what you want to do then I'd say roll with it until you hit a problem. When you have a concrete problem, put in an issue.

For general usage advice and discussion, the discord server is a good place to get help, we are all on there too.

**Comment by vrslev** [comment]
From the docs:
> Starlite builds on top of the [Starlette middleware architecture](https://www.starlette.io/middleware/) and is 100% compatible with it - and any 3rd party middlewares created for it.

Personally, I’d choose Starlette’s BaseHTTPMiddleware, it looks much cleaner and is higher level.

**Comment by mybigman** [comment]
@vrslev thanks mate, agreed

**Comment by peterschutt** [comment]
@mybigman should we be updating our docs here?

**Comment by peterschutt** [comment]
> and is higher level.

Starlette's  middleware doesn't really operate at a higher level than any other middleware does it? Looks to me like starlite just supports it in line with any other middleware:

```python
        for middleware in reversed(user_middleware):
            if isinstance(middleware, Middleware):
                current_app = middleware.cls(app=current_app, **middleware.options)
            else:
                current_app = middleware(app=current_app)
```

**Comment by mybigman** [comment]
> @mybigman should we be updating our docs here?

@peterschutt  I think it would be a good idea to have a bit more details on how you go about modifying the request and response would greatly help especially using `MiddlewareProtocol`

**Comment by peterschutt** [comment]
Yeh, I agree. The existing example demonstrates accessing the incoming request data, but nothing about modifying the response.

So we should include an example of the canonical way to modify a response object using the `MiddlewareProtocol` pattern.

@Goldziher is there a more concise way to add response headers on the fly via middleware than this:

```python

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] == "http":
            start_time = time.time()

            async def send_wrapper(message: Message) -> None:
                if message["type"] == "http.response.start":
                    process_time = time.time() - start_time
                    headers = MutableHeaders(scope=message)
                    headers.append("X-Process-Time-2", str(process_time))
                await send(message)

        await self.app(scope, receive, send_wrapper)
```

**Comment by Goldziher** [comment]
> Yeh, I agree. The existing example demonstrates accessing the incoming request data, but nothing about modifying the response.
> 
> So we should include an example of the canonical way to modify a response object using the `MiddlewareProtocol` pattern.
> 
> @Goldziher is there a more concise way to add response headers on the fly via middleware than this:
> 
> ```python
> 
>     async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
>         if scope["type"] == "http":
>             start_time = time.time()
> 
>             async def send_wrapper(message: Message) -> None:
>                 if message["type"] == "http.response.start":
>                     process_time = time.time() - start_time
>                     headers = MutableHeaders(scope=message)
>                     headers.append("X-Process-Time-2", str(process_time))
>                 await send(message)
> 
>         await self.app(scope, receive, send_wrapper)
> ```

Not via middleware. You can use the 'after_request` hook for this, it's perfect for this use case.

**Comment by peterschutt** [comment]
I'd say _almost_ perfect, and I was going to make the same suggestion. I think the fact that `after_request` is overridden by a definition that is closer to the handler makes the approach less than perfect.

Say we decide to put an `after_request` hook at the app level that injects a header value that must exist for all requests. That means that any time we want to use the before/after hooks for a router, controller or handler, we have to remember to include logic to inject the header. With the middleware approach that isn't a problem.

**Comment by Goldziher** [comment]
> I'd say _almost_ perfect, and I was going to make the same suggestion. I think the fact that `after_request` is overridden by a definition that is closer to the handler makes the approach less than perfect.
> 
> Say we decide to put an `after_request` hook at the app level that injects a header value that must exist for all requests. That means that any time we want to use the before/after hooks for a router, controller or handler, we have to remember to include logic to inject the header. With the middleware approach that isn't a problem.

Sure, you can use middleware as well. I would simply use a higher order function to set after_request handlers.

**Comment by peterschutt** [comment]
For sure, higher order function is a good shout in that case. 

I wonder how common it is that users will want to modify the response object via middleware such as in this case, and weather it is worth thinking about providing a cleaner api to do so. It's not something I do at all.

To start with, I'll include the `send_wrapper()` example from above in the docs and say "here's how you can access the response object via middleware", and we can just see what people ask for after that.

**Comment by peterschutt** [comment]
@mybigman I've included your example of accessing the response in the docs - hope that's ok. Thanks for starting the discussion. If you have any thoughts about what a nice api might look like for this sort of thing, feel free to weigh in.
