### ISSUE TITLE
passing validation error to frontend

### ISSUE THREAD

**Issue by mybigman** [starlite-api/starlite#159]
Similar to previous issue [#102](https://github.com/starlite-api/starlite/issues/102)

It never reaches the "VALIDATION FAILED" as its catching the validation error and returning a JSON response.

How can I pass it through?

```python
class User(BaseModel):
    username: str
    password: str

class LoginController(Controller):
    path = ""

    @get(path="/login")
    async def login(self) -> Template:
        return Template(name="login.html")

    @post(path="/login")
    async def post_login(
        self,
        data: User = Body(media_type=RequestEncodingType.URL_ENCODED),
    ) -> None:
        if "VALIDATION FAILED":
            return Template(name="login.html", context="VALIDATION ERRORS")

        response = RedirectResponse(url=f"/profile", status_code=303)
        response.set_cookie("MY_COOKIE", "1")

        return response
```

**Comment by Goldziher** [comment]
This isn't the same issue as #102, the issue there was the json serialization. 

Anyhow, validation errors do not reach the view, they bubble upwards. 

You can register an exception handler that returns your html.

**Comment by Goldziher** [comment]
This isn't the same issue as #102, the issue there was the json serialization. 

Anyhow, validation errors do not reach the view, they bubble upwards. 

You can register an exception handler that returns your html. 

Please try that and let us know what's the experience. 

We might consider allowing users to register exception handlers per route handler, controller or router, thoughts? @peterschutt

**Comment by mybigman** [comment]
> You can register an exception handler that returns your html.
> 
> Please try that and let us know what's the experience.

I did look at that though however thats only going to create a generic APP level exception which is not what I want?

```python
def custom_exception(_: Request, exc: Exception) -> Response:
    status_code = HTTP_400_BAD_REQUEST
    detail = ""

    if hasattr(exc, "detail"):
        detail = exc.detail

    if hasattr(exc, "status_code"):
        status_code = exc.status_code

    return Response(
        media_type=MediaType.HTML,
        content=detail,
        status_code=status_code,
    )

...
exception_handlers={ValidationException: custom_exception}
```

**Comment by peterschutt** [comment]
I'm all for as many configs as possible being available to every layer of the application. In this case, if the exception handler could be specified at levels below the app it would allow for greater control over responses, so +1 for that. I think it makes sense whether of not it evolves to become the canonical way to override the 400 response.

**Comment by Goldziher** [comment]
@mybigman its far from idyll, but you can inspect the url for the request and handle the logic this way. I will make a PR with an update for route handler level exception handling.
