### ISSUE TITLE
OpenAPI schema generation includes `status_code` but default exception handler never outputs that attribute

### ISSUE THREAD

**Issue by timwedde** [starlite-api/starlite#167]
I was doing some endpoint schema validation for my project and ran into what seems like an inconsistency between the generated OpenAPI schema and reality.

Specifically, `HTTPException` has an (optional) `status_code` attribute which is typically set to the response status code when something exceptional happens.
The fact that this field should always be present in the output is documented in the generated schema, but in the code it is omitted in all cases in the default exception handler:
```py
if isinstance(exc, HTTPException):
    content = {"detail": exc.detail, "extra": exc.extra}
```

This currently makes my tests fail because the schema says status_code is required, but starlite will never output it.

There are two possible fixes for this:
1. Fix the OpenAPI schema generator not to include the field as required (or at all)
2. Update the default exception handler to include the field when it exists

**Comment by Goldziher** [comment]
So, whats your suggestion for a fix?

**Comment by timwedde** [comment]
Personally I would go with option 2 because:
- The status codes are already tracked and it's documented in all schemas that Starlite has generated up until now, so this would break the "API" less in the sense that the OpenAPI schema just becomes more truthful instead of changing.
- The status code is always given in `HTTPException` (500 by default) so we can simply add the field in the default exception handler and fix this very easily. It will be 500 when not otherwise specified and if it *is* specified, it'll be whatever the developer put in, which is expected behavior based on the rest of Starlite.

**Comment by timwedde** [comment]
Actually, I think I found another (albeit minor) inconsistency:
The `extra` attribute can be `None`/`null`, but the generated schema ends up as requiring at least an empty dict `{}`. This means that if you try to validate the endpoint's conformance against the generated schema, it will fail for all cases where `extra` is not given, as `None` is technically not an allowed value at the moment.

**Comment by Goldziher** [comment]
Go ahead and handle them together

**Comment by timwedde** [comment]
There's two options in this case as well:
1. Since `extra` is in fact marked as optional, completely exclude the key from the response dict when it's empty.
2. Coerce an empty `extra` key to an empty dict.

I'd personally go with 1.) as it's more true to what the schema already specifies (an optional key should not exist if it's just empty).

What's your preference here?

**Comment by Goldziher** [comment]
> There's two options in this case as well:
> 1. Since `extra` is in fact marked as optional, completely exclude the key from the response dict when it's empty.
> 2. Coerce an empty `extra` key to an empty dict.
> 
> I'd personally go with 1.) as it's more true to what the schema already specifies (an optional key should not exist if it's just empty).
> 
> What's your preference here?
> 
> Edit: Just noticed that `extra` may be either a dict *or* a list. How would this be typed in the OpenAPI schema?
> I managed to come up with this, which seems to work:
> ```py
> extra=Schema(type=[OpenAPIType.OBJECT, OpenAPIType.ARRAY]),
> ```
> 
> This way extra can be optional and if it's given, it can be a dict or a list.

The extra key is present, there is no option 1. But it can be None, which means it's nullable.

**Comment by timwedde** [comment]
How would one mark a nullable key in OpenAPI in that case?
We can mark it as one of several types, but I have not yet found a way to denote it as nullable versus "not required" (it's already marked as the latter). If we mark it as not-required and then supply a null value, that is technically not within the schema spec.

**Comment by Goldziher** [comment]
OpenAPIType.NULL

**Comment by timwedde** [comment]
Heh, serves me right for looking at that enum and immediately forgetting what it contained, heh.
I've added the updated type declaration to #168, let me know if that's a workable solution.

**Comment by timwedde** [comment]
Alright, will do this evening.
