### ISSUE TITLE
template additional config

### ISSUE THREAD

**Issue by mybigman** [starlite-api/starlite#170]
How can this be achieved with the current way the template config is used?

```python
templates = Jinja2Templates(directory="templates")
templates.env.globals[’flashed_messages’] = flashed_messages
```

**Comment by peterschutt** [comment]
I cannot see an obvious way, nor any mention of setting globals in the docs, so hopefully I haven't missed anything.

The jinja `Environment` is constructed in `starlite.template.jinja.JinjaTemplateEngine`:

```python
class JinjaTemplateEngine(TemplateEngineProtocol[JinjaTemplate]):
    """Template engine using the jinja templating library"""

    def __init__(self, directory: Union[DirectoryPath, List[DirectoryPath]]) -> None:
        super().__init__(directory)
        loader = FileSystemLoader(searchpath=directory)
        self.engine = Environment(loader=loader, autoescape=True)
```
According to [jinja docs](https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.Environment.globals) that `Environment` object has a `globals` attribute which is a dict for storing those variables in.

So maybe we could do something like:

```python
templates = TemplateConfig(
    directory="templates", engine=JinjaTemplateEngine, globals={"flashed_messages": flashed_messages}
)
```

**Comment by mybigman** [comment]
@peterschutt are you saying that you can implement into the code base or it should already work?

I have tried that but errors with `UndefinedError: 'flashed_messages' is undefined` when trying to call it in the template.

**Comment by peterschutt** [comment]
That is a suggestion of a potential api design to solve the problem you have, it would need to be implemented.

**Comment by Goldziher** [comment]
+1

**Comment by peterschutt** [comment]
@mybigman are you happy enough that you can do what you want to do with the solution in #172?

**Comment by mybigman** [comment]
@peterschutt looks like it should do the trick.

I came across this yesterday, does it also cover the ability to do -

[jinja partials](https://github.com/mikeckennedy/jinja_partials)
```python
from starlette.templating import Jinja2Templates

import jinja_partials

templates = Jinja2Templates("tests/test_templates")

jinja_partials.register_starlette_extensions(templates)
```

**Comment by peterschutt** [comment]
Yeh I think that would work easy enough, as you can just work with the `Environment` that is passed back to you.

```python
from jinja_partials import generate_render_partial

def engine_callback(templates: JinjaTemplateEngine) -> JinjaTemplateEngine:

    def renderer(template_name: str, **data: Any) -> str:
        return templates.get_template(template_name).render(**data)

    templates.engine.globals.update(render_partial=generate_render_partial(renderer))

template_config = TemplateConfig(
    directory="templates", engine=JinjaTemplateEngine, engine_callback=engine_callback
)
```
Haven't tested though, let me know if it doesn't work for you.

**Comment by mybigman** [comment]
@peterschutt just tested and it appears all is working.

thanks mate

**Comment by peterschutt** [comment]
No probs. I'd not come across that lib before, but seems pretty neat. Random fact: it belongs to the guy that does the "Talk Python to Me" podcast.

**Comment by mybigman** [comment]
yeh likewise... as mentioned only come across the other day and thought the same pretty clever.
