### ISSUE TITLE
Bug: exception representation swallows errors

### ISSUE THREAD

**Issue by Bobronium** [starlite-api/starlite#188]
From https://github.com/starlite-api/starlite/pull/174#issuecomment-1166689792:

> Also a shame that pytest seems to be stripping out the error message pointing to the extra install requirement.

Turns out, It's not pytest, it's actually starlite :)

`StarLiteException` eats exception args, doesn't pass them to `Exception` and doesn't define custom `__str__` 
While `__repr__` is defined, that not what python uses to display errors.

My proposal: ditch custom `__repr__` altogether and rely on `Exception.args`.
And make `detail` a property of `args` joined together (which is actually just `Exception.__str__`)

**Comment by Goldziher** [comment]
Go ahead

**Comment by Goldziher** [comment]
Another thing we need to take care when doing this is to support headers being passed to exception, as is done in `starlette.exceptions.HTTPException`.

@Bobronium will you be taking over this issue?

**Comment by Bobronium** [comment]
@peterschutt, yep, I'm working on it. Though it may take a couple of days or even weeks, since I'm a bit more busy with life :)

I'm fighting with backwards/cross compatibility with `starlette` at the moment.

**Comment by Bobronium** [comment]
Ok, so I've been working on this for couple of days, but struggling to continue.

If anyone wants to pick up on this, please let me know. 

I'm still committed to do this, but don't want to stop anyone who's able to do it quicker than me. If no one will pick this up, there's a great chance I will do it some time later.

**Comment by Goldziher** [comment]
Ok, thanks for your efforts @Bobronium
