### ISSUE TITLE
Code quality: more functional approach

### ISSUE THREAD

**Issue by vrslev** [starlite-api/starlite#191]
I'm excited about functional programming. I think it makes code more clean and self-explanatory, especially when it is split into small functions. Starlite has code that is much better and clean that you can see in other ambitious projects. Still, it has a lot of quite big functions. They are hard to test in isolation and potentially can lead to bugs.
What do you think about taking more of FP approach? Writing more pure functions, avoiding object oriented design when possible, keep classes small and easy to understand.
Since Starlite is thoroughly tested, we can be confident that nothing important will break on refactor. Of course, since it is my initiative, I will take part in the refactoring process.

**Comment by Goldziher** [comment]
Go ahead. Please go small so I can review PRs granularly. Also, testing is good, but it should be increased if you want to do unit testing.

**Comment by vrslev** [comment]
I’m struggling with big project that should be done first. I added it in my action list and will make first steps in couple of weeks or months (programming is currently just a hobby for me, so I do it in my spare time)

**Comment by Goldziher** [comment]
>  I’m struggling with big project that should be done first. I added it in my action list and will make first steps in couple of weeks or months (programming is currently just a hobby for me, so I do it in my spare time)

Ok. So I will close this issue for now. Reopen if when you want to do the work.
