### ISSUE TITLE
Add GZIP support

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#192]
Starlette offers a gzip middleware, we should support it like we support CORS and AllowedHosts, namely with a config and then set it on the app level.

**Comment by MrAwesomeRocks** [comment]
Brotli would be a good idea too, there's a middlewhere here: https://github.com/fullonic/brotli-asgi

**Comment by MrAwesomeRocks** [comment]
That was what I was thinking. The entire middleware is 182 lines: https://github.com/fullonic/brotli-asgi/blob/master/brotli_asgi/__init__.py

**Comment by Goldziher** [comment]
Its worth a discussion. @peterschutt thoughts?

**Comment by peterschutt** [comment]
Two separate issues I think. Supportive of Gzip but I think we should wait until we have sorted out #175.

I think Brotli should be in another issue so we can discuss the forking, etc, that doesn't apply to Gzip.
