### ISSUE TITLE
Feature: Extend lifecycle hooks

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#250]
We currently support two lifecycle hooks for HTTP handlers, it would be good to extend and systematize these because it can be very useful for users. I would like to open this to discussion. 

So questions- 
1. at what junctures does it make sense to add a lifecycle hook?
2. what are some of the use case(s) for the suggested hook?
3. are there any particular difficulties in implementing a suggested hook?
4. are there any arguments against implementing a suggested hook?

**Comment by Goldziher** [comment]
So here are some suggestions:

1. An `after_response` hook that will fire once the response cycle finishes. The use case for this I can see is to be able to plug some instrumentation, e.g. prometheus, to gather matrics, emit logs etc. I don't see any difficulties implementing it. I also dont really see a reason not to do this, but maybe someone else does?
2. An `after_exception` hook that will fire after an exception response has been handled. The use case is basically identical to the one above, i.e. instrumentation. Again I dont see difficulties implementing it. One reason not to do this is to avoid bloat - also we might be able to combine this hook with the previous one suggested and then just have a single hook.

**Comment by wassafshahzad** [comment]
@Goldziher We could take a look at Django signals, There are a few good examples which could be useful such as `pre_save` and `post_save`

**Comment by Goldziher** [comment]
> @Goldziher We could take a look at Django signals, There are a few good examples which could be useful such as `pre_save` and `post_save`

But Django has a builtin ORM. We don't. Do you know Fastify? We can take a queue from what they got.

**Comment by wassafshahzad** [comment]
> > @Goldziher We could take a look at Django signals, There are a few good examples which could be useful such as `pre_save` and `post_save`
> 
> But Django has a builtin ORM. We don't. Do you know Fastify? We can take a queue from what they got. 

I can look into it

**Comment by wassafshahzad** [comment]
@Goldziher sorry for the late reply, I looked into fastify lifecyclehooks and `preSerialization` looks like a good hook to add in addition to `after_response` and `after_exception`

This PR will take some time since I am new to this repo and library in general

**Comment by Goldziher** [comment]
> @Goldziher sorry for the late reply, I looked into fastify lifecyclehooks and `preSerialization` looks like a good hook to add in addition to `after_response` and `after_exception`
> 
> This PR will take some time since I am new to this repo and library in general

No problem. I might do this depending on time available.
