### ISSUE TITLE
Query parameter arrays with 1 element aren't parsed as arrays

### ISSUE THREAD

**Issue by josepdaniel** [starlite-api/starlite#255]
I've been reading through the docs and so far I'm loving how domain modelling is built in with pydantic! Experimenting with query params I noticed that query parameter arrays with 1 element end up with type `T` rather than `List[T]`.  See the example below:

```
from typing import List
from starlite import get, Starlite

@get("/test")
async def test(myArray: List[int]) -> int:
    return 0

app = Starlite(route_handlers=[test])
```

Running 
- `curl "localhost:8000/test?myArray=1"` gives a 400 with `value is not a valid list`. 
- `curl "localhost:8000/test?myArray=1&myArray=2` is fine.  

The workaround isn't too bad - declare myArray as `Union[int, List[int]]` and handle the different types in the body of the function, but I wonder if from an ergonomics perspective its nicer to wrap that logic into the library itself? Something like

```
from pydantic.generics import GenericModel
from typing import List, Generic, TypeVar

DataT = TypeVar('DataT')

class QueryParamArray(GenericModel, Generic[DataT]):
    __root__: Union[DataT, List[DataT]] 

    @property
    def array(self):
        return self.__root__ if isinstance(self.__root__, list) else [self.__root__]
```

Then it would be a simple matter of declaring `myArray` as a `QueryParamArray`. Happy to raise a PR to include this but am not sure where the best place to do so is (types.py?). Also happy to be told this is a stupid idea and its up to the users to declare this utility themselves.

Thanks in advance

**Comment by wassafshahzad** [comment]
> Hi, thanks for reporting.
> 
> Yes this is a bug. We should infer the type and stick with it. Do you want to submit a PR? We will take care of it otherwise.

Is this open to pick up ?

**Comment by Goldziher** [comment]
lets let @josepdaniel respond first. If he doesn't respond within the next few hours, go ahead. 

Also - there wouldn't need to be much adjustment, just a tuning of the parsing logic, which now converts from a list to a single element if the length is one.

**Comment by Goldziher** [comment]
> @Goldziher sure, I'm happy to have a crack at it. I've just started looking at the repo so may take me a few days to get familiar and merge a fix, hope thats alright. 

Take your time
