### ISSUE TITLE
Enhancement: Eager eval of async vs. sync guards

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#289]
In `LifecycleHook` we eagerly evaluate whether a callable is async or sync, so that we don't need to do that for every call to the handler around every request.

Guards would probably benefit from the same - currently we discriminate for every call:

https://github.com/starlite-api/starlite/blob/a2c8a86d42fb347133a5c0c278ae9bc950c75cb7/starlite/handlers/base.py#L220-L228

If we itroduce a `Guard` type like `LifecycleHook` then that could probably reduce down to:

```python
     async def authorize_connection(self, connection: "HTTPConnection") -> None: 
         """ 
         Ensures the connection is authorized by running all the route guards in scope 
         """ 
         for guard in self.resolve_guards(): 
                 await guard(connection, copy(self))
```

**Comment by Goldziher** [comment]
Sure
