### ISSUE TITLE
Enhancement: add support for Picologging

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#291]
Picologging is a new library that looks very promising, it would be great to extend support for it: https://github.com/microsoft/picologging. 

Ideally we would have a logging config for Picologging like we have for the standard lib. 

Of course, Picologging should be an optional dependency or a dev dependency only that throws an `MissingDependencyException` if not present (see other occurances of `MissingDependencyException` in Starliite as an example).

**Comment by MrAwesomeRocks** [comment]
Probably would be a good idea to combine it with [Structlog](https://www.structlog.org/en/stable/).

Here's how I did Stdlib + Structlog (with some SQLAlchemy stuff - just ignore), we can just replace stdlib with picologging and everything should work: https://gist.github.com/MrAwesomeRocks/42645651849bb36b84429d219989dbcb

**Comment by cofin** [comment]
All of the test cases currently pass, but I wanted to do some additional checks.  

Picologging doesn't have a `dictConfig`, so I had to use the existing logging dictConfig.  I'll leave it as a draft until we've done some more testing, and I'll take a look at Structlog.

**Comment by MrAwesomeRocks** [comment]
> Picologging doesn't have a `dictConfig`
Already opened an issue: microsoft/picologging#53

**Comment by cofin** [comment]
Thanks for opening that. I'm watching the issue and we'll update this integration as soon as it's available.  I'll release the integration in its current form later today so that we can begin to use it now.
