### ISSUE TITLE
Make default exception handler response creation logic available from outside ExceptionHandlingMiddleware`

### ISSUE THREAD

**Issue by devtud** [starlite-api/starlite#294]
As far as I can see, Starlite does not log the exceptions, the only thing I see is:

```
INFO:     127.0.0.1:38622 - "GET / HTTP/1.1" 500 Internal Server Error
```

I would like that Starlite prints out the exceptions behind and their trace.

Thanks.

**Comment by peterschutt** [comment]
You can register handlers to exception types and http status codes, this is how I approach it.

You can see in the example app, this module: https://github.com/starlite-api/starlite-pg-redis-docker/blob/main/app/core/exceptions.py

And how that is registered to the application: https://github.com/starlite-api/starlite-pg-redis-docker/blob/78094bc4ea82839ba8703a41381da1e60f0b1d4d/app/main.py#L14

**Comment by devtud** [comment]
> You can register handlers to exception types and http status codes, this is how I approach it.
> 
> You can see in the example app, this module: https://github.com/starlite-api/starlite-pg-redis-docker/blob/main/app/core/exceptions.py
> 
> And how that is registered to the application: https://github.com/starlite-api/starlite-pg-redis-docker/blob/78094bc4ea82839ba8703a41381da1e60f0b1d4d/app/main.py#L14

Thanks. I was thinking at something like that but instantiating a `ExceptionHandlerMiddleware` to take its default exc handler seemed a poor choice initially.

**Comment by peterschutt** [comment]
> > You can register handlers to exception types and http status codes, this is how I approach it.
> > You can see in the example app, this module: https://github.com/starlite-api/starlite-pg-redis-docker/blob/main/app/core/exceptions.py
> > And how that is registered to the application: https://github.com/starlite-api/starlite-pg-redis-docker/blob/78094bc4ea82839ba8703a41381da1e60f0b1d4d/app/main.py#L14
> 
> Thanks. I was thinking at something like that but instantiating a `ExceptionHandlerMiddleware` just for taking its default exc handler seemed a poor choice initially.

Yeh, that `default_http_method_handler()` method used to exist on the `Starlite` class until a recent release so it was a bit cleaner.. you don't need to do that, but I just wanted to get at the pre-existing response generation logic rather than roll my own.. we should probably just split that out into a utility func so that it can be accessed directly.

**Comment by peterschutt** [comment]
@devtud exception response utility now available and example code in the docs.

Thanks for opening the issue.

**Comment by peterschutt** [comment]
@all-contributors please add @devtud for bug
