### ISSUE TITLE
Enhancement: CSRF Middleware

### ISSUE THREAD

**Issue by cofin** [starlite-api/starlite#296]
Implement a middleware to provide CSRF validation.  No additional libraries should be required since everything we'd need is built into Starlette.

**Comment by seladb** [comment]
@cofin @Goldziher I'm trying to tackle this issue. We can use [Starlette's 3rd-party `CSRFMiddleware`](https://github.com/frankie567/starlette-csrf) and write a simple wrapper around it or write our own. What would you prefer?

**Comment by Goldziher** [comment]
> @cofin @Goldziher I'm trying to tackle this issue. We can use [Starlette's 3rd-party `CSRFMiddleware`](https://github.com/frankie567/starlette-csrf) and write a simple wrapper around it or write our own. What would you prefer?

Hi, and thanks. Please no third party dependencies unless they are very strongly maintained, which isn't the case here.

**Comment by seladb** [comment]
Sounds good! In that case we can write our own implementation which should be somewhat similar to [`CSRFMiddleware`](https://github.com/frankie567/starlette-csrf)

**Comment by seladb** [comment]
@Goldziher you can assign this issue to me, it might take me a few days because I'm still new to starlite but I think I can get it done

**Comment by Goldziher** [comment]
> @Goldziher you can assign this issue to me, it might take me a few days because I'm still new to starlite but I think I can get it done

Done. You're welcome to join our discord where we can chat 😉

**Comment by cofin** [comment]
Thanks, @seladb.  Let us know how we can help!

**Comment by Goldziher** [comment]
done
