### ISSUE TITLE
Bug: Sentry middleware doesn't catch errors

### ISSUE THREAD

**Issue by vrslev** [starlite-api/starlite#308]
- Set `SENTRY_DSN` environment variable
- Install `sentry_dsk`
- Run Starlite app:

```python
import os

import sentry_sdk
from sentry_sdk.integrations.asgi import SentryAsgiMiddleware
from starlite import Starlite, get


@get()
def index() -> None:
    raise Exception


sentry_sdk.init(os.environ["SENTRY_DSN"])
app = Starlite(route_handlers=[index], middleware=[SentryAsgiMiddleware])
```

Sentry didn't catch the Exception.

**Comment by Goldziher** [comment]
testing this. next time please add a test PR so we can easily identify the issue.

**Comment by Goldziher** [comment]
verified - the exception is caught before the middleware is invoked. Lets see if there is a solution for this.

**Comment by Goldziher** [comment]
Ok, so I looked into this. IMO there is no issue. Look at this code from the middleware:

```python
def _capture_exception(hub, exc, mechanism_type="asgi"):
    # type: (Hub, Any, str) -> None

    # Check client here as it might have been unset while streaming response
    if hub.client is not None:
        event, hint = event_from_exception(
            exc,
            client_options=hub.client.options,
            mechanism={"type": mechanism_type, "handled": False},
        )
        hub.capture_event(event, hint=hint)
```

And then where it might be invoked:

```python
 with hub.start_transaction(
                        transaction, custom_sampling_context={"asgi_scope": scope}
                    ):
                        # XXX: Would be cool to have correct span status, but we
                        # would have to wrap send(). That is a bit hard to do with
                        # the current abstraction over ASGI 2/3.
                        try:
                            return await callback()
                        except Exception as exc:
                            _capture_exception(
                                hub, exc, mechanism_type=self.mechanism_type
                            )
                            raise exc from None
```

Basically an exception is captured only when its not handled, but it is a handled exception. The only kind of exception you might get here is from a middleware inside the middleware stack before this middleware, which might be unhandled. Sentry should still capture responses and response statuses correctly. So in my opinion this is a non-issue.

What do you think @vrslev ? also @cofin @peterschutt your input would be nice.

**Comment by peterschutt** [comment]
Knowing that Starlite wraps the route handlers in their own exception handling which doesn't let exceptions propagate back through the middleware stack, then yeh this is expected.

However, I'm pretty sure most would expect that an internal error such as this would be ingested by sentry, especially beginners.

I don't experience the issue as due to the logging exception handler pattern:

```python
def logging_exception_handler(request: Request, exc: Exception) -> Response:
    logger.error("Application Exception", exc_info=exc)
    return create_exception_response(exc)
```
... and the fact that sentry automatically injects logs at `ERROR` or higher: https://docs.sentry.io/platforms/python/guides/logging/

**Comment by Goldziher** [comment]
> Knowing that Starlite wraps the route handlers in their own exception handling which doesn't let exceptions propagate back through the middleware stack, then yeh this is expected.
> 
> However, I'm pretty sure most would expect that an internal error such as this would be ingested by sentry, especially beginners.
> 
> I don't experience the issue due to the logging exception handler pattern:
> 
> ```python
> def logging_exception_handler(request: Request, exc: Exception) -> Response:
>     logger.error("Application Exception", exc_info=exc)
>     return create_exception_response(exc)
> ```
> ... and the fact that sentry automatically ingests logs at `ERROR` or higher: https://docs.sentry.io/platforms/python/guides/logging/

So what's your suggestion for resolving this?

**Comment by vrslev** [comment]
I agree with @peterschutt. For Starlite perspective, this behavior is expected, however users (for sure) expect that Sentry will catch server errors.

**Comment by peterschutt** [comment]
> So what's your suggestion for resolving this?

`from sentry_sdk.integrations.starlite import StarliteIntegration`?

For context, specific starlette and fastapi integrations were merged 5 days ago (https://github.com/getsentry/sentry-python/pull/1441 and https://github.com/getsentry/sentry-python/pull/1495)

**Comment by peterschutt** [comment]
https://github.com/getsentry/sentry-python/blob/master/CONTRIBUTING.md#adding-a-new-integration-checklist

**Comment by Goldziher** [comment]
Ok, this is not a "bug" par se. Its incompatibility. The solution is to create a sentry integration - not in this repository. As such I created an issue in the Sentry repository, and am closing this one. See: https://github.com/getsentry/sentry-python/issues/1549
