### ISSUE TITLE
Enhancement: Extend `Partial` to accept other class types

### ISSUE THREAD

**Issue by Harry-Lees** [starlite-api/starlite#309]
Currently, [Partial](https://starlite-api.github.io/starlite/usage/11-data-transfer-objects/#partial-dtos) can be used to create Partial instances of Pydantic classes e.g.

```python
from pydantic import BaseModel
from starlite.types import Partial


class CompanyDTO(BaseModel):
    id: int
    name: str
    worth: float


PartialCompanyDTO = Partial[CompanyDTO]
```

It would be helpful for Partial to also support dataclasses and ORM classes e.g. SQLAlchemy, Tortoise, etc.

**Comment by Goldziher** [comment]
Dataclasses for sure. Supporting plugins is going to be harder to do.

**Comment by Harry-Lees** [comment]
I believe I have an acceptable implementation for dataclasses at the moment, the current implementation uses `dataclasses.fields` and `dataclasses.make_dataclass` to copy across fields. This includes some of the more complex behaviour:

```python
@dataclass
class C:
    x: int
    y: int = field(repr=False)
    z: int = field(repr=False, default=10)
    t: int = 20

    def z_squared(self) -> int:
        return z ** 2

D = Partial[C]
```

would be equivalent to the following class definition

```python
@dataclass
class C:
    x: int
    y: int = field(repr=False)
    z: int = field(repr=False, default=10)
    t: int = 20
```

obviously, we lose some information with the methods, but I believe the same thing happens with the pydantic base class. Let me know if you think we should be copying the fields and I can rework the code slightly, otherwise I can open a PR shortly.

**Comment by Harry-Lees** [comment]
I believe I have an acceptable implementation for dataclasses at the moment, the current implementation uses `dataclasses.fields` and `dataclasses.make_dataclass` to copy across fields. This includes some of the more complex behaviour:

```python
@dataclass
class C:
    x: int
    y: int = field(repr=False)
    z: int = field(repr=False, default=10)
    t: int = 20

    def z_squared(self) -> int:
        return z ** 2

D = Partial[C]
```

would be equivalent to the following class definition

```python
@dataclass
class C:
    x: int
    y: int = field(repr=False)
    z: int = field(repr=False, default=10)
    t: int = 20
```

obviously, we lose some information with the methods, but I believe the same thing happens with the pydantic base class. Let me know if you think we should be copying the fields and I can rework the code slightly, otherwise I can open a PR shortly.

**Comment by Goldziher** [comment]
I think we should aim for a class identical to the base with modification of types to Optional
