### ISSUE TITLE
allow empty `""` path in Controller ?

### ISSUE THREAD

**Issue by vincentsarago** [starlite-api/starlite#31]
https://github.com/starlite-api/starlite/blob/965d97620774991bd302a3a227bd3ebe6236ae96/starlite/controller.py#L27-L28

### Context
In some of our project (built with FastAPI) we use **Factory** classes that helps us creating bunch of endpoints for given user inputs and dependencies (https://developmentseed.org/titiler/advanced/tiler_factories/ https://developmentseed.org/titiler/api/titiler/core/factory/#tilerfactory). This is why I was really interested in the `Controller` class to replace our `Factories`. 

One problem I'm facing right now is that Controller `Path` has to be non null. 

```python
from starlite import get, Starlite
from starlite.controller import Controller
from starlette.requests import Request


class Endpoints(Controller):
    """TileMatrixSets endpoints."""

    path = "/"

    @get(path="/yo")
    def hey(self, request: Request) -> str:
        return "yipi"

    @get(path="ye")
    def hey2(self, request: Request) -> str:
        return "what"


app = Starlite(route_handlers=[Endpoints])
```
schema

<details>

```json
{
  "openapi": "3.1.0",
  "info": {
    "title": "Starlite API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "/"
    }
  ],
  "paths": {
    "//yo": {
      "get": {
        "operationId": "hey",
        "responses": {
          "200": {
            "description": "Request fulfilled, document follows",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "//ye": {
      "get": {
        "operationId": "hey2",
        "responses": {
          "200": {
            "description": "Request fulfilled, document follows",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    }
  }
}
```

</details>

as we can see in the schema ☝️, both endpoints are `//` prefixed because Starlite is normalizing path (I think).  I can agree that I want to use the Controller class for something it wasn't designed for, but it could be nice if the `path` could be set to `""`.

### Potential fix

By allowing path to be all but not `None` it seem to fix my issue, but I'm not quite sure what it means for the rest of the application.

```python
class Endpoints(Controller):
    """TileMatrixSets endpoints."""

    path = ""

    def __init__(self, owner: "Router"):
        if not hasattr(self, "path") or self.path is None:
            raise ImproperlyConfiguredException("Controller subclasses must set a path attribute")

        for key in ["dependencies", "response_headers", "response_class", "guards"]:
            if not hasattr(self, key):
                setattr(self, key, None)

        self.path = self.path
        self.owner = owner
        for route_handler in self.get_route_handlers():
            route_handler.owner = self

    @get(path="/yo")
    def hey(self, request: Request) -> str:
        print(request)
        return "yipi"

    @get(path="/ye")
    def hey2(self, request: Request) -> str:
        print(request)
        return "what"
```

again, I will understand that I want to use the Controller class outside of its scope 🙏

**Comment by Goldziher** [comment]
Hiya. 

How about this solution: 

1. We move the validation to a method that is called by `Controller.__init__`. 
2. You can then override it in your subclass.

**Comment by Goldziher** [comment]
@adriangb , you wanna take a look at this?

**Comment by vincentsarago** [comment]
> If I understand you correctly you would.in effect like to use a controller on the root level, correct?

Yes. 

> If this results in //, we need to fix it.

It does (see schema) 

> In either case, would you like to add a PR with a fix (and changelog update)?

I can try, later today or tomorrow 😄

**Comment by vincentsarago** [comment]
@Goldziher I'm not quite sure of the solution here.

## Case 1: `path = ""`

This is quite straight forward, meaning that routes won't have any prefix. This also ensure the user set `""` as the path and that we will only raise is path is not set at all. We could just add a note in the documentation (or a warning in the code) that `""` path will append routes at the root.

## Case 2: `path = "/"` 

This could cause some misunderstanding. To me all routes should be prefixed with `/` (I believe `//yo` is a valid path 🤷.

**Comment by Goldziher** [comment]
Sure, path 1 is good. Just add a note on the docs as well.

Maybe raise an informative error if the path is set to "/" by the user, or also allow that case.
