### ISSUE TITLE
Enhancement: Extended documentation for multiple responses

### ISSUE THREAD

**Issue by lewoudar** [starlite-api/starlite#316]
Hi folks,
I just discovered this framework today, it seems really promising. But I already have one question after reading the docs.
It seems like it is not possible to document alternative responses for a route path (or may be I read too fast), i.e. something like [this](https://fastapi.tiangolo.com/advanced/additional-responses/) in FastAPI.

**Comment by Goldziher** [comment]
You can just type the return value as a union type and it will infer the responses for you.

**Comment by lewoudar** [comment]
Ok I see, but the issue here is that you can't customize the message, description, etc...

**Comment by Goldziher** [comment]
> Ok I see, but the issue here is that you can't customize the message, description, etc...

Per response content body content? Not at present. 

To be clear - we are talking here bout customizing the description of elements inside whats called `oneOf` In OpenAPI, correct?

**Comment by lewoudar** [comment]
> To be clear - we are talking here bout customizing the description of elements inside whats called oneOf In OpenAPI, correct?

Yes!

**Comment by Goldziher** [comment]
> > To be clear - we are talking here bout customizing the description of elements inside whats called oneOf In OpenAPI, correct?
> 
> Yes!

Ok. I'll Label this as an enhancement request then. You're welcome to contribute a PR to handle this, or someone else will get to it 😀

**Comment by lewoudar** [comment]
Unfortunetaly I don't have too much time now to dig in the code 😢
You probably want to affect it to another person

**Comment by Goldziher** [comment]
No worries

**Comment by Goldziher** [comment]
@seladb any progress?

**Comment by seladb** [comment]
Unfortunately I didn't have time to get to it yet, but it seems like a good issue to work on 🙂
If someone else wants to take it I can un-assign myself, otherwise would it be ok to give me a few more weeks?

**Comment by Goldziher** [comment]
> Unfortunately I didn't have time to get to it yet, but it seems like a good issue to work on 🙂
> If someone else wants to take it I can un-assign myself, otherwise would it be ok to give me a few more weeks?

Sure, take your time.

**Comment by seladb** [comment]
@Goldziher just to make sure: do we want to support additional responses with different status codes or just customizing the description of existing return values?

**Option 1:** support additional responses can be quite similar to what FastAPI has, for example:
```python
@get(..., responses={404, {"model": Message}})
``` 

**Option 2:** allow customizing the description of existing return values - not yet sure how to achieve this because there is no description for each return type 🤔 
![image](https://user-images.githubusercontent.com/9059541/189322403-8c878d9d-4769-4111-a483-fccbc3cc7d13.png)

**Comment by Goldziher** [comment]
As you see fit

**Comment by seladb** [comment]
Option 1 seems easier to implement and makes more sense. I'll go for it 😃
