### ISSUE TITLE
Enhancement: Contrib

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#330]
It might be useful to add a `starlite.contrib` package, with some base implementations that users might extend. For example, a `starlite.contrib.authentication.jwt` might be a package that includes an optional JWT authentication backend, as [given in the docs as an example](https://starlite-api.github.io/starlite/usage/8-authentication/?h=jwt#example-create-a-jwt-authentication-middleware).

There are several other things that might go there. We need though to evaluate this - it might lead to bloating. So please add your opinions and lets have a discussion.

**Comment by cofin** [comment]
I'd like to see something like this.  It gives a standard location to put any extensions and it gives a clear indication in the module name that it's for "extra" functionality.

**Comment by Tobi-De** [comment]
I agree with @cofin, it's a good idea, but if one of the main goals of startlite is to be as light as possible, then over time yes it might become bloat. Maybe a separate package for that is more appropriate.
