### ISSUE TITLE
Documentation: reference example project

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#335]
We should provide a link to the example project(s) from the docs and readme to make it more apparent to users that they exist.

**Comment by chicken-teriyaki-cup-rice** [comment]
Is this what you had in mind? Apologies, I'm new to all this.

**Comment by peterschutt** [comment]
Hey @chicken-teriyaki-cup-rice - love your profile name by the way! You're making me hungry :laughing: 

Thanks for this! I've assigned this issue to you but no pressure, remove yourself anytime if you like.

I have a some suggestions:

1. follow the guidelines `CONTRIBUTING.md` to get pre-commit configured to run locally, that way you'll pick up any failures before CI does. In this case, your contribution causes:
```
markdownlint.............................................................Failed
- hook id: markdownlint
- exit code: 1

README.md:40:34 MD039/no-space-in-links Spaces inside link text [Context: "[ Example Starlite project usi..."]
```
2. I would suggest adding a 2nd level heading (`##`) below the `Core Features` section in the readme, called `Examples` and include this in there, rather than right at the top of the readme. We can then use that section to promote any other examples that we find out in the wild.
3. Include similar in the docs as well, the `index.md` page has similar subject matter to the readme, so you should be able to find a similar place to position the `Examples` section in there.

Thanks again, once you are happy with you PR we can make specific reviews in there.

**Comment by Goldziher** [comment]
Oops. @chicken-teriyaki-cup-rice, I merged your PR before seeing this thread. Can you do another PR to follow up with what @peterschutt wrote above?
