### ISSUE TITLE
Proposal: allow for route handlers to return tuples to handle response headers and cookies.

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#338]
So as I see it the current API is somewhat constricted, as also pointed out in #278. Namely, if the user wants to set response header, cookies or background tasks the only option really is to use an instance of `starlite.responses.Response` or `starlette.responses.Response`. For example, lets say a user returns the following json response:

```python
from starlite import get


@get("/greet/{name:str}")
def greet_handler(name: str) -> dict[str, str]:
    return {"hello": name}
```

If the user wants to set a specific header on this response he or she has three options, either return a response class, use the `after_request` life-cycle hook, or use a middleware. While all of these are viable, if the user wants to do some sort of computation in the route handler function and set the header based on it, only the response class route is viable:

```python
from starlite import Response, MediaType, get
from starlette.status import HTTP_200_OK


@get("/greet/{name:str}")
def greet_handler(name: str) -> Response:
    return Response(content={"hello": name}, media_type=MediaType.JSON, status_code=HTTP_200_OK, headers={"MY_HEADER": name})
```

The problem with the above is that OpenAPI docs are not going to be very good in this case, because we do not know the response content. 

One option would be to make the `Response` class generic and then use the typing args that go into it. This though is not very scalable and it will break existing code.

So the other option I can think of, and which I think is better, is to allow route handlers to return a NamedTuple of values if needed:

```python
from typing import NamedTuple, Any, Optional, Dict, Tuple, TYPE_CHECKING, Generic, TypeVar
from starlite import get

if TYPE_CHECKING:
    from starlette.background import BackgroundTask

T = TypeVar("T")
    
class ResponseValues(NamedTuple, Generic[T]):
    data: T
    headers: Optional[Dict[str, str]]
    cookies: Optional[Dict[str, str]]
    background: Optional["BackgroundTask"]


@get("/greet/{name:str}")
def greet_handler(name: str) -> ResponseValues[Dict[str, str]]:
    return ResponseValues(data={"hello": name}, headers={"MY_HEADER": name})
```

We will be able to access the generic value here for documentation, and this is going to be simpler then to modify the response class.

**Comment by peterschutt** [comment]
Seems a reasonable idea to me - a bit like flask responses.

**Comment by cofin** [comment]
This makes sense to me as well.
