### ISSUE TITLE
Enhancement: Instrumentation hooks

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#350]
The suggestion here is to add several new hooks, primarly meant for instrumentation and any use case that needs access to some internals.

Hooks:

* `after_startup`: fires after the ASGI lifecycle startup finishes and calls whatever handler (sync or async) is defined by passing to it the Starlite app instance. The application will block connections until the hook returns / ends. 
* `after_shutdown`: similar to the previous one, accept it fires when shutdown is finished. 
* `after_exception`: calls a handler when an exception occurs. The handler is given the exception and it must raise an exception - this allows for example to record exceptions or transform them, but is not meant to replace an exception handler. 

Some other options that crossed my mind but im not sure about:

* `before_startup`: called as part of the ASGI lifecycle startup, before any function set in the `on_startup` callable list. Receives the app instance. 
* `before_shutdown`: same as above, but for shutdown. Receives the app instance.
* `before_routing`: called when an ASGI call is received by the app and before resolving routing etc. Receives the ASGI `scope` object

Please give input and any suggestions you may have.

**Comment by lewoudar** [comment]
Hello, honestly I'm not sure to see the importance of `after_startup`, `after_shutdown` and the `before` counterparts. It is over engineering for me since we already have callbacks for startup and shutdown. For the two others I have no opinion.

**Comment by cofin** [comment]
I like the idea of all of these hooks.  

On another project, I could have really benefited from a before/after shutdown hook.   If we get to this level of granularity, I think we have quite a bit of control on how/what to implement with the OpenTelemetry integrations.

At the moment, I can't think of anything I'd add to the list above, but will update accordingly if something comes to mind.

**Comment by peterschutt** [comment]
How about before/after request hooks that are guaranteed to be called, configured at the app level and separate from handler resolution. 

Use-case is this:

```py
async def session_after_request(response: Response) -> Response:
    """
    Passed to `Starlite.after_request`.

    Inspects `response` to determine if we should commit, or rollback the database
    transaction.

    Finally, calls `remove()` on the scoped session.

    Parameters
    ----------
    response : Response
        The outgoing response.

    Returns
    -------
    Response
        Passed through from input assuming that commit/roll back does not error.
    """
    if 200 <= response.status_code < 300:
        await AsyncScopedSession.commit()
    else:
        await AsyncScopedSession.rollback()
    await AsyncScopedSession.remove()
    return response
```
I'd like to know that always runs irrespective of whether a user defines a hook for a particular route without them having to know that they need to manage that themselves.

**Comment by Goldziher** [comment]
> How about before/after request hooks that are guaranteed to be called, configured at the app level and separate from handler resolution.
> 
> Use-case is this:
> 
> ```python
> async def session_after_request(response: Response) -> Response:
>     """
>     Passed to `Starlite.after_request`.
> 
>     Inspects `response` to determine if we should commit, or rollback the database
>     transaction.
> 
>     Finally, calls `remove()` on the scoped session.
> 
>     Parameters
>     ----------
>     response : Response
>         The outgoing response.
> 
>     Returns
>     -------
>     Response
>         Passed through from input assuming that commit/roll back does not error.
>     """
>     if 200 <= response.status_code < 300:
>         await AsyncScopedSession.commit()
>     else:
>         await AsyncScopedSession.rollback()
>     await AsyncScopedSession.remove()
>     return response
> ```
> 
> I'd like to know that always runs irrespective of whether a user defines a hook for a particular route without them having to know that they need to manage that themselves.
> 
> I could handle it by doing the middleware `send_wrapper()` trick, but I feel like that is a bit of an anti-pattern/workaround..

`on_connection_start` and `on_connection_close`?

**Comment by peterschutt** [comment]
The important thing for the db transaction is getting the response as late as possible but before it is actually awaited, so the commit has the chance to error before the response is sent. Does that align with `on_connection_close` do you think? 

We haven't used `before_response`, yet but it would be confusing to have `after_response` resolved down to the handler as it is, and `before_response` only at the app level.

Maybe we need a separate namespace for hooks that aren't resolved and are guaranteed to run irrespective of the resolved hook, so it is clearer which is which, rather than relying on memorising which hooks have which behaviour.

**Comment by cofin** [comment]
One thing I'll add re: the database commit.  If you look at something like Cloud Run, by default it only allocates CPU when the container is processing a request.  So, in this model, you can have the CPU throttled to 0 before the database gets the commit.
