### ISSUE TITLE
Application doesn't fallback to index.html when the file is not specified

### ISSUE THREAD

**Issue by infohash** [starlite-api/starlite#354]
```python
app = Starlite(route_handlers=[device_router, health_check],
               static_files_config=[
                   StaticFilesConfig(
                       directories=['templates'], path='/home', html_mode=True)
                   ],
               openapi_config=OpenAPIConfig(title='Starlite Service', version='0.0.1'))
```

## Structure

```
── src
│   ├── ...
│   ├── templates
│   │   ├── 404.html
│   │   ├── index.html
│   ├── ...
```

Path set in `StaticFilesConfig`: http://127.0.0.1:8000/home

## From Documentation

[Static Files](https://starlite-api.github.io/starlite/usage/0-the-starlite-app/3-static-files/)

> If html_mode is enabled and no specific file is requested, the application will fall back to serving index.html. If no file is found the application will look for a 404.html file in order to render a response, otherwise a 404 NotFoundException will be returned.

## Observed Behaviour

When I don't specify the file, it doesn't fallback to `index.html`. It is falling back to `404.html`.

## Expected Behaviour

Visiting http://127.0.0.1:8000/home should serve `index.html` instead of 404.html. If `index.html` is not available, then it should fallback to 404.html.

## What's Working

http://127.0.0.1:8000/home/index.html is working.

**Comment by Goldziher** [comment]
ok, this is a starlette bug. For now append index.html to the path - either its solved in Starlette or we resolve it here. 

See: https://github.com/encode/starlette/discussions/1806

**Comment by infohash** [comment]
Let's wait for the fix in upstream.

**Comment by cofin** [comment]
These changes look good to me.

**Comment by Goldziher** [comment]
v1.10.1 is being released now. Please test the fix @infohash
