### ISSUE TITLE
Enhancement: Easily configure which UI is served at the root of the OpenAPI Controller

### ISSUE THREAD

**Issue by mobiusxs** [starlite-api/starlite#356]
The OpenAPI Controller doesn't have a built-in way to select which UI will be served at the root path and defaults to Redoc.

https://github.com/starlite-api/starlite/blob/main/starlite/openapi/controller.py#L140

I want the root URL of my APIs to serve the Swagger UI. To accomplish this, I must subclass the controller and rewrite the `swagger_ui`, `redoc`, and `stoplight_elements` methods, which include a lot of HTML and make my APIs resistant to framework updates, and reroute them. This is because routing is only possible via decorators.

To accomplish this, I propose the following approach:

1. Move the bodies of the above-mentioned routed methods to `render_` methods.
2. Use the existing routed methods to serve the return value of the `render_` methods to maintain current functionality.
3. Add an attribute to `OpenAPIController`: `root = 'redoc'` to maintain current functionality.
4. Add a routed method to `OpenAPIController` like that serves whatever content is specified by `root` at `/`.

Now, to serve the Swagger UI at the root of an API, just subclass the `OpenAPIController` like this:

```
class RootOpenAPIController(OpenAPIController):
    path = '/'
    root = 'swagger'
```

The value of `root` should be validated to be in the set of `{'redoc', 'swagger', 'elements'}`. That set could be expanded to include `yaml` and `json`, as those are valid routes on the controller as well, despite not being UIs. Someone may want that too.

**Comment by Goldziher** [comment]
This is a good proposal. Go ahead and implement it.

**Comment by Goldziher** [comment]
I suggest you make a PR with the solution you think is best- it will be easier to understand seeing the code.
