### ISSUE TITLE
Enhancement: Add 'path' type to path parameters

### ISSUE THREAD

**Issue by waweber** [starlite-api/starlite#371]
Starlette's route path parameters include a `path` type that matches any further path components. Example: `Route('/uploaded/{rest_of_path:path}', uploaded)` would match `/uploaded/some-dir/some-file.txt` with `rest_of_path` set to `some-dir/some-file.txt`.

A couple cases where this might be useful:

- A file upload service where uploaded files are exposed as a virtual directory tree
- A blog where posts have extra path components for readability and SEO which are otherwise ignored, like `/posts/1234/2022/8/14/how-to-use-path-parameters/` with only `/posts/1234` being necessary

It doesn't look like this is supported yet in Starlite. Is there a recommended approach in the meantime?

**Comment by Goldziher** [comment]
Not at present. I'm not sure how simple this is with our routing system.

**Comment by waweber** [comment]
I looked through the routing code and it should be relatively simple to add this. However, I did discover a couple bugs I will create a separate issue for.

**Comment by Goldziher** [comment]
Great, if you are confident, a PR is welcome 😉

**Comment by Goldziher** [comment]
@waweber do you intend to add this?
