### ISSUE TITLE
Bug: Certain routes break the route_map structure

### ISSUE THREAD

**Issue by waweber** [starlite-api/starlite#373]
I found a few ways to specify routes that result in a `route_map` which doesn't work as expected. Here's an example script:

```python
from pprint import pprint
from starlite import Starlite, get, Controller

class Example(Controller):
    # Breaks because app.py:279 replaces all "user:str" with the empty string
    @get("/test1/user:str/{user:str}")
    def route1(self, user: str) -> str:
        return f"User: {user}"

    # Throws an exception because "_components" is a special value in the route map
    @get("/test2/_components/{user:str}")
    def route2(self, user: str) -> str:
        return f"User: {user}"

    # Breaks because "*" is a special value in the route map.
    # GET /test3/foo/bar returns "User: foo"
    @get("/test3/*/{user:str}")
    def route3(self, user: str) -> str:
        return f"User: {user}"

app = Starlite(route_handlers=[Example])
pprint(app.route_map)
```

The bug from example 1 starts at the regex used to parse route parameters (https://github.com/starlite-api/starlite/blob/main/starlite/routes/base.py#L21). `re.findall` will match "{user:str}" and return "user:str" without the brackets as the match because the pattern has exactly one capturing group. This is then `.replace`d with the empty string when building the route map (https://github.com/starlite-api/starlite/blob/3914b5090d6db579152a24e954dd31cc89684bac/starlite/app.py#L283) but since it doesn't include the brackets, it could include non-parameter url segments.

Example 2 throws an exception during route map construction simply because `_components` is a special name. There is currently no documentation about what path components are reserved names, but I think a proper fix would be to make the metadata not be an element inside the prefix tree.

Example 3 is similar in that "*" has special meaning in the prefix tree that is not documented. This results in an extra path param, and the `user` param will no longer be properly mapped.

**Comment by Goldziher** [comment]
Hiya,

Well TBH Im aware that `_components` and `*` will break. I believe that these are not possible edge cases in user land, but rather require that the user intentionally tries to break stuff. In this case we do not need to cater to the user. This is why this is not guard against. We could though add validation specifically against using these in the `_validate_path_parameters` method on the `BaseRoute` class, which you already discovered. Saying that, I am open to any PR that has an elegant and clean solution to this.

As for the first issue `/test1/user:str/{user:str}` - here you indeed identify a bug IMO. We should validate the path string and ensure that all path params are well formed or through an exception. If you want to contribute this, it would be great.
