### ISSUE TITLE
Enhancement: Logging Middleware

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#411]
We've decided to include an optional logging middleware. The middleware should log incoming requests and out-going responses. It needs to be configurable:

1. The user should be able to dictate the values that are being logged and the logging ourput structure. 
2. The middleware should support obfuscating data and excluding logging for specifc paths.
3. The middleware must use the logging config as a basis - i.e. register the logger as part of the config, and allow the user to decide on dictate what logger is actually used (e.g. picologger, stdlib, some structlogger etc.)

**Comment by Swannbm** [comment]
I am starting something.

**Comment by Swannbm** [comment]
Here some thinking about how to do it:

>The middleware should log incoming requests and out-going responses

I will make a first PR with this capabilities (so very simple). I'll add two debug log, one on incoming request and the other on outgoing response. I am thinking using INFO level.

I will name the logger classicaly using __name__.

> 1. The user should be able to dictate the values that are being logged

Are you speaking of choosing if he logs both (incoming / outgoing) or only one of them or even none of them.

Another idea could be to choose what is logged:
- url requested
- content-type expected
- browser used and other client information
- response status
...

> and the logging output structure.

I will add a format option that will override logging configuration for this logger.

> 2. The middleware should support obfuscating data and excluding logging for specifc paths.

I will add tow options:
- first, a callable list to parse the str that will be logged (that's for obfuscating).
- second a path exclusion list but I am unsure of the purpose of that. Shouldn't we log something minimal for that ?

> 3. The middleware must use the logging config as a basis - i.e. register the logger as part of the config, and allow the user to decide on dictate what logger is actually used (e.g. picologger, stdlib, some structlogger etc.)

I will add a logger_class in the configuration to load the correct one.

I am not an expert here, please feel free to complete your wish.
