### ISSUE TITLE
Enhancement: A Better Session Cookie Management 

### ISSUE THREAD

**Issue by infohash** [starlite-api/starlite#412]
We need a more optimal approach on managing session cookies. The problem with `starlette.middleware.session.SessionMiddleware` is that it does not create multiple cookies if there is a large session data to store that cannot be fit into one `Set-Cookie` HTTP response header. The max-size limit per cookie allowed by the browsers is `4096 bytes` beyond which browsers silently ignores the `Set-Cookie` header.

Adding to the problem of storing entire session data into just one cookie, `base64` encoder further increases the size of `Set-Cookie` header. This causes the issue with storing Oauth2 and OIDC tokens and their metadata whose size is already too large to store in one `Set-Cookie` header. If the user is using multiple Identity Providers in the app, that will multiply the session data.

# What we need

1. Support for splitting cookies if the size of the session is greater than 4096 bytes. Browsers allows 150-180 cookies per domain and max-size of 4096 bytes per cookie.

[Set-Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie)
>  To send multiple cookies, multiple `Set-Cookie` headers should be sent in the same response. 

2. `base64` encoding of `Set-Cookie` header is recommended by [RFC4648](https://datatracker.ietf.org/doc/html/rfc4648).

> To maximize compatibility with user agents, servers that wish to
   store arbitrary data in a cookie-value SHOULD encode that data, for
   example, using Base64.

But we can also use custom encoders that will not increase the size that much. Nice to have if we can compress the size of encoded string.
[What are allowed characters in cookies?](https://stackoverflow.com/a/1969339/6538535)
> In practice you cannot use non-ASCII characters in cookies at all. If you want to use Unicode, control codes or other arbitrary byte sequences, the cookie_spec demands you use an ad-hoc encoding scheme of your own choosing and suggest URL-encoding (as produced by JavaScript's encodeURIComponent) as a reasonable choice.

[Flask seems to be using a custom encoder](https://github.com/pallets/flask/blob/36af821edf741562cdcb6c60d63f23fa9a1d8776/src/flask/sessions.py#L353) which actually decreases the size after encoding and signing which is impressive but also complex.

---

# Notes

1. Splitting the session into multiple cookies solves the size problem so it is fine to use `base64`.

2. We can upstream the feature 1 to `SessionMiddleware` but if you have more ideas to improve session management further, we can offer a middleware out of box that manages the session.

# References For Cookie Specification

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

https://datatracker.ietf.org/doc/html/rfc6265

# Nice To Have

## Authenticated encryption for session cookies.

[Session Management: Expire and Max-Age Attributes](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#expire-and-max-age-attributes)

> Ensure that sensitive information is not compromised by ensuring that it is not persistent, encrypting it, and storing it only for the duration of the need
>
> Ensure entire cookie should be encrypted if sensitive data is persisted in the cookie
    
`itsdangerous` does not support encryption of cookie. See, [How to overcome limitations of itsdangerous for SSO: encryption and expired tokens](https://stackoverflow.com/questions/27641044/how-to-overcome-limitations-of-itsdangerous-for-sso-encryption-and-expired-toke). 

It is under nice to have section because integrity of cookie is what matters more than its confidentiality. See, [Why should the value of the cookie be encrypted?](https://security.stackexchange.com/questions/141675/why-should-the-value-of-the-cookie-be-encrypted). But sometimes, enterprises do have a requirement of encrypted cookies so this feature can be offered optionally.

> **Note**: There is already a library [JWCrypto](https://github.com/latchset/jwcrypto) that encrypts JWTs so the confidentiality of the session cookies do not completely fall on us.

**What Do You Think?**

**Comment by Goldziher** [comment]
Sounds good to me. 

Im for having our own session middleware - i would like to add optional persistence as well. To allow for session based autorization (see the builtin django auth as an example).

**Comment by peterschutt** [comment]
Agree with note #1 - if producing multiple cookies isn't an issue then the encoding isn't a problem unless reducing the size has better performance characteristics.

This issue is an interesting related read: https://github.com/oauth2-proxy/oauth2-proxy/issues/482 - it tails off into very k8s specific session storage ideas but in the end they mention that they LZ4 compress their sessions so that for the most part splitting isn't an issue.
