### ISSUE TITLE
Bug: Documentation Site doesn't work properly in mobile.

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#420]
The Doc site isn't working well in mobile. You need to press the back arrow to find the menu to see usage and reference.

**Comment by omertalmi5** [comment]
I would like to solve that issue.
Can you explain the expected behavior by you?
It looks well for me, the menu keeps its state.
Attaching reproducing from my mobile.

https://user-images.githubusercontent.com/43521606/187301451-3bd62049-ab5d-4b5e-b8bf-47a286ad73ce.mp4

**Comment by Goldziher** [comment]
> @Goldziher 
> I would like to solve that issue.
> Can you explain the expected behavior by you?
> It looks well for me, the menu keeps its state.
> Attaching reproducing from my mobile.
> 
> https://user-images.githubusercontent.com/43521606/187301451-3bd62049-ab5d-4b5e-b8bf-47a286ad73ce.mp4
> 
> 

Broker tov Omer,

To be honest I resolved this issue a few hours before you write this, and forgot to close the issue.

**Comment by alphanoobie** [comment]
Hello! I was trying to work on this issue but was not able to find a fix for it.
It would be a great help if you could tell me a gist of how you solved it @Goldziher
