### ISSUE TITLE
[enhancement] allow the exclusion of some keys or None in output response

### ISSUE THREAD

**Issue by vincentsarago** [starlite-api/starlite#43]
In other Framework (e.g FastAPI), users can set the output model but also exclude specific keys or unset values without the need of re-writting new classes:

#### With FastAPI
```python
class User(BaseModel):
    name: str
    password: str
    age: Optional[int]

@app.get(
    "/user", 
    response_model=User,
    response_model_exclude_none=True,
    response_model_exclude={"password"},
)
def get_user() -> User:
    return User(name="vincent", password="starlite")
```
#### With Starlite
```python
class User(BaseModel):
    name: str
    password: str
    age: Optional[int]

class UserWithoutPassword(BaseModel):
    name: str
    age: Optional[int]

@get(path="/user")
def get_user() -> UserWithoutPassword:
    return UserWithoutPassword(**User(name="vincent", password="starlite").dict())
```
Note: in Starlite, we don't need the `response_model=User` because it's defined in the model signature.

**Comment by Goldziher** [comment]
I'm not sure how to go about this - no clue how to design the interface for this. suggestions? Perhaps there should be something like a pydantic config - which you could set on various levels. What do you think?

**Comment by Goldziher** [comment]
Thoughts on this one @peterschutt ?

**Comment by peterschutt** [comment]
I don't know...

Given the above example, I'd prefer to have a user model:

```python
class User(BaseModel):
    name: str
    age: Optional[int]
```

and a create-user model:

```python
class CreateUser(User):
    password: str
```
And then only use the `CreateUser` model for post:

```python
@post("/user")
def create_user(data: CreateUser) -> User:
    ...
```
Otherwise I'd need all that boilerplate, e,g,:

```python
@get(
    "/user", 
    response_model_exclude_none=True,
    response_model_exclude={"password"},
)
```
or whatever that would turn out to be, for every method that returns a `User`.

Maybe a more real-world example would help to convince me.

**Comment by Goldziher** [comment]
Ok. I'm closing this then.
