### ISSUE TITLE
[enhancement] per controller url_for/url_path_for

### ISSUE THREAD

**Issue by vincentsarago** [starlite-api/starlite#45]
Within a controller, I don't think you can find a `url` for another handler using starlette url_path_for.

A working example of it can be found over https://github.com/developmentseed/pg_mvt/blob/10fa599928fc96ea30fad63289e40e39e564845d/pg_mvt/factory.py#L66-L96

**Comment by Goldziher** [comment]
The Starlette `url_path_for` is not implemented in starlite at all. It was removed in version 0.5.0 - previously the BaseRoute class had an implementation but it was removed.

What is the use case for these?

**Comment by Goldziher** [comment]
So, @vincentsarago - any input? otherwise please close

**Comment by vincentsarago** [comment]
yes Sorry @Goldziher 

In a lot of our application we use endpoint which will return links to other endpoints (within the same app). The most obvious example I have in mind is TileJSON (https://github.com/developmentseed/pg_mvt/blob/master/pg_mvt/factory.py#L156-L202) where a user send request to the application and receive a TileJSON document referencing Tiles URL. 

As mentioned, I've implemented this on my end, but I think it would be a nice feature to have

**Comment by Goldziher** [comment]
Ok, starlite has a different architecture and this stuff won't work as such.

We could implement this as a method on the app instance, so you could do `request.app.urls_for()`. In the plural because the path is now paths as you know.

We can then also have a controller level method. 

Would you like to take care of this issue?

**Comment by vincentsarago** [comment]
>  In the plural because the path is now paths as you know.

yeah, I updated my code (but not pushed in GitHub yet)

```python
class Controller(controller.Controller):
    """Custom controller class."""

    def url_for(self, request: Request, name: str, **path_params: Any) -> str:
        """Return full url (with prefix) for a specific endpoint."""
        url_path = self.url_path_for(name, **path_params)

        base_url = str(request.base_url)
        if self.path:
            base_url += self.path.lstrip("/")

        return url_path.make_absolute_url(base_url=base_url)

    def url_path_for(self, name: str, **path_params: Any) -> URLPath:
        """return path for a controller handler."""
        for route in self.get_route_handlers():
            for route_path in route.paths:
                path_regex, path_format, param_convertors = compile_path(route_path)
                print(route_path)
                try:
                    seen_params = set(path_params.keys())
                    expected_params = set(param_convertors.keys())

                    if name != route.fn.__name__ or seen_params != expected_params:
                        raise NoMatchFound()

                    path, remaining_params = replace_params(path_format, path_params)
                    assert not remaining_params
                    return URLPath(path=path, protocol="http")
                except NoMatchFound:
                    pass

        raise NoMatchFound()
```

I'm not quite sure how it will work at the application level because controller could technically mount same handler but with different path (prefix) so it won't be able to find only one solution. 

> Would you like to take care of this issue?

Sadly I'm quite booked at the moment. We can totally close this issue for now

**Comment by Goldziher** [comment]
Well, lets keep this issue open. Either you find the time, I do or someone else decides to pick it up.

**Comment by Goldziher** [comment]
@vincentsarago -- any update on this?

**Comment by vincentsarago** [comment]
sorry @Goldziher I haven't worked on this! feel free to close the issue!
