### ISSUE TITLE
Enhancement: Path Resolver For Route Handler Methods On A Controller

### ISSUE THREAD

**Issue by infohash** [starlite-api/starlite#455]
**What's the feature you'd like to ask for.**
With `Starlite.route_handler_method_view`, you can resolve paths of route handler instance. So for example, if a decorator receives a route handler instance, it can resolve its path with this dictionary. But it raises `KeyError` when the route handler methods are desfined on a controller.

This is because `Starlite.Controllers.get_route_handlers` creates a shallow copy of the instance when creating a list of the route handlers defined on the controller. It means the instance registered in the `Starlite.route_handler_method_view` is different from what decorator received and when the decorator will try to resolve its path, it will raise `KeyError`.

```python
...
for f_name in route_handler_fields:
    source_route_handler = cast("BaseRouteHandler", getattr(self, f_name))
    route_handler = copy(source_route_handler)
    route_handler.owner = self
    route_handlers.append(route_handler)

return route_handlers
```

**Additional context**

```python
from starlite import Controller, Starlite, get


def route_decorator(route_handler_instance):

    def wrapper(*args, **kwargs):
            # do something
            ...
            try:
                app.route_handler_method_view[route_handler_instance])
            except KeyError:
                raise
            # do something
            ...
    return wrapper


class Star(Controller):

    path = "/test"

    @route_decorator
    @get()
    def test_handler(self) -> None:
        pass


@route_decorator
@get(path="/root")
def root_handler() -> None:
    pass


app = Starlite(route_handlers=[Star, root_handler])

**Comment by Goldziher** [comment]
Ok, @infohash - I dont see any down side to adding a PR for this so feel free to do so.

**Comment by infohash** [comment]
I tested the code without creating copy. It works fine but there must be a design reason behind this at the time of writing the code. Do you remember anything?

**Comment by Goldziher** [comment]
yes, it was meant to ensure there is a degree of encapsulation, i.e. not use the same memory addresses. 

I think we can drop this.

**Comment by infohash** [comment]
It turns out, it has more deep use case than just encapsulation. By creating a copy of the route handler of a controller, you preserve the route ownership of the route handler.

If we don't create copy, all 3 asserts will be true if they are checked like this.
```
first_router = Router(path="/first", route_handlers=[MyController])
assert first_router.routes[0].route_handlers[0].owner.owner is first_router

second_router = Router(path="/second", route_handlers=[MyController])
assert second_router.routes[0].route_handlers[0].owner.owner is second_router

third_router = Router(path="/third", route_handlers=[MyController])
assert third_router.routes[0].route_handlers[0].owner.owner is third_router
```

But if they are checked at the end, only the 3rd assert will be true.

```
first_router = Router(path="/first", route_handlers=[MyController])
second_router = Router(path="/second", route_handlers=[MyController])
third_router = Router(path="/third", route_handlers=[MyController])

assert first_router.routes[0].route_handlers[0].owner.owner is first_router  # False
assert second_router.routes[0].route_handlers[0].owner.owner is second_router  # False
assert third_router.routes[0].route_handlers[0].owner.owner is third_router  # True
```
This is because the 3rd `Router` instance has overwritten the ownership of `MyController`.

Instead of overwriting the ownership by the next `Router` instance, we should preserve make them all as the owner of `MyController` by stopring their ownership as a `list`. Will it cause any issue?

**Comment by Goldziher** [comment]
Yes, it will slow us down. We can't do this.

**Comment by infohash** [comment]
I also noticed there is another problem with resolving path if the copy is not created. The `starlite.router.route_handler_method_view` method will overwrite the key if the same route handler instance is found in multiple route instances.

So I am thinking to do this:

When creating a copy of the route handler instance, also store the source route handler as an attribute.
```python
source_route_handler = cast("BaseRouteHandler", getattr(self, f_name))
route_handler = copy(source_route_handler)
route_handler.owner = self

# Store the source route handler as an attribute.
route_handler._source_route_handler = source_route_handler

route_handlers.append(route_handler)
```

**Comment by Goldziher** [comment]
Let's focus on the purpose of these changes. You want to add the ability to resolve paths from within a controller. Why not simply add a private attribute to the controller that stores this mapping info before the copying and expose a method to access it?
