### ISSUE TITLE
Enhancement: update the `starlite.testing.create_request` utility

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#459]
The `starlite.testing.create_request` utility should be updated to allow setting cookies better, and perhaps to have some other improvements. This might entail replacing the utility with a class and splitting its logic into several methods - because its quite condensed. Furthermore, while doing this we should refactor the test for this utility, which currently uses hypothesis, and instead replace it with proper unit tests - because that test is especially slow.

**Comment by infohash** [comment]
Currently, it takes semicolon separated string as cookies. We can make it to accept a list of `Cookie` instance.

**Comment by Goldziher** [comment]
That would be good

**Comment by seladb** [comment]
@Goldziher are you referring to `starlite.testing.create_test_request`? 🤔

**Comment by Goldziher** [comment]
> @Goldziher are you referring to `starlite.testing.create_test_request`? 🤔

yup

**Comment by seladb** [comment]
Can I assume we want to build something similar to Django's [`RequestFactory`](https://docs.djangoproject.com/en/4.1/topics/testing/advanced/#the-request-factory)?

**Comment by Goldziher** [comment]
> Can I assume we want to build something similar to Django's [`RequestFactory`](https://docs.djangoproject.com/en/4.1/topics/testing/advanced/#the-request-factory)?

By all means

**Comment by peterschutt** [comment]
Closed in #497
