### ISSUE TITLE
Enhancement: Update Test Client

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#460]
We need to enhance the `TestClient` class with methods to easily set / clear authentication headers - i.e., a session cookie or a JWT token header with a specified key.

**Comment by ingjavierpinilla** [comment]
Hi.
I'm a bit confused about this requirement. Do you want a method to set/remove the Middleware from the TestClient?

**Comment by Goldziher** [comment]
> Hi. I'm a bit confused about this requirement. Do you want a method to set/remove the Middleware from the TestClient?

For JWT its simple and we dont need to do anything, basically you set a header. But the `SessionMiddleware` is something we have as part of Starlite. The thing is - in order to create a user session, you basically need to go through the middleware now. 

I was thinking of the way django allows you to "login" a user in the context of tests. Obviously we cannot do the same because we are not an ORM and user management system as well, but what we can do is create a session and send it as part of the request. This is very annoying to do right now because you basically need to serialize the cookie on your own. So I was thinking we might find a way to do this - although I am not sure how feasible it is TBH. @infohash - do you have input on this?

**Comment by infohash** [comment]
A fixture will work.

```python
def mock_asgi_app(scope: "Scope", receive: "Receive", send: "Send") -> None:
    pass

@pytest.fixture()
def session_middleware() -> SessionMiddleware:
    return SessionMiddleware(app=mock_asgi_app, config=SessionCookieConfig(secret=TEST_SECRET))


def create_session(size: int = 16) -> Dict[str, str]:
    return {"key": secrets.token_hex(size)}


@pytest.fixture()
def create_test_cookies(session_middleware) -> str:
    cookies = ';'.join(f"session-{i}={serialize.decode('utf-8')}" for i, serialize in enumerate([b'abc', b'xyz']))
    return cookies

request= create_test_request(cookie=create_test_cookies)

>>> request.cookies
{'session-0': 'abc', 'session-1': 'xyz'}
```

**Comment by infohash** [comment]
I have written the fixtures for it. Will raise the PR soon.

**Comment by infohash** [comment]
@Goldziher Is it fine to keep random data in the fixture to create session cookie or do we need an option for tester to specify what session cookie should contain?

**Comment by Goldziher** [comment]
> @Goldziher Is it fine to keep random data in the fixture to create session cookie or do we need an option for tester to specify what session cookie should contain? In my opinion, the tester doesn't need to care about what session cookie contains while using `create_session_cookie` fixture unless they are specially dealing with the session management. In that case the tester can use `session_middleware` to generate session cookies with his own data instead of using `create_session_cookie` fixture.

Let's go for as simple and straight forward as possible
