### ISSUE TITLE
Simple Post endpoint parameter error "value is not a valid dict"

### ISSUE THREAD

**Issue by smpurkis** [starlite-api/starlite#464]
**Describe the bug**
Summary: Simple POST endpoint server doesn't work using Starlite, but the same setup works in Fastapi.

I'm trying to make a server that accepts a POST request with a parameter. When I try to do it using Starlite I get the error
```
{'detail': 'Validation failed for POST http://127.0.0.1:1234/orders', 'extra': [{'loc': ['page'], 'msg': 'value is not a valid dict', 'type': 'type_error.dict'}], 'status_code': 400}
```

The expected result should be the same as Fastapi. I.e.
```
{'page': 1}
```

The example looks like
Client requests code:
`requests_client.py`
```python
import requests


def get_orders_endpoint():
    resp = requests.post("http://127.0.0.1:1234/orders", json={"number": 1})
    print(resp)
    print(resp.json())


if __name__ == "__main__":
    get_orders_endpoint()
```

In Starlite (run with `uvicorn starlite_server:app --port 1234 --reload`)
`starlite_server.py`
```python
from pydantic import BaseModel
from starlite import Starlite, post


class Page(BaseModel):
    number: int


class Order(BaseModel):
    page: int


@post(path="/orders")
def get_orders(page: Page) -> Order:
    return Order(page=page.number)


app = Starlite(route_handlers=[get_orders])
```

Working Fastapi (run with `uvicorn fastapi_server:app --port 1234 --reload`)
`fastapi_server.py`
```python
from fastapi import FastAPI
from pydantic import BaseModel


class Page(BaseModel):
    number: int


class Order(BaseModel):
    page: int


app = FastAPI()


@app.post("/orders")
def get_orders(page: Page) -> Order:
    return Order(page=page.number)
```

To reproduce:
1. Run server `uvicorn starlite_server:app --port 1234 --reload`
2. Run client request code `python3 requests_client.py`

The version information:
Starlite - 1.17.1
Fastapi - 0.82.0
Requests - 2.28.1
Python - 3.9.9
OS: Ubuntu 20.04 (Linux kernel 5.15.0)

Other:
Code example is adapted from https://starlite-api.github.io/starlite/usage/3-parameters/1-query-parameters/, I also couldn't work out the correct way to pass an `int` as a parameter using requests using Starlite.

**Comment by Goldziher** [comment]
> ```python
> from pydantic import BaseModel
> from starlite import Starlite, post
> 
> 
> class Page(BaseModel):
>     number: int
> 
> 
> class Order(BaseModel):
>     page: int
> 
> 
> @post(path="/orders")
> def get_orders(page: Page) -> Order:
>     return Order(page=page.number)
> 
> 
> app = Starlite(route_handlers=[get_orders])
> ```

Hi @smpurkis - there is no bug here, simply your use is wrong. As we state in the docs: if you want to post data, you have to use the `data` kwarg. Otherwise, if the data is supposed to be sent as query parameter, it should be sent as such.

These two different cases are passing:

```python
from pydantic import BaseModel
from starlette.status import HTTP_201_CREATED

from starlite import post
from starlite.testing import create_test_client


def test_with_data_post() -> None:
    class Page(BaseModel):
        number: int


    class Order(BaseModel):
        page: int


    @post(path="/orders")
    def get_orders(data: Page) -> Order:
        return Order(page=data.number)

    with create_test_client(get_orders) as client:
        response = client.post("/orders", json=dict(number=1))
        assert response.status_code == HTTP_201_CREATED


def test_with_query_param() -> None:
    class Order(BaseModel):
        page: int


    @post(path="/orders")
    def get_orders(number: int) -> Order:
        return Order(page=number)

    with create_test_client(get_orders) as client:
        response = client.post("/orders?number=1")
        assert response.status_code == HTTP_201_CREATED
```

**Comment by smpurkis** [comment]
My mistake, how would I do the same thing as a GET request, as in https://starlite-api.github.io/starlite/usage/3-parameters/1-query-parameters/?

I've tried using a simplified example from that page, and get 400 error, with
```
{'detail': 'Validation failed for GET http://127.0.0.1:1234/orders', 'extra': [{'loc': ['page'], 'msg': 'value is not a valid dict', 'type': 'type_error.dict'}], 'status_code': 400}
```

From that page, it shows no special keywords are required and that the parameter parsing should happen automatically.

`starlite_server.py`
```python
from pydantic import BaseModel
from starlite import Starlite, get


class Page(BaseModel):
    number: int


class Order(BaseModel):
    page: int


@get(path="/orders")
def get_orders(page: Page) -> Order:
    return Order(page=page.number)


app = Starlite(route_handlers=[get_orders])
```

`requests_client.py`
```python
import requests


def get_orders_endpoint():
    resp = requests.get("http://127.0.0.1:1234/orders", json=dict(number=1))
    print(resp)
    print(resp.json())


if __name__ == "__main__":
    get_orders_endpoint()
```

**Comment by smpurkis** [comment]
Aw thanks so much! 
Very helpful and fast responses 🙏

**Comment by Goldziher** [comment]
> Aw thanks so much! 
> Very helpful and fast responses 🙏

You're welcome. Consider joining our discord if you need support .
