### ISSUE TITLE
Enhancement: replace python-multipart with a faster and more stable multipart parser

### ISSUE THREAD

**Issue by h0rn3t** [starlite-api/starlite#466]
python-multipart extremely slow, not maintaining (0.0.5 version released at 12 Oct 2018) and have problems with text files (xml, json, csv etc )

need to swap it to baize or some else 
https://github.com/h0rn3t/starlette-opt/commit/96a7a08b54a24650ad331c4f812659609e7a1494

**Comment by Goldziher** [comment]
Are there any benchmarks to support this?

**Comment by h0rn3t** [comment]
25mb xml  in form-data (python-multipart) = 1-2 min parsing (some problems internal problem in parsing algorithm )
25mb xml in form-data (baize) patched starlette = 6 seconds

**Comment by h0rn3t** [comment]
BTW im not first who ask to swap this old python-multipart library, also the code of that lib not so good

**Comment by Goldziher** [comment]
@peterschutt @cofin @infohash -- what do you think?

I looked at Baize and the multipart implementation does look good. I am concerned though adding this dependency into the project - its not modular and we are going to get some annoying import issues. I opened an issue in their github -> https://github.com/abersheeran/baize/issues/47

An alternative would be to fork either baize or the python multipart and create our own smaller implementation.

@h0rn3t - how interested are you in contributing to this?

**Comment by peterschutt** [comment]
Plenty of prior art out there to guide us in implementing ourselves. 

Flask and Quart both use [werkzeug.sansio.multipart](https://github.com/pallets/werkzeug/blob/main/src/werkzeug/sansio/multipart.py) and the baize implementation seems to be just a copy of that. Falcon, sanic and django all roll their own implementations as well.

**Comment by Goldziher** [comment]
Aight, I'll check this out. Might be an interesting case

**Comment by abersheeran** [comment]
> 25mb xml in form-data (python-multipart) = 1-2 min parsing (some problems internal problem in parsing algorithm ) 25mb xml in form-data (baize) patched starlette = 6 seconds

I didn't even think I could be so fast...thanks mypyc


> Plenty of prior art out there to guide us in implementing ourselves.
> 
> Flask and Quart both use [werkzeug.sansio.multipart](https://github.com/pallets/werkzeug/blob/main/src/werkzeug/sansio/multipart.py) and the baize implementation seems to be just a copy of that. Falcon, sanic and django all roll their own implementations as well.

Yes, it's better to build the parser in starlite, which means some targeted optimizations can be made. The multipart format is an old, stable construct that requires little maintenance once the code is written.

**Comment by artyom-ace** [comment]
I met with the problem of long file uploads too. And it was connected to the old python-multipart library. I was surprised that such an old library without proper support for async is still used in fastapi (using many dependencies from Starlette)

**Comment by Goldziher** [comment]
I started work on a library to handle this. I will be using Werkzeug as a basis.

**Comment by abersheeran** [comment]
> I met with the problem of long file uploads too. And it was connected to the old python-multipart library. I was surprised that such an old library without proper support for async is still used in fastapi (using many dependencies from Starlette)

https://github.com/encode/starlette/pull/1514#issuecomment-1041362805

**Comment by h0rn3t** [comment]
strange that so old and bad implemented parser used  by cool  innovative frameworks like starlite, fastapi, starlette

**Comment by h0rn3t** [comment]
> > I met with the problem of long file uploads too. And it was connected to the old python-multipart library. I was surprised that such an old library without proper support for async is still used in fastapi (using many dependencies from Starlette)
> 
> [encode/starlette#1514 (comment)](https://github.com/encode/starlette/pull/1514#issuecomment-1041362805)

bad that  starlette guys closed the issue without solution :(

**Comment by Goldziher** [comment]
@h0rn3t -- I created a package, adapting werkzeug and using your PR to starlette as a basis. See: https://github.com/starlite-api/starlite-multipart

Would you like to get involved?

**Comment by Goldziher** [comment]
PR added

**Comment by Goldziher** [comment]
v1.18.0 released with this update. 

@h0rn3t - you're welcome to test it.

I am adding you for code contributions, since I incorporated some of your code in there.

@all-contributors add @h0rn3t code

**Comment by h0rn3t** [comment]
@Goldziher  cool , okay I will
