### ISSUE TITLE
How should contributors check test coverage locally?

### ISSUE THREAD

**Issue by jonadaly** [starlite-api/starlite#484]
In `CONTRIBUTING.md`, we are told that 100% coverage is mandatory on any code we touch.

There are no instructions for how to check test coverage locally, and I can't see any straightforward way of checking with existing tooling - it seems like first we need to raise a PR before we can see via SonarCloud whether this coverage requirement is met.

I can check coverage locally by copying commands from the CI config, and changing it to output nice human-readable things rather than XML - but it might be worth either updating the contribution guidelines with details on how to check coverage locally, or updating `tox.ini` itself to include a coverage check that outputs to the terminal.

Alternatively, if checking via SonarCloud is the preferred method, perhaps this could be made clearer in the contribution guidelines.

**Comment by Goldziher** [comment]
You can run pytest with coverage: 

```shell
poetry run pytest tests examples --cov=.
```

You can also run pytest using your IDE of choice. I use intellij, and coverage is builtin there.

**Comment by jonadaly** [comment]
Yep that's what I ended up doing - my suggestion would be either to add this to `CONTRIBUTING.md`, or to include the coverage check in tox.ini (or both!)

It might also be worth enforcing a minimum coverage level as part of `poetry run tox`?

**Comment by Goldziher** [comment]
You're welcome to submit a PR with this update to the guidelines 🙃
