### ISSUE TITLE
BUG: openapi docs break where two pydantic models have the same name

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#488]
**Describe the bug**
Using a domain-centric app pattern, I'll have a single module or sub-package specific to a domain element and within that namespace have a set of common tools, all named consistently, e.g., `books.Service`, `books.Model`, `books.Schema`, and `authors.Service`, `authors.Model`, `authors.Schema`, etc. I prefer to have all components for a type grouped together rather than having `services.Books`, `services.Authors`, `models.Books`, `models.Authors` etc.

**To Reproduce**
Run this example: https://github.com/starlite-api/starlite-hello-world/tree/domain-scoped-models

`$ poetry install`
`$ poetry run uvicorn app.main:app`

Then navigate to `localhost:8000/schema`.

**Additional context**

Redoc stacktrace:

![image](https://user-images.githubusercontent.com/20659309/190681275-34f01f49-a12a-4800-9423-19cb1ad19c48.png)

Notice the schema names get scoped with their path, e.g., `app__domain__authors__Model`, yet the `$ref` for the paths is `                $ref: '#/components/schemas/Model'`

```yaml
components:
  schemas:
    app__domain__authors__Model:
      properties:
        dead:
          title: Dead
          type: boolean
        name:
          title: Name
          type: string
      required:
      - name
      - dead
      title: Model
      type: object
    app__domain__books__Model:
      properties:
        genre:
          title: Genre
          type: string
        name:
          title: Name
          type: string
      required:
      - name
      - genre
      title: Model
      type: object
info:
  title: Starlite API
  version: 1.0.0
openapi: 3.1.0
paths:
  /authors:
    get:
      deprecated: false
      operationId: Get Authors
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
          description: Request fulfilled, document follows
          headers: {}
  /books:
    get:
      deprecated: false
      operationId: Get Books
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
          description: Request fulfilled, document follows
          headers: {}
servers:
- url: /
```

My workaround has been to instantiate the model with a unique name and then alias it:

```python
# domain/authors.py

class Author(BaseModel): ...

Model = Author
```

**Comment by Goldziher** [comment]
why are you reusing the namespaces?

**Comment by peterschutt** [comment]
Do you mean why do I reuse names like `Model`? Grouping components by namespace is my preferred pattern. The example is obviously quite simplistic, however as applications grow, it is nice to have the consistency.

Not sure if I've answered your question though.

**Comment by peterschutt** [comment]
Maybe this is more of a pydantic-openapi-schema issue??

**Comment by Goldziher** [comment]
> Maybe this is more of a pydantic-openapi-schema issue??

I'm pretty sure it is technically. 

How about we add support to some special `ClassVar` - `__schema_name__` for example. Pydantic ignores it, and we can use this value to allow the user to customize the schema key.

**Comment by peterschutt** [comment]
I really have no idea how to approach it. I've been sitting on the issue for a while cause my workaround has been fine and I haven't had the time to dig into it. So I'll take whatever solution you think is viable for a spin.

I always had the pydantic schema customization hook in the back of my mind, but no idea if I could actually make it work:

```python
from typing import Any
from pydantic import BaseModel


class Person(BaseModel):
    name: str
    age: int

    class Config:
        @staticmethod
        def schema_extra(schema: dict[str, Any], model: type['Person']) -> None:
            for prop in schema.get('properties', {}).values():
                prop.pop('title', None)


print(Person.schema_json(indent=2))
```
