### ISSUE TITLE
Refactor: LoggingConfig to Use Class Inheritence

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#493]
The introduction of more complexity into the logging config class - for piccologing and now also for rich-logging and the new logging middleware (see #475 and #462 ) - makes the config class bloated and unwieldiy. We need to come up with a better strategy to handle the logging configuration, while making it simple for both users and contributors to get access to a configured logger (using for example `logging.getLogger`).

My proposal is to use class inheritence to simply this. We can have one base `LoggingConfig` class and then subclasses of it. We can then have the Starlite constructor (read `__init__`method) receive this config or any of its subclasses, call it during the app bootstrap etc. 

We should make sure that the logging config can be easily subclassed and extended - and decouple any middlewares from the config class itself. I.e. we should follow SOLID here and ensure that the logging config does only one thing - configure logging.

**Comment by Goldziher** [comment]
@cofin @john-ingles @Swannbm - please add your input.

**Comment by john-ingles** [comment]
Perhaps we should abstract further and instead of using a base class LoggingConfig and subclasses we should instead make and abstract base class for LoggingConfig and have various implementations of it.

**Comment by Goldziher** [comment]
there is still the logging config structure to share, no?

**Comment by john-ingles** [comment]
@Goldziher What exactly do you mean?

**Comment by Goldziher** [comment]
We dont need an asbtract class if a base implementation should already do something. I.e., all configurations have a shared strucure - i assume. Am i missing something?

**Comment by john-ingles** [comment]
Perhaps and abc isn't the way to go but I'm still worried about the possibility of a combinatorial explosion of Logging subclasses in the future.  For now there would be

1. LoggingConfig
2. RichLoggingConfig
3. RichPicologgingConfig
4. StructlogLoggingConfig
5. StructlogPicologgingConfig

If we wanted to add other logging integrations it could get worse.  I'm just suggesting if there is a different pattern we can use to promote composition over inheritance?  Maybe decorators or mixins like django?

**Comment by Goldziher** [comment]
Can you show me examples?

**Comment by john-ingles** [comment]
Mixins could be used to modify the configure method like so:

```python
class PicologgingMixin:
    def configure(self):
        picologging_config.dictConfig(self.dict(exclude_none=True))

class LoggingConfig(PicologgingMixin, BaseModel):
    ...
    # attributes
    ....
    def configure(self):
        logging.dictConfig(self.dict(exclude_none=True))
```

It might be more trouble than it's worth though.  I'm struggling to come up with an elegant way to incorporate rich or structlog that favors composition.  There might be a way to do it by having subclasses only define a new attribute that passes a list of functions to be applied to the attributes of the base class when calling configure.  Functions that modify the handlers, filters, and formatters attributes for instance.  Then we would define these functions somewhere else with names like use_rich_handler, use_structlog_handler, etc.

```python
class PicologgingMixin:
    def configure(self):
        log_config_dict= self.dict(exclude_none=True)
        for mod in modifiers:
            log_config_dict= mod(log_config_dict)
        picologging_config.dictConfig(log_config_dict)

RICH_FORMATTER = {"format": "%(name)s - %(message)s"}

def use_rich_logging(log_config_dict):
    """change what is needed to use rich"
    log_config_dict["formatters"]["rich"] = RICH_FORMATTER
    log_config_dict["handlers"].pop("console", None)
    log_config_dict["handlers"]["p_rich"] = {
        "class": "rich.logging.RichHandler",
        "level": "DEBUG",
        "rich_tracebacks": True,
        "formatter": "rich",
    }
    if "cfg://handlers.console" in log_config_dict["handlers"]["queue_listener"]["handlers"]:
        log_config_dict["handlers"]["queue_listener"]["handlers"].remove("cfg://handlers.console")

    log_config_dict["handlers"]["queue_listener"]["handlers"].append("cfg://handlers.p_rich")
    return log_config_dict

# What we or the user makes
class RichPicoLoggingConfig(PicologgingMixin, LogConfig):
    """Inherits all attributes from LogConfig.  Uses Picologging in configure method"
    modifiers: List[Callable] = [use_rich_logging]

logging_config = RichPicoLoggingConfig()
logging_config.configure()
```

Again, it might be more trouble than it's worth.

**Comment by john-ingles** [comment]
@Goldziher  Any comment on the above?

**Comment by Goldziher** [comment]
So, I decided against this approach. I updated the logging config to handle the logic better, and I am updating the app to receive a logging config: https://github.com/starlite-api/starlite/pull/511
