### ISSUE TITLE
Update SQLAlchemy plugin

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#521]
Our update to the plugin protocol allows us to include an optional layer in the plugin - 

I suggest we add option constructor args, that allows the user the establish a connection, inject a db session etc. This can be as a separate package or by making the plugin a contrib module.

**Comment by cofin** [comment]
I'm thinking we should do the same for the Redis cache backend.

**Comment by Goldziher** [comment]
there is no redis cache backend at present. You want to add a plugin for it?

**Comment by Goldziher** [comment]
> yes, correct. I should have said "a Redis cache backend" instead of the "the Redis cache backend". I'll create a new issue with the feature request later this evening. Re: this one, I think we absolutely need this.
> 
> Do you think we should limit the supported backends to be asnycio engines only or no?

i think so, yes.
