### ISSUE TITLE
Update RequestFactory

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#524]
This is a followup issue.

We should update the RequestFactory in the following:

1. extend the scope generation to support most things we define in the scope type (see `starlite.types.asgi_types`)
2. add documentation in the usage/testing docs regarding how to use this.

**Comment by seladb** [comment]
@Goldziher I looked into everything we have in `scope` and is being used in starlite's `Request` and `ASGIConnection`. Here are properties I can add:
- `state: Dict[str, Any]`
- `client: Tuple[str, int]`
- `route_handler: "RouteHandlerType"`

The following keys are in `scope` but are not being used anywhere in starlite's request object, hence I don't think we should add them:
- `asgi: ASGIVersion`
- `http_version: str` (I checked in Starlette and it is always set to a const value of `1.1`)
- `raw_path: bytes`
- `extensions: Dict[str, Dict[object, object]]`

There is also `path_params: Dict[str, str]` which is created from the request path, but it's not easy to parse and I don't think it adds much value, so I don't think we should add it.

Please let me know what you think. I'll work on this in the coming days.

**Comment by Goldziher** [comment]
So, the scope object actually originates from the ASGI server (uvicorn, daphne etc.). If the user uses an ASGI server that supports HTTP2, such as `hypercorn`, then `http_version` will be `2.0`. In the future there might be `3.0` versions etc. So its good to have it. 

`raw_path` should equal path - only in bytes. it shouldnt be passed in. 

`extensions` are specified by the ASGI specification, this is a value passed by the ASGI server - again. The only place we use it is for `push promise` - which is undocumented currently. Still, users might have use cases for this - although its true this is really marginal and we dont need to cater to this. 

`path_params` - yes, its not easy to set at all - but maybe allow users to set the value, otherwise default it to an empty dict.
