### ISSUE TITLE
Feature: validator for `data` kwarg separate to injected type

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#547]
I'd like to discuss whether it is possible to have a different parser/validator for body input than the object that it is injected.

General idea:

```python
# sqlalchemy declarative class
class Thing(Base):
    id: Mapped[UUID]
    name: Mapped[str]
    created: Mapped[datetime]
    updated: Mapped[datetime]

dto_factory = DTOFactory(plugins=[SQLAlchemyPlugin()])

ThingUpdateDTO = dto_factory("ThingUpdateDTO", Thing, exclude=["created", "updated"])

@put("/{thing_id:uuid}", body_validator=ThingUpdateDTO)
async def update_thing(data: Thing) -> Thing:
    """
    The request body would be parsed and validated by ThingUpdateDTO, and then used to instantiate a 
    `Thing` for injection as `data`.
    """
    print(data.__dict__)  # {"id": "xxx", "name": "xxx", "_sa_instance_state": ...}
    return data
```

Possibly even something similar for handler return values?

**Comment by peterschutt** [comment]
> Well, the above example will fail because created and updated are typed as required values.

The sqlalchemy class will instantiate without them present, they might have a db server generated default value or a value set after instantiating.

Look at value of `data.__dict__` in the handler. The missing values are simply not set as an attribute, but the instance instantiates fine.

Missing values are resolved during either merging the transient representation to an existing persistent instance in the session, or via adding the transient instance to the session and flushing to the database. In the latter case, defaults will either be applied by sqlalchemy on the way in, or by server-side defaults.

> Whats the use cast this is supposed to address that the existing design fails to?

Using the sqlalchemy plug-in, I can have a single model represent the domain type, but I don't always want every attribute modifiable by clients, eg, `created` timestamp. This allows using the sqlalchemy model as the domain type, and DTO factories to create pydantic models that specifically represent the allowed interface for given routes.

It also would allow using the DTOs in a manner that is not subject to static typing problems.

**Comment by peterschutt** [comment]
> In fact - created and updated are optional.

It's a bit of a grey area.

```python
author = Author()
author.name = None
```

Type checks as:

```
app/domain/authors.py:19: error: Incompatible types in assignment (expression has type "None", variable has type "Union[SQLCoreOperations[str], str]")  [assignment]
Found 1 error in 1 file (checked 43 source files)
```

However accessing the property on the instance does indeed return `None` if it hasn't been set:

```python-console
>>> from app.domain.authors import Author
>>> author = Author()
>>> type(author.name)
<class 'NoneType'>
>>> author.__dict__
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7fb1560e0520>}
```

I know I've read SQLAlchemy author comments on that behavior down the years, but it's pretty immaterial - it is the way it is.

**Comment by peterschutt** [comment]
How about a way to have more control over the DTO that the SQLAlchemy plugin generates per route?

Could there be a way to have `SQLAlchemyPlugin.to_pydantic_model_class()` accept some configuration from the route, so that the DTO it generates can be tailored to the individual route. Maybe through including some info in `opt`?

l'd like to press this idea further by incorporating a separate generated DTO for route return, but lets start with the above and see if that's feasible.

**Comment by Goldziher** [comment]
> > In fact - created and updated are optional.
> 
> It's a bit of a grey area.
> 
> ```python
> author = Author()
> author.name = None
> ```
> 
> Type checks as:
> 
> ```
> app/domain/authors.py:19: error: Incompatible types in assignment (expression has type "None", variable has type "Union[SQLCoreOperations[str], str]")  [assignment]
> Found 1 error in 1 file (checked 43 source files)
> ```
> 
> However accessing the property on the instance does indeed return `None` if it hasn't been set, but doesn't actually set `None` as an attribute value for that property.
> 
> ```
> >>> from app.domain.authors import Author
> >>> author = Author()
> >>> type(author.name)
> <class 'NoneType'>
> >>> author.__dict__
> {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7fb1560e0520>}
> ```
> 
> I know I've read SQLAlchemy author comments on that behavior down the years, but it's pretty immaterial - it is the way it is.

Ok, but I dont see how we can translate this into something we can do here. The solution really is to use a DTO for this. What solution to you propose? a validator separate from the `data` value is not going to cut it - its a lot of extra complexity, and its going to significantly degrade performance I believe - and in the end, the behaviour of SQLAlchemy is actually not reflected in its typing. The problem is the types i think - not us.

**Comment by peterschutt** [comment]
Have got a DTO based solution in the example app now, and TBH I'm happy with it.

Now that mypy allows to disable specific errors per directory, I've just silenced the `valid-type` errors for the `controllers` sub-package:

```ini
[mypy-app.controllers.*]
disable_error_code = valid-type
```

I also had to disable the pydantic plugin (it was crashing) - but aside from the calls to `Base.from_dto()` and `DTO.from_orm()` I'm not interacting directly with pydantic models anywhere in the app anyway.
