### ISSUE TITLE
Feature: Add TestClient.add_session_cookies() method

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#557]
See #555 for context.

httpx are deprecating setting cookies per request, e.g,. `client.get(..., cookies=...)`.

We now have some code in our test suite like this:

```python
    with TestClient(app=app, session_config=session_config if enable_session else None) as client:
        client.cookies = client.create_session_cookies(session_data=session_data)
        client.get("/test")
        assert app.state.value == 1
```

We could add a method `add_session_cookies()`, so the pattern would become:

```python
    with TestClient(app=app, session_config=session_config if enable_session else None) as client:
        client.add_session_cookies(session_data=session_data)
        client.get("/test")
        assert app.state.value == 1
```

**Comment by infohash** [comment]
I see.

```python
client.cookies = client.create_session_cookies(session_data=session_data)
```

This code is only required if the user wants to overwrite cookies. The cookies should not be updated outside of session middleware because the raw session cookies must match with the data present in scope["session"].

**Comment by peterschutt** [comment]
So just forget about all this?

**Comment by infohash** [comment]
I think so. I'll wait for @Goldziher view on it.

**Comment by peterschutt** [comment]
It can be reopened.
