### ISSUE TITLE
Default name in handler index is not unique

### ISSUE THREAD

**Issue by jtraub** [starlite-api/starlite#567]
**Describe the bug**
Default name for route handlers might be not unique.

[Here](https://github.com/starlite-api/starlite/pull/541#discussion_r987565608) we decided to use `handler.fn.__qualname__` as default name in handler index but today I learned the hard way that `__qualname__` is not unique if your route handlers are functions with the same name located in different files. Sorry, I didn't check python docs carefully to make sure that picked named would be unique.

Easy repro
```
/tmp/test 
> cat a.py 
def create():
    pass

/tmp/test 
> cat b.py 
def create():
    pass

/tmp/test 
> python
Python 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from a import create as create_a
>>> from b import create as create_b
>>> create_a.__qualname__
'create'
>>> create_b.__qualname__
'create'
>>> 
```

Django uses `func.__module__ + "." + func.__qualname__' for similar purposes as can be see [here](https://github.com/django/django/blob/974942a75039ba43e618f6a5ff95e08b5d5176fd/django/contrib/admindocs/utils.py#L22)

I tried it https://github.com/starlite-api/starlite/compare/main...jtraub:starlite:fix_default_name_in_index and it works fine for my case.
Maybe "internal" method `app._get_handler_qualname` should be moved to utils so the user can import and use it - at the moment I ha to duplicate the code in my app

**Comment by Goldziher** [comment]
yup

**Comment by Goldziher** [comment]
I added a PR fixing this, you're welcome to review @jtraub
