### ISSUE TITLE
Documentation: Update the migration guide

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#597]
Our docs now have a rather basic migration guide. It would be very helpful to have this updated. If need be, we can split it by different frameworks, so a migration guide from `FastAPI`, from `Starlette` and any other framework that users want to migrate from. 

This is an open "permanent" issue, so feel free to add PRs refering to it - it will not be closed in the near future.

**Comment by provinzkraut** [comment]
Ideally this would include a comparison table for equivalent constructs.

Something like
| Flask                                                                          | Starlite                                                                 |
|--------------------------------------------------------------------------------|--------------------------------------------------------------------------|
| <pre>@app.route("/")<br>def hello_world():<br>    return "Hello, World!"</pre> | <pre>@get("/")<br>def hello_world():<br>    return "Hello, World!"</pre> |
| Blueprints                                                                     | Controllers / Routers                                                    |
| `@app.before_request`                                                          | `get("/", before_request=...)` / `Starlite(before_request=...)` etc.     |
| flask-sqlalchemy                                                               | SQLAlchemyPlugin                                                         |
