### ISSUE TITLE
Bug: Picologging not behaving correctly 

### ISSUE THREAD

**Issue by nielsvanhooy** [starlite-api/starlite#609]
**Describe the bug**
i reported an earlier issue to @peterschutt about logging configuration not visible in the console output.
that was fixed in https://github.com/starlite-api/starlite/pull/594

i now wanted to test this out with picologging but it seems to override the LoggingConfig settings.

**To Reproduce**
checkout https://github.com/starlite-api/starlite-pg-redis-docker    and add picologging to the application.
then you see the behaviour i describe here.

nothing else changes so only add picologging.

**Additional context**
you can see the behaviour already at starting the project with docker-compose up.

without picologging in project:

app_1      | Starting Starlite App...
app_1      | INFO:     Will watch for changes in these directories: ['/app']
app_1      | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
app_1      | INFO:     Started reloader process [10] using WatchFiles
app_1      | INFO:     Started server process [12]
app_1      | INFO:     Waiting for application startup.
app_1      | 2022-10-16 18:38:14,888 loglevel=INFO   logger=uvicorn.error serve() L75   Started server process [12]
app_1      | 2022-10-16 18:38:14,888 loglevel=INFO   logger=uvicorn.error startup() L47   Waiting for application startup.
app_1      | INFO:     Application startup complete.
app_1      | 2022-10-16 18:38:14,908 loglevel=INFO   logger=uvicorn.error startup() L61   Application startup complete.

with picologging in project:

app_1      | Starting Starlite App...
app_1      | INFO:     Will watch for changes in these directories: ['/app']
app_1      | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
app_1      | INFO:     Started reloader process [10] using WatchFiles
app_1      | INFO:     Started server process [12]
app_1      | INFO:     Waiting for application startup.
app_1      | INFO:     Application startup complete.

i tried looking at the documentation of picologging https://microsoft.github.io/picologging/handlers.html   section Queue Listener but it seems to be correct. at this point im lacking knowledge in the logging department to troubleshoot this deeper.

Kind regards,
Niels

**Comment by Goldziher** [comment]
hmpf. I really screwed this stuff up it seems.

**Comment by Goldziher** [comment]
fixing now

**Comment by peterschutt** [comment]
Sorry, I should have plugged the example app into the fix branch and tested this more thoroughly.

Looks like the app output is duplicating log messages too @nielsvanhooy, one formatted, and one unformatted. That'll either be a problem with the config in the example app, or the config you are using in your version of it. I'll check that out soon.

**Comment by peterschutt** [comment]
@nielsvanhooy I just pushed updates to example app that remove the duplicated uvicorn log messages and update the starlite version
