### ISSUE TITLE
Minimal example doesn't run because of incorrect import

### ISSUE THREAD

**Issue by philvarner** [starlite-api/starlite#61]
In the minimal example: https://starlite-api.github.io/starlite/#minimal-example

The Controller (my_app/controllers/user.py) imports the model with

```
from my_app.models import User
```

This fails to startup with:

```
ImportError: cannot import name 'User' from 'my_app.models' (unknown location)
```

because the User class is defined in:

```
my_app/models/user.py
```

This would work if there were a __init__.py file in my_app/models that imports all the model classes (as there is for the backend-starlite-postgres), but this isn't in the minimal example. 

To fix, the import should be:

```
from my_app.models.user import User
```

It would also be nice if this code were in a standalone template repo to clone and use, instead of cutting and pasting it out of the docs.

**Comment by Goldziher** [comment]
Well, TBH its not meant to be a viable example with all the files included - there is an assumption there that python pacakges are in place etc. 

We have an example project in the works, the problem is that its not finished yet.

**Comment by philvarner** [comment]
The example project would be great. My point was more that it's *almost* a viable example if it just used explicit imports rather than relying on the package-level init imports that don't exist. Totally fine if it's not intended to be.

**Comment by Goldziher** [comment]
You can check this out- https://github.com/lesnik512/starlite-sqlalchemy-template
