### ISSUE TITLE
Redirect on authentication error

### ISSUE THREAD

**Issue by jjgalvez** [starlite-api/starlite#627]
**What's the feature you'd like to ask for.**
A clear and concise description of what this feature does, improves and / or solves. Include code snippets or examples if applicable.

When using authentication within web-browser based applications, it would be convenient for the application to redirect to the login page rather than displaying the 401 error. 

**Additional context**

The following code accomplishes this:

```
def auth_redirect_handler(request: Request, exc: Exception) -> RedirectResponse:
    '''
    Exception handler to capture 401 errors and redirect to /login
    '''
    status_code = HTTP_401_UNAUTHORIZED
     return RedirectResponse(url=request.url_for('login'), status_code=307)
```

and in my app adding:
`exception_handlers={HTTP_401_UNAUTHORIZED: auth_redirect_handler}`

**Comment by infohash** [comment]
If starlite is made to do it by default, it will send redirect response even to the request sent by REST API clients. So this is left on the user to decide. Besides, once `starlite-oidc` extension is ready for production, it will have this functionality by default for the web apps, not only that, `starlite-oidc` will redirect you to the login page of the identity provider and back to the same page where the user was redirected from to maintain continuity.

**Comment by Goldziher** [comment]
Its easy enough to do with a custom middleware as is - simply set the logic in the `__call__` method of the middleware and you can redirect there.
