### ISSUE TITLE
Replace starlette.datastructures.Headers and other MultiDict-like structures with aio-libs/multidict

### ISSUE THREAD

**Issue by jtraub** [starlite-api/starlite#640]
As a part of migration from Starlette we should replace `starlette.datastructures.Headers`, `starlette.datastructures.MutableHeaders` and `starlette.datastructures.ImmutableMultiDict` with another multidict implementation.

Proposed library is  [multidict](https://github.com/aio-libs/multidict)

Convenient usage list for mentioned classes can be found in #634 

Related issue in starlite-multipart tracker - https://github.com/starlite-api/starlite-multipart/issues/5

**Comment by Goldziher** [comment]
It occurs to me we can create our own version using https://docs.python.org/3/library/collections.html#collections.ChainMap

This has the advantage if being both fast and a builtin. It's not a multidict, but we can use it as a basis. 

Thoughts?

**Comment by provinzkraut** [comment]
We could, but I'm not sure if we should. I don't think it's that fast, certainly not faster than the proposed multidict. And we'd have to add most of the implementation, not sure if there's really any benefit to using `ChainMap` here really (or maybe you have some genius idea on how to do that, that I just can't see? :upside_down_face: If so, please do share!).

**Comment by Goldziher** [comment]
> We could, but I'm not sure if we should. I don't think it's that fast, certainly not faster than the proposed multidict. And we'd have to add most of the implementation, not sure if there's really any benefit to using `ChainMap` here really (or maybe you have some genius idea on how to do that, that I just can't see? :upside_down_face: If so, please do share!).

Nothing genius I'm afraid. Let's stick with multidicting This

**Comment by provinzkraut** [comment]
I had this on my plate already, unless @jtraub wants to take this on I'd take care of it in the following days?

**Comment by provinzkraut** [comment]
Implemented in #732
