### ISSUE TITLE
Enhancement: Replace BaseHTTPMiddleware with a starlite implementation

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#642]
As part of the migration from Starlette #612 we should replace the `starlette.middleware.BaseHTTPMiddleware` that appears in our docs with our own implementation.

**Comment by Goldziher** [comment]
I am not 100% sure we should actually support this -- thoughts?

**Comment by provinzkraut** [comment]
Why shouldn't we support it? It's a valid use case IMO. If a middleware should be more than a simple callable but doesn't want to deal with ASGI directly either, it's quite useful.

**Comment by Goldziher** [comment]
> Why shouldn't we support it? It's a valid use case IMO. If a middleware should be more than a simple callable but doesn't want to deal with ASGI directly either, it's quite useful.

Ok, but in that case we can have a better implementation than this - maybe something like Django's, where you can specify the request side and response side.

**Comment by odiseo0** [comment]
I think a simple decorator will work fine for most commons use cases

```py
@middleware
def my_middleware(*args, **kwargs):
    ...
```
It may be too simplistic tho

**Comment by Goldziher** [comment]
> I think a simple decorator will work fine for most commons use cases
> 
> ```py
> @middleware
> def my_middleware(*args, **kwargs):
>     ...
> ```
> It may be too simplistic tho

That's pretty cool TBH

**Comment by provinzkraut** [comment]
So something like starlettes [`Starlette.middleware`](https://github.com/encode/starlette/blob/master/starlette/applications.py#L262) decorator, just not bound to the app instance.

I like the idea!

**Comment by Goldziher** [comment]
ok, we agreed not to include `BaseMiddleware` in Starlite - this is a starlette feature, if its required by users they can either vendor it from Starlette, or simply have Starlette as a dependency. We will ensure we are compatible with it though.
