### ISSUE TITLE
Enhancement: Versioned docs

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#650]
### Discussed in https://github.com/starlite-api/starlite/discussions/649

<div type='discussions-op-text'>

<sup>Originally posted by **jtraub** October 23, 2022</sup>
Starlite evolves at a quite fast pace. The problem here is that Starlite version in user project can lag multiple releases behind while documentation at https://starlite-api.github.io/starlite/ is being regenerated on each commit to the main branch. This might be the source of confusion when the docs say about some new feature that is not available in a version that is available to the user.

Should we start docs versioning so user can view docs about their version? Material for MkDocs supports it
https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/

The problem here seems to be repository size and Github Pages limits. I have no idea about docs size nor about Github limits but I think we can work something out. Even keeping docs for last 10 versions looks like an improvement.</div>

**Comment by provinzkraut** [comment]
GitHub page recommends a maximum size of 1GB.
https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits

With a current size of ~20MB we can fit about 50 versions.

If we exceed that, maybe ditch older versions (which is kinda meh IMO), or move away from GH pages?

**Comment by pemocarlo** [comment]
I would say that we do not need to keep all the version docs. The most important is to show the ones that are actively supported (which in Starlite case is only the latest one) and the unreleased version. Maybe also keep longer the ones with an important milestone (like before dropping a Python version). Where I actually see the biggest value here is to differentiate between the unreleased and latest version. Even if the release cadence is very high, the docs are still updated on each pull request, and it is then possible that some users are confused by unreleased features.

**Comment by provinzkraut** [comment]
I think we definitely need them to some extend. People might not be able to update immediately because of their own release cycle or interdependent packages, so they could be stuck with a version that has no appropriate documentation available anymore.

**Comment by pemocarlo** [comment]
An alternative is to add a note in the relevant section of the docs, indicating the most important changes in each version, similar to the python docs:

![Screenshot from 2022-10-23 18-11-14](https://user-images.githubusercontent.com/7297323/197403172-e9cd6e4d-40b5-4d09-9fc3-c676ba43d7cb.png)

But I guess this requires a more involved effort from the contributors. Maybe it would be possible to automate by extracting this information from the git history, but it might be a bit too complex.

**Comment by pemocarlo** [comment]
> I think we definitely need them to some extend. People might not be able to update immediately because of their own release cycle or interdependent packages, so they could be stuck with a version that has no appropriate documentation available anymore.

Maybe we can limit this to the last 5 or 10 minor versions, for example. For more special changes, there is always the possibility to regenerate the docs from the git history, even if not ideal XD

**Comment by peterschutt** [comment]
I'm currently experimenting with https://github.com/jimporter/mike in another project. It is used by https://github.com/awslabs/aws-lambda-powertools-python - see the version selector on their docs: https://awslabs.github.io/aws-lambda-powertools-python/2.0.0/

**Comment by provinzkraut** [comment]
@peterschutt What are your findings? I think it looks good from what I can tell, so unless you found some major drawbacks I'll say we go ahead an implement this.

**Comment by provinzkraut** [comment]
Implemented in #996
