### ISSUE TITLE
[BUG] cannot add routes to starlite

### ISSUE THREAD

**Issue by alf1e** [starlite-api/starlite#680]
**Describe the bug**
When adding any route handler complains route is already registered.

**To Reproduce**
Explain how to reproduce the bug.

[backend.zip](https://github.com/starlite-api/starlite/files/9854603/backend.zip)
download the code
Run `pip3 install -e .`
Run `SQLA_KEY="sqlite+aiosqlite:///:memory:" python3 src/__init__.py`

**Additional context**
Error is `starlite.exceptions.http_exceptions.ImproperlyConfiguredException: 500: Router with path /v0 has already been registered`

**Comment by Goldziher** [comment]
hi, can you paste code here or link the reproduction repo?

**Comment by alf1e** [comment]
> hi, can you paste code here or link the reproduction repo?

I attached a ZIP of it

**Comment by Goldziher** [comment]
This is what I meant:

```python
import uvicorn
from starlite import Starlite, Router, Controller, get

class PingController(Controller):
    path = "/ping"

    @get()
    def ping_message(self) -> dict:
        return {"message": "Pong!"}


router = Router(
    path="/v0",
    route_handlers=[
        PingController
    ]
)


app = Starlite(
    route_handlers=[
        router
    ],
)
for i in app.routes:
    print(i.path_components)

if __name__ == "__main__":
    uvicorn.run(
        app=app,
        host="0.0.0.0",
        log_level="debug",
        port=443,
        timeout_keep_alive=0,
    )
```

Look, im glad to help - but opening random zips from the internet is insecure and aside from that you didn't offer a minimum reproduction.

Running this works fine.

**Comment by alf1e** [comment]
> This is what I meant:
> 
> ```python
> import uvicorn
> from starlite import Starlite, Router, Controller, get
> 
> class PingController(Controller):
>     path = "/ping"
> 
>     @get()
>     def ping_message(self) -> dict:
>         return {"message": "Pong!"}
> 
> 
> router = Router(
>     path="/v0",
>     route_handlers=[
>         PingController
>     ]
> )
> 
> 
> app = Starlite(
>     route_handlers=[
>         router
>     ],
> )
> for i in app.routes:
>     print(i.path_components)
> 
> if __name__ == "__main__":
>     uvicorn.run(
>         app=app,
>         host="0.0.0.0",
>         log_level="debug",
>         port=443,
>         timeout_keep_alive=0,
>     )
> ```
> 
> Look, im glad to help - but opening random zips from the internet is insecure and aside from that you didn't offer a minimum reproduction.
> 
> Running this works fine.

Sorry. Yes it does work in one but when I split it into multiple files it dosent work.

**Comment by jtraub** [comment]
> Sorry. Yes it does work in one but when I split it into multiple files it dosent work.

Change `from src.routes.v0 import router` to `from routes.v0 import router` in `src/__init__.py`

**Comment by alf1e** [comment]
Oh that works. Thanks

**Comment by jtraub** [comment]
@alf1e if you want to know why it didn't work.

> Importing `parent.one` will implicitly execute `parent/__init__.py` and `parent/one/__init__.py`. Subsequent imports of `parent.two` or `parent.three` will execute `parent/two/__init__.py` and `parent/three/__init__.py` respectively.

https://docs.python.org/3/reference/import.html#regular-packages
