### ISSUE TITLE
Bug: SQLAlchemy Plugin DTO cannot reflect relationships.

### ISSUE THREAD

**Issue by cloasdata** [starlite-api/starlite#687]
Hi folks,

not sure if this really a bug or a feature, but Im not able to make a DTO from a instance having a simple relationship.
I do have very often the case where I just want to reflect the 1 in my sa model and explicitly not the n because it will soon pollute the namespace. 
And it is not that uncommon as per [sa doc](https://docs.sqlalchemy.org/en/14/orm/basic_relationships.html#many-to-one)

I could work around by expunging the orm model form the its session and set owner to None. But this implies a lot of additional problems. 

P. S. I really would encourage you to document only working examples. Code below is a copy from sa plugin doc, which does not work without adding a proper tablename. 

cheers...

```python
"""
Showing exception on simple relationships avoiding optional back_populate argument.
"""
from sqlalchemy import Column, Float, ForeignKey, Integer, String
from sqlalchemy.orm import relationship, declarative_base
from starlite.plugins.sql_alchemy import SQLAlchemyPlugin
from starlite import DTOFactory

Base = declarative_base()

dto_factory = DTOFactory(plugins=[SQLAlchemyPlugin()])

class Pet(Base):
    __tablename__ = "pet"  # needs to added to example, or change base definition accordingly.
    id = Column(Integer, primary_key=True)
    name = Column(String)
    age = Column(Float)
    owner_id = Column(Integer, ForeignKey("user.id"))
    owner = relationship("User") #  , back_populates="pets")


class User(Base):
    __tablename__ = "user" # needs to added to example, or change base definition accordingly.
    id = Column(Integer, primary_key=True)
    name = Column(String, default="moishe")
    # pets = relationship(
    #     "Pet",
    #     back_populates="owner",
    # )


UserDTO = dto_factory("UserDTO", User)
PetDTO = dto_factory("PetDTO", Pet)

mike = User(id=1, name="Mike")
kitty = Pet(id=1, name="kitty", age=4.2)
kitty.owner = mike

pet_dto = PetDTO.from_model_instance(kitty)

# prints:
# pydantic.error_wrappers.ValidationError: 1 validation error for Pet
# owner
#   value is not a valid dict (type=type_error.dict)
```

**Comment by Goldziher** [comment]
Hi @cloasdata - I would like to ask either @peterschutt or @cofin to look into this when they have time.

**Comment by peterschutt** [comment]
Yep I'll be able to have a look
