### ISSUE TITLE
Bug: Header values should not be lowercased

### ISSUE THREAD

**Issue by LordGaav** [starlite-api/starlite#693]
**Describe the bug**
Headers keys and values are lowercased before being rendered. While lowercasing key is fine (as per HTTP2 spec), lowercasing values should not be done.

For my use case, integrating with a payment provider involves passing a transaction ID as a header. This ID contains lowercase, uppercase letters, and is not case-insensitive.

**To Reproduce**
1. Create a new route_handler.
2. In the route_handler, modify the response: `response.headers["Foo"] = "Bar"` .
3. Observe that the key and value are returned as lowercase:

![2022-10-27_16-23](https://user-images.githubusercontent.com/546693/198312809-fc5b8947-be88-4354-b909-033270ae188f.png)

4. While reporting this, I noticed that `date` and `vary` headers are not lowercased.

**Additional context**
Looking at the Git history, it seems that originally Starlette was used for handling the responses. I thought that Starlette might also have this behaviour, but they do not lowercase the header values. See https://github.com/encode/starlette/blob/fa737beb2838f568fe2477e2316a7fdf3d3eb257/starlette/responses.py#L72 .

The relevant code in Starlite is here: https://github.com/starlite-api/starlite/blob/95379f102be249f3c9453fbf9d216a41eede2d6f/starlite/response/base.py#L257

**Comment by Goldziher** [comment]
yup, will fix. @provinzkraut can you take this on quickly and add it to the release you are doing?

**Comment by provinzkraut** [comment]
@Goldziher will do. Just waiting for a comment from you on the open conversations, then it's ready to go

**Comment by provinzkraut** [comment]
@LordGaav Thanks for reporting! It's fixed in #695 and will be in the next release!

**Comment by LordGaav** [comment]
That was quick, thanks 👍
