### ISSUE TITLE
Bug: Cookies set via `TestClient` are not set correctly when domain specified

### ISSUE THREAD

**Issue by provinzkraut** [starlite-api/starlite#706]
Setting cookies on the `TestClient` does not work as expected when specifying a domain:

```python
from typing import Any

from starlite import get, Request
from starlite.testing import create_test_client

@get(path="/test")
def get_cookies(request: Request) -> dict[str, Any]:
    return request.cookies

with create_test_client(route_handlers=[get_cookies]) as client:
    client.cookies.set("foo", "bar", domain=client.base_url.host)
    assert client.get("/test").json()
```

**Comment by provinzkraut** [comment]
May not be a bug on our side. Behaviour can be replicated when using starlette and the ASGI example from httpx's docs:

```
import asyncio

from httpx import AsyncClient
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.requests import Request
from starlette.routing import Route

async def hello(request: Request) -> JSONResponse:
    return JSONResponse(request.cookies)

app = Starlette(routes=[Route("/", hello)])

async def main():
    async with AsyncClient(app=app, base_url="http://testserver") as client:
        client.cookies.set("foo", "bar", domain=client.base_url.host)
        response = await client.get("/")
        assert response.json()

asyncio.run(main())
```

**Comment by Goldziher** [comment]
sounds good. I dont think it introduces a bug . Perhaps we should upstream the issue as well though - but i am not sure we should wait for a fix there, because it might not be an "issue" etc.

**Comment by provinzkraut** [comment]
I don't think it's an upstream issue really after finding out what the root cause is. It all works as intended, it's just not very explicit about those intentions, since httpx hides a lot of the implementation details. But I can't disagree with the fact that using an invalid FQDN results in issues isn't really bug.
