### ISSUE TITLE
Enhancment: Providers with `yield`

### ISSUE THREAD

**Issue by provinzkraut** [starlite-api/starlite#722]
### Discussed in https://github.com/starlite-api/starlite/discussions/678

<div type='discussions-op-text'>

<sup>Originally posted by **provinzkraut** October 24, 2022</sup>
On a [reddit post](https://www.reddit.com/r/Python/comments/yc7rvf/comment/itl41oy) someone brought up supporting generator based providers, so that cleanup code could be run after the request.</div>

**Comment by ExpLog** [comment]
Hi, that was me. Thanks for opening the issue.

Like you mentioned, by particular use case would be easy cleanup of dependencies. It would be much simpler to use, and it wouldn't depend on plugins or hooks like [this implementation](https://docs.pytest.org/en/6.2.x/fixture.html#yield-fixtures-recommended).

It is also a good feature to have in order to make project migrations from FastAPI to Starlite smoother, as FastAPI allows for dependencies with `yield`.

A very good (in my opinion) example of this type of functionality would be [pytest yield fixtures](https://docs.pytest.org/en/6.2.x/fixture.html#yield-fixtures-recommended).

**Comment by ExpLog** [comment]
I'd love to contribute, but it's going to have to wait until next year.

I unfortunately don't have the time right now, as I'm in the middle of moving countries, then I still need to find a new place to live.

**Comment by KabirSinghShekhawat** [comment]
@provinzkraut Let me take a shot at this, give me a few days to read-up some docs.

**Comment by provinzkraut** [comment]
@KabirSinghShekhawat Have at it!

**Comment by KabirSinghShekhawat** [comment]
@ExpLog @provinzkraut Could any of you explain the requirements in more detail? I'm new to open source and could use some guidance :).

**Comment by truejacobjones** [comment]
@provinzkraut I came up with this solution, let me know if it is satisfactory for you

`def _init_session() -> Generator:
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

def get_session():
    return next(_init_session())`
    
and this dependency is injected like so:
`class TheController(Controller):
    path = "/"
    dependencies = {"db": Provide(get_session)}


    @post("/login", status_code=200)
    def login(self, db: Session, data: Credentials) -> Response[UserDTO]:
        ...`

**Comment by provinzkraut** [comment]
@truejacobjones
Unfortunately this doesn't work, as `next` will only be called once on the generator, therefore code after the `yield` won't run.

```python
from starlite import Provide, create_test_client, get

STATE = {"value": False}


def set_state():
    STATE["value"] = True
    yield STATE
    STATE["value"] = False


def get_state():
    return next(set_state())


@get("/", dependencies={"foo": Provide(get_state)})
def route(state: dict) -> dict:
    return state


with create_test_client(route_handlers=[route]) as client:
    res = client.get("/")
    assert res.json() == {"value": True}
    assert STATE["value"] is False
```

**Comment by provinzkraut** [comment]
@KabirSinghShekhawat 
If you want to know about the requirements in general, take a look at our [contribution guidelines](https://github.com/starlite-api/starlite/blob/main/CONTRIBUTING.md). 

As for the specific requirements for this, there's not a lot.

- It should allow generator based dependencies, that will call `next` on the provided generator once the request is finished (this could maybe go into background tasks)
- It should not affect current dependencies

**Comment by provinzkraut** [comment]
@KabirSinghShekhawat Have you started working on this? It seems to be the most requested feature at the moment, so if you're not already on it, I'd take this since it would be nice to get done sooner than later!

**Comment by ExpLog** [comment]
Just to give a bit more context: for cleanup purposes, it would also be really cool if any exceptions that happen when handling a request are propagated to the generator, so appropriate clean up can be done.

This can be done by calling `generator.throw` ((docs)[https://docs.python.org/3/reference/expressions.html#generator.throw]). I believe FastAPI does it by turning the generators into context managers.

**Comment by provinzkraut** [comment]
Hmm. I can see the benefit of that, but I can also see use cases for having the cleanup be called unconditionally. 
In theory we could support both by `send`ing exceptions into the generator instead of `throw`ing them, but that's a bit ugly. I guess `try/finally` should suffice for this use case though?

The question would also be what we do with exceptions raised during cleanup / how they affect the rest of the exception handling. I did a little try run with this and it was relatively easy to add cleanup as `BackgroundTask`s, but I fear that the whole topic of exceptions during cleanup doesn't play nicely with the current way we handle exceptions and would make this quite a lot more complex. Not sure what the best way moving forward is here.

@jtraub @Goldziher what do you think about this?

**Comment by ExpLog** [comment]
I'm sorry if I was unclear, but the cleanup should happen regardless. Personally, I think exceptions should be thrown into the generators, so we can just use `try/except/finally` in them, instead of having to inspect what was sent into the generator.

I haven't read much of Starlite's code yet, so I'm unable to comment on what would be the best way to fit this into the current architecture. ):

**Comment by provinzkraut** [comment]
Sure, the cleanup should happen regardless, but we still need access to the exceptions. The issue is that those are only caught way higher up the call stack, so we would have to catch them in the response, `throw` them to the dependencies and re-raise them.

**Comment by KabirSinghShekhawat** [comment]
> @KabirSinghShekhawat Have you started working on this? It seems to be the most requested feature at the moment, so if you're not already on it, I'd take this since it would be nice to get done sooner than later!

Sure, feel free to take it up, I was anyways going to take some time since a bit of unexpected work came up.
