### ISSUE TITLE
Bug: Signature.return_annotation is a str when using "from __future__ import annotations"

### ISSUE THREAD

**Issue by smithk86** [starlite-api/starlite#745]
Starlite Version: 1.35.1
Python Version: 3.10.5

Traditionally, it seems that `Signature.return_annotation` holds the exact value of the annotation given. This is the assumption made in [starlite/handlers/websocket.py, line #67](https://github.com/starlite-api/starlite/blob/v1.35.1/starlite/handlers/websocket.py#L67).

This behavior changes once you include `from __future__ import annotations` into the module exercising the type validations. In this case, `Signature.return_annotation` is a string of the annotation you passed; what once was `None` becomes `"None"`. This triggers an `ImproperlyConfiguredException` in [starlite/handlers/websocket.py](https://github.com/starlite-api/starlite/blob/v1.35.1/starlite/handlers/websocket.py).

Python 3.10 includes a new `eval_str` kwarg for [inspect.signature](https://docs.python.org/3.10/library/inspect.html#inspect.signature) which appears to also work on `Signature.from_callback()` but this would be a compatibility-breaking change without further inspecting the version of Python being used.

Cheers!
Kyle

**Comment by Goldziher** [comment]
Hi Kyle, 

Good analysis. Do you want to add a PR?
