### ISSUE TITLE
Issues with the Route Handler OpenAPI Configuration docs for configuring secure doc endpoints

### ISSUE THREAD

**Issue by scott2b** [starlite-api/starlite#756]
The [Router Handler OpenAPI Configuration](https://starlite-api.github.io/starlite/usage/12-openapi/2-route-handler-configuration/?h=securityschemes#example-applications) documentation seems to have a typo or bug. The `components` and (I think ) the `security` properties should go into the OpenAPIConfig rather than Starlite. As-is, Starlight does not accept the components parameter.

There also seems to be some discrepency in the referenced docs about whether apiKey or bearer authorization is intended. I ended up going with apiKey (which is what I want for my current project) and have a components parameter to the OpenAPIConfig that looks like this:

```
...
        components=Components(
            securitySchemes={
                "apiKey": SecurityScheme(
                    type="apiKey",
                    name="X-API-KEY",
                    security_scheme_in="header",
                )
            },
        ),
        security=[{"apiKey": []}],
...
```

And then I've specified apiKey security on the "internal" route:

```
@get("/other", tags=["internal"], security=[{"apiKey": []}])
def internal_path_handler() -> None:
    return {"foo": "bar"}
```
~Having fixed the above, however, I think there is still some lack of clarity here. I am uncertain if the results are as intended. When I get this working the "internal" endpoint simply becomes unusable via the docs. The header is there: "Internal: this endpoint is for internal users," but there is no way to use it. My expectation is that once I enter an API key via the Authorize button in Swagger that I would be able to issue requests against any endpoints that are apiKey protected. However, since indicating the apiKey security on the internal endpoint seems to make that endpoint disappear from the docs, there is no way to do this. Even after issuing a separate request and verifying that swagger is sending my api key header, the interactive component for the apiKey protected endpoint is still missing.~

~Perhaps there is something else wrong here I have not yet figured out?~

**Comment by scott2b** [comment]
Update: I've come to realize that I forgot to put my endpoints into the route_handlers list to Starlite. My routes are showing up in the docs now. The only thing that holds above I think are the misplaced parameters in the documentation and the discrepancy between auth types.

Thanks!

**Comment by Goldziher** [comment]
Ha yes, issue in the docs. A PR fixing the docs is welcome 😸

**Comment by Goldziher** [comment]
typo in docs is fixed. 

Can you explain what is the discrepency you experience?

**Comment by scott2b** [comment]
Just that an http/bearer security scheme is configured in the OpenAPIConfig, but the example specified route `internal_path_handler` uses an apiKey scheme that is never configured.

**Comment by Goldziher** [comment]
can you show me some output from the openapi docs so i understand better? 

@cofin - this is your domain, if you find time it would be gr8.

**Comment by scott2b** [comment]
Sorry, I think I have not been clear and may have been ambiguous with the term "docs." I am referring specifically to the last code example on this page of the Starlite documentation: https://starlite-api.github.io/starlite/usage/12-openapi/2-route-handler-configuration/?h=securityschemes#example-applications

It appears to me that there was an intent to setup one type of security scheme but then a different type was used (apiKey vs bearer). This may be a simple copy-paste error. If I understand the example correctly, either an apiKey security scheme needs to be added to the configuration (e.g. see my code example above), or the secured (i.e. internal) route needs to use the bearer scheme that is configured rather than the apiKey scheme as specified. It's a minor issue, but seems like it could be potentially confusing.

**Comment by Goldziher** [comment]
Ha ok. This is fixed. Thanks!
