### ISSUE TITLE
Returning of Starlette's JSONResponse appears broken

### ISSUE THREAD

**Issue by scott2b** [starlite-api/starlite#762]
**Describe the bug**

This may be a documentation issue. When I follow the [documentation here](https://starlite-api.github.io/starlite/usage/5-responses/3-returning-responses/#returning-other-library-responses) to return a Starlette JSONResponse, I get a **500: Unable to serialize response content**.

**To Reproduce**

I used the following code, based on the documentation linked above:

```python
from starlette.responses import JSONResponse
from starlite import get, Starlite
from starlite.types import ASGIApp


@get("/this-works")
def get_dict() -> dict:
    return { "testing": "hello" }

@get("/this-does-not")
def get_jsonresponse() -> ASGIApp:
    return JSONResponse(content={"hello": "world"})  # type: ignore

app = Starlite(
    debug=True,
    route_handlers=[get_dict, get_jsonresponse]
)
```

**Additional context**

I do not have a strong need to specifically return Starlette responses. What I do have a need for is to enable background tasks that are dependent on resources either injected into or conjured within route handlers. Based on the [background tasks documentation](https://starlite-api.github.io/starlite/usage/5-responses/11-background-tasks/) there does not appear to be a straightforward way to do this with the standard pattern of specifying the task in the route decorator -- but this probably best left to a separately named discussion thread (which I have now done in #765).

**Comment by Goldziher** [comment]
lemme test this

**Comment by Goldziher** [comment]
fix is incoming

**Comment by peterschutt** [comment]
@all-contributors please add @scott2b for bug report
