### ISSUE TITLE
Enhancement: Versioning support

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#768]
Would be good to add a way to easily setup versioning. My thinking is a kwarg on router/handler or attribute on controller for version, which will then be prepended to the path as a version path.

**Comment by Goldziher** [comment]
not sure, here is an example from nestJS: https://docs.nestjs.com/techniques/versioning

**Comment by provinzkraut** [comment]
Okay, that would be more than a path prefix. Looks like a good concept to me. I would suggest supporting it on all layers then.

**Comment by Goldziher** [comment]
It should

**Comment by Goldziher** [comment]
my thinking after fiddling with this is that we need to start from the level of API design, i.e. the API docs, and otherstand what is the best use we have here.

I don't think we should support versioning via weird paramters, it should reflect only in paramters that can be set in the OpenAPI schema. Usually this is a path parameter - because it allows to divide operations.

**Comment by Goldziher** [comment]
ok, this isn't really something we can implement without hitting performance - following the nestJS design. Otherwise its just prepending a prefix to the url, which is a bit silly. So im closing this issue.
