### ISSUE TITLE
[enhancement] logging setup to be non-blocking

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#77]
The default logging config, which is just a simple abstraction on top of DictConfig, creates a standard python logger. The issue with this setup is that python logging is sync and blocking. This means that the logging config needs to be updated to setup a QueueHandler. 

Here are some resources regarding this:

1. https://rob-blackbourn.medium.com/how-to-use-python-logging-queuehandler-with-dictconfig-1e8b1284e27a
2. https://stackoverflow.com/questions/25585518/python-logging-logutils-with-queuehandler-and-queuelistener
3. https://betterprogramming.pub/power-up-your-python-logging-6dd3ed38f322

**Comment by JonasKs** [comment]
We use [this](https://python-logstash-async.readthedocs.io/en/stable/) library with logstash, it's awesome.

**Comment by madlad33** [comment]
Hello, I would like to contribute and work on this issue.

**Comment by Goldziher** [comment]
> Hello, I would like to contribute and work on this issue. 

Great, looking forward to your PR 😃
