### ISSUE TITLE
All requests fail when `exclude_opt_key` or `exclude` param is passed to `AllowedHostsConfig` or `CompressionConfig`

### ISSUE THREAD

**Issue by jtraub** [starlite-api/starlite#803]
**Describe the bug**
When `exclude_opt_key` or `exclude` params are passed to `AllowedHostsConfig` or `CompressionConfig` all requests generate 500 error. 

This happens because we apply both middlewares on app's asgi handler. Temp.solution would be moving its applicationto the `build_route_middleware_stack` function (the same way we did with CSRF middleware).

**To Reproduce**
Run this file and open http://127.0.0.1:8000/ in the browser.
You will see `{"status_code":500,"detail":"KeyError('route_handler')"}`

```python
import uvicorn
from starlite import Starlite, get, AllowedHostsConfig

@get("/")
def index() -> str:
    return "ok"

app = Starlite(
    route_handlers=[index],
    allowed_hosts=AllowedHostsConfig(
        allowed_hosts=["localhost"],
        exclude_opt_key="skip_allowed_hosts"
    )
)

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)

```

UPD: Will try to provide a temp fix soon.

**Comment by peterschutt** [comment]
Closed in #804
