### ISSUE TITLE
Wrapping NewRelic around Starlite app breaks handlers with path parameters 

### ISSUE THREAD

**Issue by indra-an** [starlite-api/starlite#813]
Ask your question...
I tried to integrate starlite with newrelic 

```python
import os
from starlite import Starlite
import newrelic.agent

from routes import home

newrelic.agent.initialize('newrelic.ini')

app = Starlite(route_handlers=[home])
newrelic.agent.ASGIApplicationWrapper(app)
```

but getting error
`CIMultiDict keys should be either str or subclasses of str`

could you guys help me why this happen?

**Comment by jtraub** [comment]
@indra-an I can not reproduce the problem with empty `newrelic.ini` and the following code

```python
/tmp/newrelic_test took 2s 
> cat app.py 
import uvicorn
import os
from starlite import Starlite, get
import newrelic.agent


newrelic.agent.initialize('newrelic.ini')

@get("/")
def home() -> str:
    return "home"

app = Starlite(route_handlers=[home])
newrelic.agent.ASGIApplicationWrapper(app)

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8000)
 
/tmp/newrelic_test 
> cat newrelic.ini 

```

Could you please provide more details?

**Comment by indra-an** [comment]
Hi @jtraub, this is my newrelic.ini

```[newrelic]

license_key = APP_LICENSE_KEY
app_name = APP_NAME
monitor_mode = true
log_file = stdout
log_level = info
high_security = false
transaction_tracer.enabled = true
transaction_tracer.transaction_threshold = apdex_f
transaction_tracer.record_sql = obfuscated
transaction_tracer.stack_trace_threshold = 0.5
transaction_tracer.explain_enabled = true
transaction_tracer.explain_threshold = 0.5
transaction_tracer.function_trace =
error_collector.enabled = true
error_collector.ignore_classes =
error_collector.expected_classes =
browser_monitoring.auto_instrument = true
thread_profiler.enabled = true
distributed_tracing.enabled = true```

I also tried with this route
```
@get("/{id:str}", media_type=MediaType.TEXT)
def home(id: str) -> str:
    return id
```

**Comment by jtraub** [comment]
@indra-an I still can not reproduce

```python
import uvicorn
import os
from starlite import Starlite, get
import newrelic.agent


newrelic.agent.initialize('newrelic.ini')

@get("/")
def home() -> str:
    return "home"

app = Starlite(route_handlers=[home])
app_ = newrelic.agent.ASGIApplicationWrapper(app)

if __name__ == "__main__":
    uvicorn.run(app_, host="127.0.0.1", port=8000)
```

My ini file:
```
[newrelic]

# You must specify the license key associated with your New
# Relic account. This key binds the Python Agent's data to your
# account in the New Relic service.
license_key = ....

# The application name. Set this to be the name of your
# application as you would like it to show up in New Relic UI.
# The UI will then auto-map instances of your application into a
# entry on your home dashboard page.
app_name = TestApp
monitor_mode = true
log_file = stdout
log_level = info
high_security = false
transaction_tracer.enabled = true
transaction_tracer.transaction_threshold = apdex_f
transaction_tracer.record_sql = obfuscated
transaction_tracer.stack_trace_threshold = 0.5
transaction_tracer.explain_enabled = true
transaction_tracer.explain_threshold = 0.5
transaction_tracer.function_trace =
error_collector.enabled = true
error_collector.ignore_classes =
error_collector.expected_classes =
browser_monitoring.auto_instrument = true
thread_profiler.enabled = true
distributed_tracing.enabled = true

```

When I launch it I see my handler output and the agent reports back to the server
![image](https://user-images.githubusercontent.com/153191/202411517-5b4a618a-6b19-4491-a23a-c29149d12fa5.png)

**Comment by jtraub** [comment]
So could you please produce a self-contained example (including version of dependencies) I can run? Otherwise the issue should be closed as non-reproducible.

**Comment by indra-an** [comment]
@jtraub could you change your route to 
```
@get("/{id:str}")
def home(id: str) -> str:
    return id
```
and try to access that endpoint ?

so it will return the same error

**Comment by indra-an** [comment]
this is my dependencies

```

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
uvicorn = "^0.19.0"
pynamodb = "^5.2.3"
smart-open = {extras = ["s3", "gcs"], version = "^6.2.0"}
starlite = "^1.35.1"
boto3 = "^1.25.4"
everett = {extras = ["yaml"], version = "^3.1.0"}
newrelic = "^8.4.0"
```

**Comment by indra-an** [comment]
ah i`ve added repository for reproduce this case @jtraub
[https://github.com/indra-an/starlite-newrelic](https://github.com/indra-an/starlite-newrelic)

**Comment by jtraub** [comment]
Now I can reproduce it, thanks.

I will investigate the problem in the next few days.

**Comment by jtraub** [comment]
Ok, quick investigations shows that the current code doesn't properly process `scope["headers"]` when it is a tuple of tuples. It works with list of tuples though

According to the spec
https://asgi.readthedocs.io/en/latest/specs/www.html#http-connection-scope


`headers` (`Iterable[[byte string, byte string]]`) – An iterable of `[name, value]` two-item iterables, where name is the header name, and value is the header value.

**Comment by indra-an** [comment]
Thank you for investigating and looking to this issue! 
we are planning to deploy our first starlite service to production very soon

**Comment by jtraub** [comment]
@indra-an so thanks to @peterschutt the code that resolves the problem with NewRelic has landed into the `main` branch. It hasn't been released yet.

You can now try to install Starlite from the repo `git+https://github.com/starlite-api/starlite.git#main` and check if it works for you.

**Comment by amryamanah** [comment]
hi @jtraub 

Thanks a lot, we confirm that the main branch works on new relic agent version 8.4.0

Best regards
