### ISSUE TITLE
Enhancment: Support arbitrary json libraries

### ISSUE THREAD

**Issue by v3ss0n** [starlite-api/starlite#851]
**What's the feature you'd like to ask for.**

Starlite should be able to choose a default json decoder and make it configurable.
Currently Starlite cannot run on PyPy due to orjson compilation problem and orJson states that they are not going to make pypy compatible anytime soon https://github.com/ijl/orjson/issues/90 , so I couldn't test starlite on pypy which could see a good deal of performance improvement on pypy.

**Additional context**

Should orjson be optional dependency and starlite should be able to configure any json backends ?

**Comment by Goldziher** [comment]
Well, there is nothing preventing users from subclassing response. Do we need to add anything extra?

**Comment by Goldziher** [comment]
Ok, im closing this since its easy enough to subclass a response and use a different serializer.
