### ISSUE TITLE
Redis is not included with starlite[full], and documentation references aioredis

### ISSUE THREAD

**Issue by ThinksFast** [starlite-api/starlite#865]
**Describe the bug**
When installing `starlite[full]`, the redis group is not included.  And installing `starlite[full]` seems to remove redis packages installed with `starlite[redis]`.

Also, the Starlite documentation is slightly out of date.  Session middleware page says Starlite uses `aioredis`, but the example correctly shows `redis`

https://starlite-api.github.io/starlite/usage/7-middleware/3-builtin-middlewares/5-session-middleware/

**To Reproduce**
`pip install starlite[full]` or `poetry add starlite[full]`, check installed packages, `redis` and `hiredis` is missing

**Comment by cofin** [comment]
to do:
- [] Update `pyproject.toml` to install `redis` group with `full`
- [] Modify documentation references to `aioredis` to `redis`

**Comment by provinzkraut** [comment]
I already have fixed this in an upcoming PR which updates the docs
