### ISSUE TITLE
Bug: Structlog example throws a 500 error

### ISSUE THREAD

**Issue by robertlagrant** [starlite-api/starlite#871]
**Describe the bug**
Using the [Structlog sample code](https://starlite-api.github.io/starlite/usage/0-the-starlite-app/4-logging) with Starlite returns a 500 error.

**To Reproduce**
Paste the exact sample code linked into a text file, run.py.
Have the dependencies (below) installed and available.
Run the command `uvicorn run:app`.
Hit http://localhost:8000 in the browser.
Error response: `{"status_code":500,"detail":"TypeError(\"_make_filtering_bound_logger.<locals>.log() missing 1 required positional argument: 'event'\")"}`

**Additional context**
Python 3.10
Starlite 1.39.0
Structlog 22.3.0
Uvicorn 0.19.0 (extras = standard)
MacOS Monterey 12.16.1

**Comment by jtraub** [comment]
@robertlagrant could you please try to launch the code with the latest Starlite version.

**Comment by robertlagrant** [comment]
@jtraub same on Starlite 1.42.0 anyway :)

**Comment by jtraub** [comment]
@robertlagrant it is just a typo in the docs.

Loggers follow [`Logger`](https://github.com/starlite-api/starlite/blob/main/starlite/types/protocols.py#L4) protocol which doesn't have `log` method. So you need to replace
```python
request.logger.log("inside a request")
```
in the example code with
```python
request.logger.info("inside a request")
```

and it should work.

**Comment by jtraub** [comment]
There is an ongoing effort to make sure that all examples in the docs are runnable (#343).

@provinzkraut is working hard on this and I think it will be addressed soon.

**Comment by robertlagrant** [comment]
Confirmed - this change works.
```bash
% poetry run uvicorn run:app
INFO:     Started server process [80291]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
{"event":"inside a request","level":"info","timestamp":"2022-11-28T19:19:25.317728Z"}
INFO:     127.0.0.1:62892 - "GET / HTTP/1.1" 200 OK
```
