### ISSUE TITLE
Bug: OpenAPI schema does not generate file upload form in Swagger

### ISSUE THREAD

**Issue by adambozson** [starlite-api/starlite#877]
**Describe the bug**
Using `UploadFile`, the generated docs don't produce the expected Swagger file upload form component.

**To Reproduce**
The following standalone app:
```python
import logging

from starlite import Body, RequestEncodingType, UploadFile, post, Starlite

logger = logging.getLogger(__name__)


@post(path="/upload", cache=False, tags=["Collection"])
async def handle_collection_upload(
    data: UploadFile = Body(media_type=RequestEncodingType.MULTI_PART),
) -> dict[str, str]:
    """Upload a file"""
    logger.info("Processing Uploaded File")
    return {
        "status": "file uploaded",
    }

app = Starlite(route_handlers=[handle_collection_upload])
```
produces this Swagger UI:
<img width="1384" alt="Screenshot 2022-11-29 at 15 15 42" src="https://user-images.githubusercontent.com/13031205/204567944-bbe2d22e-5b71-487c-afcb-d81537d29072.png">
But we expect an upload form, similar to that generated by FastAPI.

**Additional context**
This appears to be a regression of #396.

**Comment by Goldziher** [comment]
annoying. ill check it out.
