### ISSUE TITLE
OpenAPI schema invalid due to duplicate operationIds

### ISSUE THREAD

**Issue by mje-nz** [starlite-api/starlite#897]
**Describe the bug**
The OpenAPI schema includes the autogenerated OPTIONS handler for every HTTP route. These all have the same name, so the schema has `operationId: Options Handler` for each one. The OpenAPI 3.1.0 spec says each `operationId` has to be unique, so the schema is non-conforming.

This results in [openapi-generator](https://github.com/OpenAPITools/openapi-generator-cli) rejecting it.

**To Reproduce**
Download `/schema/openapi.yaml` from an instance of [starlite-pg-redis-docker](https://github.com/starlite-api/starlite-pg-redis-docker), or presumably any application with more than one route that doesn't specify its own OPTIONS handler. Grep for `operationId` and observe that they are not unique.

**Additional context**
Using `npx openapi-generator-cli generate -i ./openapi.yaml -g typescript-angular -o src/app/core/api/v1 --skip-validate-spec` succeeds, and generates `DefaultService.optionsHandler`, `DefaultService.optionsHandler_1`, `DefaultService.optionsHandler_2` etc to call the default OPTIONS handlers.

**Comment by jtraub** [comment]
@mje-nz could you please try the latest Starlite version?

**Comment by jtraub** [comment]
I am asking to do this because #826 addressed that.

**Comment by Goldziher** [comment]
closing this

**Comment by mje-nz** [comment]
Sorry about that, thanks team
