### ISSUE TITLE
Enhancement: Pagination Support

### ISSUE THREAD

**Issue by Alc-Alc** [starlite-api/starlite#903]
**What's the feature you'd like to ask for.**

Pagination for SQLALchemy

Frameworks such as Flask and FastAPI have extensions that add pagination support.

Would it be possible to add something like this to starlite? This can either be in the base library or as an extension, whichever is easier to maintain.

**Additional context**

Here is how this can be done in other frameworks.

In case of flask, one way to do this is using [`flask_sqlalchemy.SQLAlchemy.paginate`](https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/api/#flask_sqlalchemy.SQLAlchemy.paginate) which returns a [`flask_sqlalchemy.pagination.Pagination`](https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/api/#flask_sqlalchemy.pagination.Pagination) object.

As shown in this [StackOverflow answer](https://stackoverflow.com/a/43104868/12502959) here is how this can be used.

```python
@app.route('/myview/<int:page>',methods=['GET'])
def view(page=1):
    per_page = 10
    posts = Posts.query.order_by(Posts.time.desc()).paginate(page,per_page,error_out=False)
    return render_template('view.html',posts=posts)

```

[This extension](https://uriyyo-fastapi-pagination.netlify.app) for FastAPI lets you configure it as a response model with OpenAPI schema support.

```python
from fastapi import FastAPI
from pydantic import BaseModel

from fastapi_pagination import Page, add_pagination, paginate

app = FastAPI()


class User(BaseModel):
    name: str
    surname: str


users = [
    User(name='Yurii', surname='Karabas'),
    # ...
]


@app.get('/users', response_model=Page[User])
async def get_users():
    return paginate(users)


add_pagination(app)

```

Pagination API in starlite does not have to conform with the above mentioned examples, they are listed to show how other frameworks do it. Any design that suits starlite the most would be the preferred outcome. Thanks for the all the work you guys do in this project.

**Comment by Goldziher** [comment]
As discussed in slack:

1. We will create a general pagination helper, which can receive an iterator or async iterator and paginate it. This should not be SQLA specific but rather simply work with iterators.
2. Pagination must include an OpenAPI component to this. As such it must be declared as part of the function signature - probably as a return typing.
3. We should follow a standard pagination scheme, not reinvent the wheel.

**Comment by provinzkraut** [comment]
> We will create a general pagination helper, which can receive an iterator or async iterator and paginate it. This should not be SQLA specific but rather simply work with iterators.

I think it should be a class, not an iterator. In a paginated endpoint, you usually *don't* want to go through all the previous pages, but be able to retrieve a specific page. This can then be used by the generic pagination helper to get the current/next/previous pages.
