### ISSUE TITLE
Version >0.6.0 breaks query parameters

### ISSUE THREAD

**Issue by i404788** [starlite-api/starlite#92]
I haven't done extensive testing yet, but it seems like version >0.6.0 breaks query parameters as described in the documentation (https://starlite-api.github.io/starlite/usage/3-parameters/#query-parameters). ~~It gives 404 without every executing the function.~~

```
class ApiV1Controller(Controller):
    path = "/api/v1"

    @get(path="/product/{isin:str}/rawdata")
    async def product_rawdata(self, isin: str, dataType:  Literal['profile', 'etc']) -> Any:
        raise KeyError("Test")

with create_test_client(ApiV1Controller) as client:
        print(client.get("/api/v1/product/test/rawdata").text)
        print(client.get("/api/v1/product/test/rawdata?dataType=profile").text)
```
Output (1.2.0):
```
{"detail":"Missing required parameter dataType for url http://testserver/api/v1/product/test/rawdata","extra":null}
{"detail":"Not Found","extra":null}
```

Output (0.6.0):
```
{"detail":"Validation failed for GET http://testserver/api/v1/product/test/rawdata:\n\ndataType\n  none is not an allowed value (type=type_error.none.not_allowed)","extra":null}
Traceback (most recent call last):
...
    raise KeyError("test")
KeyError: 'test'
```

UPDATE: seems like it does run the function, but fails with 404 if there is a KeyError; I've updated the example. This might be intended behavior but it's very confusing since it also doesn't log anything on the server-side.

**Comment by Goldziher** [comment]
Hi, it should return a status 400 not a status 404. Can you add a test marked by @pytest.mark.xfail?

**Comment by Goldziher** [comment]
thank you @i404788 . V1.2.3 has been released with a fix. Please see if it resolves your issue and if so close this issue.
