### ISSUE TITLE
Bug: uploading multiple files doesn't work

### ISSUE THREAD

**Issue by danielgafni** [starlite-api/starlite#933]
**Describe the bug**
Uploading multiple files doesn't work. Here is the error:

![image](https://user-images.githubusercontent.com/49863538/207742120-f40feeb8-5964-4a87-815c-df8e00a6713f.png)

**To Reproduce**
```python
@post(path="/handle_file_upload")
async def handle_file_upload(
    files: list[UploadFile] = Body(media_type=RequestEncodingType.MULTI_PART),
) -> str:
    return "success"
```

**Additional context**
starlite 1.45.0

**Comment by Goldziher** [comment]
Hi. Just to clarify this - the bug is in the swaggerUI website or when you actually try to upload multiple files?

**Comment by provinzkraut** [comment]
This is not a bug. You need to specify the body parameter as `data` instead of `files` for it to work:

```python
from starlite import post, Body, UploadFile, RequestEncodingType, create_test_client


@post(path="/")
async def handle_file_upload(data: list[UploadFile] = Body(media_type=RequestEncodingType.MULTI_PART)) -> str:
    return "success"


with create_test_client([handle_file_upload]) as client:
    res = client.post("/", files=[("filename1", b"foo"), ("filename2", b"bar")])
    assert res.status_code == 201
```

For further information, see the documentation section on file uploads: https://starlite-api.github.io/starlite/usage/4-request-data/#file-uploads.

**Comment by provinzkraut** [comment]
> When I do it I lose the upload functionality in the Swagger UI.

That's a separate issue then. I checked it and it does indeed not work. The file upload however works as intended and advertised.

**Comment by danielgafni** [comment]
Sounds reasonable. Should I open another issue for that?

**Comment by provinzkraut** [comment]
Go ahead

**Comment by danielgafni** [comment]
#941
