### ISSUE TITLE
Bug: Unexpected behaviour with field aliases and open api.

### ISSUE THREAD

**Issue by WardPearce** [starlite-api/starlite#952]
**Describe the bug**
Found something what i think might be unexpected behaviour with field aliases and open api.

**To Reproduce**

```python
class UserPublicPasswordModel(BaseModel):
    password: str
    id: ObjectIdStr = Field(..., alias="_id")
```

OpenAPI schema says the response is

```json
{

    "password": "string",
    "_id": "string"
}
```

Investigating network traffic in firefox, the response is  actually ("id", instead of "\_id")

```json
{
	"password": "PnAn4B6PZ02afrJQvgcl9CAtmog1plPZy6RdpPqD5NO4oNmjdFT4QF_shXjY8SPo74BP0ST1Xd0MwdPGe9nR5ZIuN0CX1ONLS-Z5ojvdqftRFIwsmf9h4wJ4skJ_pfCFFjVF7WFbXxwP8NbcU5NXndkbck3dWyc-pi-3Kly9vKw",
	"id": "63995f87ead687a59ae652be"
}
```

The router handler

```python
@post(
    path="/proof",
    description="Used to generate unique password to be signed by client's private key.",
)
async def proof_user(data: UsernameModel) -> UserPublicPasswordModel:
    if await Sessions.mongo.user.count_documents({"username": data.username}) == 0:
        raise NotFoundException()

    password = secrets.token_urlsafe(128)
    result = await Sessions.mongo.proof.insert_one(
        {
            "password": password,
            "username": data.username,
            "expires": datetime.now(tz=timezone.utc) + timedelta(seconds=60),
        }
    )
    return UserPublicPasswordModel(password=password, _id=result.inserted_id)
```

**Comment by provinzkraut** [comment]
This is in fact expected behaviour, as `UserPublicPasswordModel.id` will serialize to a field with the key `id` by default, and not its alias-name, but the schema generated by pydantic used the alias-name:

```python
from pydantic import BaseModel, Field


class UserPublicPasswordModel(BaseModel):
    id: str = Field(..., alias="_id")


print(UserPublicPasswordModel(_id=1).json())
# {"id": "1"}
print(UserPublicPasswordModel.schema_json())
# {"title": "UserPublicPasswordModel", "type": "object", "properties": {"_id": {"title": " Id", "type": "string"}}, "required": ["_id"]}

```

I wouldn't say this is a bug necessarily, but something we might want to look into. @Goldziher thoughts?

**Comment by WardPearce** [comment]
Yeah issue im running into is using [openapi-typescript-codegen](https://github.com/ferdikoomen/openapi-typescript-codegen/), it generates the following model.
```typescript

export type UserPublicPasswordModel = {
    password: string;
    _id: string;
};
```

**Doing**
```typescript
const toProve = await boringClient.default.proofUser({
  username: rawUsername,
});
 ```

**Results in**
```typescript
console.log(toProve.id)  // Correct value but type error
console.log(toProve._id)  // Correct type but string is undefined.
```

**Comment by Goldziher** [comment]
> This is in fact expected behaviour, as `UserPublicPasswordModel.id` will serialize to a field with the key `id` by default, and not its alias-name, but the schema generated by pydantic used the alias-name:
> 
> ```python
> from pydantic import BaseModel, Field
> 
> 
> class UserPublicPasswordModel(BaseModel):
>     id: str = Field(..., alias="_id")
> 
> 
> print(UserPublicPasswordModel(_id=1).json())
> # {"id": "1"}
> print(UserPublicPasswordModel.schema_json())
> # {"title": "UserPublicPasswordModel", "type": "object", "properties": {"_id": {"title": " Id", "type": "string"}}, "required": ["_id"]}
> ```
> 
> I wouldn't say this is a bug necessarily, but something we might want to look into. @Goldziher thoughts?

i'll look into this. How about a top level openapi config option regarding handling of `alias`, will that be helpful? otherwise we can of course go into the route handler level as well.

**Comment by WardPearce** [comment]
> > This is in fact expected behaviour, as `UserPublicPasswordModel.id` will serialize to a field with the key `id` by default, and not its alias-name, but the schema generated by pydantic used the alias-name:
> > ```python
> > from pydantic import BaseModel, Field
> > 
> > 
> > class UserPublicPasswordModel(BaseModel):
> >     id: str = Field(..., alias="_id")
> > 
> > 
> > print(UserPublicPasswordModel(_id=1).json())
> > # {"id": "1"}
> > print(UserPublicPasswordModel.schema_json())
> > # {"title": "UserPublicPasswordModel", "type": "object", "properties": {"_id": {"title": " Id", "type": "string"}}, "required": ["_id"]}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I wouldn't say this is a bug necessarily, but something we might want to look into. @Goldziher thoughts?
> 
> i'll look into this. How about a top level openapi config option regarding handling of `alias`, will that be helpful? otherwise we can of course go into the route handler level as well.

openapi config option seems like a clean solution, handling it within the router seems like it could become repetitive if a model is used for multiple responses or you have lots of models with aliases .

**Comment by Goldziher** [comment]
> > > This is in fact expected behaviour, as `UserPublicPasswordModel.id` will serialize to a field with the key `id` by default, and not its alias-name, but the schema generated by pydantic used the alias-name:
> > > ```python
> > > from pydantic import BaseModel, Field
> > > 
> > > 
> > > class UserPublicPasswordModel(BaseModel):
> > >     id: str = Field(..., alias="_id")
> > > 
> > > 
> > > print(UserPublicPasswordModel(_id=1).json())
> > > # {"id": "1"}
> > > print(UserPublicPasswordModel.schema_json())
> > > # {"title": "UserPublicPasswordModel", "type": "object", "properties": {"_id": {"title": " Id", "type": "string"}}, "required": ["_id"]}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I wouldn't say this is a bug necessarily, but something we might want to look into. @Goldziher thoughts?
> > 
> > 
> > i'll look into this. How about a top level openapi config option regarding handling of `alias`, will that be helpful? otherwise we can of course go into the route handler level as well.
> 
> openapi config option seems like a clean solution, handling it within the router seems like it could become repetitive if a model is used for multiple responses or you have lots of models with aliases .

aight, I will address this issue.

**Comment by WardPearce** [comment]
> > > > This is in fact expected behaviour, as `UserPublicPasswordModel.id` will serialize to a field with the key `id` by default, and not its alias-name, but the schema generated by pydantic used the alias-name:
> > > > ```python
> > > > from pydantic import BaseModel, Field
> > > > 
> > > > 
> > > > class UserPublicPasswordModel(BaseModel):
> > > >     id: str = Field(..., alias="_id")
> > > > 
> > > > 
> > > > print(UserPublicPasswordModel(_id=1).json())
> > > > # {"id": "1"}
> > > > print(UserPublicPasswordModel.schema_json())
> > > > # {"title": "UserPublicPasswordModel", "type": "object", "properties": {"_id": {"title": " Id", "type": "string"}}, "required": ["_id"]}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > I wouldn't say this is a bug necessarily, but something we might want to look into. @Goldziher thoughts?
> > > 
> > > 
> > > i'll look into this. How about a top level openapi config option regarding handling of `alias`, will that be helpful? otherwise we can of course go into the route handler level as well.
> > 
> > 
> > openapi config option seems like a clean solution, handling it within the router seems like it could become repetitive if a model is used for multiple responses or you have lots of models with aliases .
> 
> aight, I will address this issue.

Awesome, as something who used fastapi & starlette a lot. Starlite is great, most likely my got to framework now!

**Comment by provinzkraut** [comment]
> How about a top level openapi config option regarding handling of alias, will that be helpful? otherwise we can of course go into the route handler level as well.

A layered parameter would also work well here I think.
