### ISSUE TITLE
Enhancement: HTMX support

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#953]
It would be great to have an `htmx` support added under `starlite.contrib.htmx`. 

For example, see this package: https://github.com/adamchainz/django-htmx

**Comment by jenish2014** [comment]
Hi, Been 2 weeks no has replied. Would it be okay if I work on it?

**Comment by provinzkraut** [comment]
Of course! Anyone is welcome to work on any open issue that haven't been assigned yet.

**Comment by jenish2014** [comment]
Thanks, I looked in [django-htmx](https://github.com/adamchainz/django-htmx) and it provides request.htmx attribute to request object. It makes it possible to do things like:
```
def my_view(request):
    if request.htmx:
        template_name = "partial.html"

def my_view(request):
    if request.htmx.boosted:
        # do something special
        ...
    return render(...)
```
but, request in Starlite cannot be extended or modified as request attributes are in __slots__. 
So, should we add htmx-headers to app scope?
coz, request.headers gets populated with htmx-headers and request.headers['hx-boosted'] (and other htmx-headers) is already possible.

**Comment by provinzkraut** [comment]
> but, request in Starlite cannot be extended or modified

Of course you can. You subclass `Request`. So you'd have `HTMXRequest`, which you could then pass as `request_class` to the appropriate layer.

**Comment by jenish2014** [comment]
@provinzkraut, can request instance be modified in middleware and passed on to route handlers?

Currently, I am using your approach but, I have to modify request object in `before_request` hook at application or router level. This will block the users ability to add another before_request hook when using htmx.
```
async def before_request_handler(request: Request) -> None:
    if request.headers.get('hx-request') == "true":
        request.htmx = HtmxDetails(request)
```

Current options:
- to achieve django-htmx like interface `request.htmx`, I am subclassing Request and adding HtmxDetails class but, I am stuck at modifying request in middleware.
- we can pass to scope as follows:
```
middleware:
async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
    request = scope['app'].request_class(scope, receive)
    scope['htmx'] = HtmxDetails(request)
    await self.app(scope, receive, send)

route handler:
@get()
async def hello(request: Request) -> Response:
    htmx = request.scope['htmx']
    if htmx:
        print(htmx.current_url)
    return Response('world')
```

- else we can pass to state.

```
middleware:
async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
    request = scope['app'].request_class(scope, receive)
    request.state['htmx'] = HtmxDetails(request)
    await self.app(scope, receive, send)

route handler:
@get()
async def hello(request: Request) -> Response:
    htmx = request.state['htmx']
    if htmx:
        print(htmx.current_url)
    return Response('world')
```

**Comment by provinzkraut** [comment]
>  I have to modify request object in `before_request` hook at application or router level

Why is that? 

I think you misunderstood what I was talking about. My suggestion was to subclass `Request`, so that you'd have `HTMXRequest`, and then use this as `request_class` on whatever layer you want HTMX support. You can then add the HTMX specific attributes and methods to that request, without having to mess around with state and middlewares and such.

In the end, you would have something like this:

```python
@get(request_class=HTMXRequest)
async def hello(request: HTMXRequest) -> str:
    if htmx := request.htmx:
        print(htmx.current_url)
    return "world"
```

Is there anything particular to HTMX that makes it so it can't be handled like we [handle json](https://github.com/starlite-api/starlite/blob/main/starlite/connection/request.py#L81) in `Request`?

**Comment by Goldziher** [comment]
if this is not being worked on, we can remove the assignee. Do you intend to add a PR in the near future @jenish2014 ?

**Comment by jenish2014** [comment]
Yes @Goldziher , I'll submit a PR today it self.

**Comment by provinzkraut** [comment]
Added in #1086
