### ISSUE TITLE
How to use socketio with

### ISSUE THREAD

**Issue by tsiresymila16** [starlite-api/starlite#96]
Hi, Guys, I want to know, how to implement socketio  with this.

**Comment by Goldziher** [comment]
Hi there,

I haven't tried it but looking at the codebase of the python socket.io implementation, i see this:

https://github.com/miguelgrinberg/python-socketio/blob/main/src/socketio/asgi.py

Which extends this:

https://github.com/miguelgrinberg/python-engineio/blob/47ada56b1ada2ed6eeb8c0fe172045bed321a037/src/engineio/async_drivers/asgi.py

So, once you have an instance of `socket.io` ASGIApp, you could simply use the `@asgi` route handler decorator from Starlite to set it under a specfic place.

This is basically a mock implementation, so don't take it as real code:

```python
from starlite import asgi

@asgi("/somepath")
def my_handler(scope: Scope, receive: Receive, send: Send) -> None:
     # any code you like here
     # ....
     my_socket_io_asgi_app(scope, receeive, send)
```
