### ISSUE TITLE
Enhancement: Support accessing raw request body in sync handlers

### ISSUE THREAD

**Issue by provinzkraut** [starlite-api/starlite#960]
**What's the feature you'd like to ask for.**
Currently, the only way to get access to the raw request body is through `Request.body()`, which returns a coroutine and therefore doesn't work in synchronous handlers. This is a common pain point and much requested feature in Starlette/FastAPI, and it would be really nice to have.

**Possible solutions**
1. Support "raw" encoding type for `Body`
    - Pros: Easy to implement, does not break any existing code
    - Cons: We would need to add a non-standard "virtual" encoding type that doesn't correspond to an actual request encoding
2. Add a `body` reserved-kwarg
    - Pros: Cleanest solution, users would only have to add `body: bytes` to receive the body
    - Cons: Possibly breaks existing code, is inconsistent with the current usage of `Body`

Approach 1 in code:
```python
from starlite import post, Body, RequestEncodingType

@post(path="/")
async def handler(data: bytes = Body(media_type=RequestEncodingType.RAW)) -> Dict:
    ...
```
Approach 2 in code:
```python
from starlite import post, Body

@post(path="/")
async def handler(body: bytes) -> Dict:
    ...
```

**Comment by Goldziher** [comment]
How would one look in actual code?

**Comment by provinzkraut** [comment]
@Goldziher I added examples for both

**Comment by Goldziher** [comment]
Option 1 can't work as is- we use the RequestEncoding to determine how we should deserialize the data AND generate schema. 

In either case, what's the use case for these two?

**Comment by provinzkraut** [comment]
> In either case, what's the use case for these two?

Accessing raw request body in sync handlers.

Probably should have used sync handlers in de examples as well 😉

**Comment by Goldziher** [comment]
> > In either case, what's the use case for these two?
> 
> Accessing raw request body in sync handlers.
> 
> Probably should have used sync handlers in de examples as well 😉

Ok, examples are not a compelling reason to do this imo. Any other use case?

**Comment by provinzkraut** [comment]
> Ok, examples are not a compelling reason to do this imo. Any other use case?

WDYM? The use case **is** being able to access the raw request body in sync handlers. We can opt to go the same route as Starlette, FastAPI and others went there, but it's sub-optimal IMO, since it means that synchronous handlers are a second class citizen, which isn't true for almost every other aspect of Starlite. 

The usual response to this is "Just use an async endpoint", but sometimes that's just not an option, and we'd be forcing the user to resort to something like `anyio.run(request.body)` or some other workarounds.

I really don't see why we should *not* support this. We give users access to form data, files and json in sync endpoints. Why not the raw body? It feels like an arbitrary limitation to me, and something that always bothered me about Starlette.

**Comment by Goldziher** [comment]
> > Ok, examples are not a compelling reason to do this imo. Any other use case?
> 
> WDYM? The use case **is** being able to access the raw request body in sync handlers. We can opt to go the same route as Starlette, FastAPI and others went there, but it's sub-optimal IMO, since it means that synchronous handlers are a second class citizen, which isn't true for almost every other aspect of Starlite. 
> 
> The usual response to this is "Just use an async endpoint", but sometimes that's just not an option, and we'd be forcing the user to resort to something like `anyio.run(request.body)` or some other workarounds.
> 
> I really don't see why we should *not* support this. We give users access to form data, files and json in sync endpoints. Why not the raw body? It feels like an arbitrary limitation to me, and something that always bothered me about Starlette.

Well, come up with at least one use case for this and we'll do it 😁, but just because is not a reason.

**Comment by Goldziher** [comment]
After thinking on it and talking in discord - this makes sense also for sync dependencies. For example, support parsing non json data like XML etc
