### ISSUE TITLE
Enhancement: Use asgiref for typing

### ISSUE THREAD

**Issue by relsunkaev** [starlite-api/starlite#97]
Starlette's ASGI types use `MutableMapping[str, Any]` which is not too different from just typing them `dict`. This package is fully spec compliant and would help in implementing additional ASGI functionality, as it would allow us to see exactly which keys are available/required to support a feature. There is currently [a PR](https://github.com/encode/starlette/pull/1374) for Starlette that addresses this but it doesn't seem like it would be merged soon.

**Comment by Goldziher** [comment]
PR is welcome

**Comment by relsunkaev** [comment]
There is currently a discussion going on about splitting away the types from `asgiref` into a separate package. It would allow maintainers to depend on just what they need for typing instead of the entirety of `asgiref`.

**Comment by Goldziher** [comment]
i saw that kludex released a version of the typing as an independent package. would you like to implement this @relsunkaev ?

**Comment by Goldziher** [comment]
So I checked this out. It seems that we cannot really use asgiref for typing as is because their typing of scope is too restrictive. We will first need to make some PRs to asgiref to fix this, or we will simply need to create a small version of this package on our end.

**Comment by Goldziher** [comment]
The scope

**Comment by Goldziher** [comment]
Ok @relsunkaev - im closing this issue. Feel free to reopen if and when asgief is updated and you have capacity to do the job .

**Comment by Goldziher** [comment]
@relsunkaev - it took a while, but i made this change. Welcome to check it out.
