### ISSUE TITLE
Bug: Setting "cache=True" Results in a 500 Error

### ISSUE THREAD

**Issue by bwhli** [starlite-api/starlite#971]
In the [Starlite docs](https://starlite-api.github.io/starlite/usage/15-caching/1-response-caching/), it says the following:

> By setting cache=True in the route handler, caching for the route handler will be enabled for the default duration, which is 60 seconds unless modified.

However, when I try to set `cache=True` like this:

```
@get(path="/", cache=60)
    async def get_transactions(self) -> list[Transaction]:
        transactions = await Tracker.get_transactions()
        return transactions
```

I receive the following exception when visiting the endpoint:

```
{
  "status_code": 500,
  "detail": "DataError("Invalid input of type:  'bool'. Convert to a bytes,
   string,
   int or float first.")"
}
```

When I switch it to `cache=60`, it works fine! So it seems like there could be an issue with converting `True` to `60`.

**Comment by provinzkraut** [comment]
I cannot reproduce this. 

The following works fine for me:
```python
from starlite import get, create_test_client


@get("/", cache=True)
async def index() -> dict[str, str]:
    return {"hello": "world"}


with create_test_client([index]) as client:
    assert client.get("/").json() == {"hello": "world"}
    assert client.get("/").json() == {"hello": "world"}
```

Can you provide a reproducible example? 
If you need examples for what a minimal, self-contained example should look like, you can check [issues with the "great-mcve" label](https://github.com/starlite-api/starlite/issues?q=+is%3Aissue+label%3Agreat-mcve).

**Comment by Goldziher** [comment]
@bwhli - please provide a reproduction.
