### ISSUE TITLE
Bug:  Upload of single file doesn't work in Swagger UI

### ISSUE THREAD

**Issue by TorbranTundra** [starlite-api/starlite#978]
**Describe the bug**
Uploading a single file doesn't work. Here's the error:
![image](https://user-images.githubusercontent.com/12883475/209139354-e43abf17-b79d-4390-a727-6723e0566a84.png)

"instance of UploadFile expected"

**To Reproduce**
To reproduce:

```
   @post(path="/")
    async def handle_file_upload(
        data: UploadFile = Body(media_type=RequestEncodingType.MULTI_PART)
    ) -> str:
        return "success"
```

**Comment by provinzkraut** [comment]
Duplicate of: #941
