### ISSUE TITLE
Bug: path parameters must have the same name for different HTTP methods

### ISSUE THREAD

**Issue by MatthewNewland** [starlite-api/starlite#986]
**Describe the bug**
If I register two route handlers with path parameters for the same route, say a "GET" and a "POST", and name the path parameters different things in the path string for each of the parameters, then only one of the handlers will successfully be registered.

**To Reproduce**
A minimal example is given here:
```python
from starlite import Starlite, get, post


@get("/{name:str}")
def get_greeting(name: str) -> str:
    return f"Hello, {name}!"


@post("/{title:str}")
def post_greeting(title: str) -> str:
    return f"Hello, {title}!"


app = Starlite(
    route_handlers=[get_greeting, post_greeting]
)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("example:app")
```
Saving the above to `example.py`, I get the following cURL outputs:
```shell
>>> curl http://localhost:8000/world -X GET
{"status_code":400,"detail":"Missing required parameter name for url http://localhost:8000/world"}
>>> curl http://localhost:8000/world -X POST
"Hello, world!"
```

But if I change the first route handler to be:
```python
@get("/{title:str}")
def get_greeting(title: str) -> str:
    return f"Hello, {title}!"
```
then both GET and POST works just fine.

**Comment by Goldziher** [comment]
This was not a bug - it was intentional behaviour. The bug was that an exception was not raised for this. But I decided to support this use case instead - so the above examples work - in the currently open PR. If you have time to test this PR @MatthewNewland , that would be nice.

**Comment by MatthewNewland** [comment]
It works with the minimal example above and also with the more involved app I originally encountered the bug in.

I did wonder if it might be intended behavior, but wasn't able to find anything in docs specifying that it was. Please feel free to close this bug as you see fit, or change it to a feature request. Thank you so much for the quick reply!
