### ISSUE TITLE
Bug: 1.47.0 Missing "Testing" Extra

### ISSUE THREAD

**Issue by rgajason** [starlite-api/starlite#997]
**Describe the bug**
Starlite 1.47.0 does not include the "testing" extra

**To Reproduce**
```
$ pip3 install 'starlite[testing]>=1.47.0'
...
WARNING: starlite 1.47.0 does not provide the extra 'testing'
...
```

**Additional context**
Testing extra referenced in docs:

https://starlite-api.github.io/starlite/main/usage/9-testing/0-intro/

**Comment by provinzkraut** [comment]
Thanks for the report!

The extra is not needed anymore and the reference can be removed from the docs. Feel free to open a PR!

**Comment by rgajason** [comment]
@provinzkraut as requested...
